openyurtio/openyurt

README.md, config/setup/yurt-ctrl-mgr.yaml, config/setup/yurthub.yaml, docs/tutorial/yurtctl.md, pkg/yurtctl/constants/constants.go
1. Edit get started section
2. fix minor yaml error
=> Edit Readme

README.md, cmd/yurt-controller-manager/app/options/options.go, cmd/yurthub/app/options/options.go, pkg/yurthub/cachemanager/cache_agent_test.go, pkg/yurthub/storage/disk/storage_test.go
To improve code quality, we should check go report. This change fixes some of the reported warnings. A full report can be found in https://goreportcard.com/report/github.com/alibaba/openyurt
=> Add go report and fix part of reported errors

go.mod
=> change github.com/googleapis/gnostic version

docs/tutorial/yurtctl.md
Mostly small editions here and there.
=> Revise yurtctl tutorial

config/setup/yurt-controller-manager.yaml, config/setup/yurthub.yaml, config/yurtctl-servant/setup_edgenode, go.sum, pkg/yurtctl/cmd/revert/revert.go, pkg/yurtctl/constants/constants.go
1. switch to the latest version of yurthub and yurt-controller-manager
2. change image and command name
=> switch to the latest image

config/setup/yurthub.yaml, config/yurtctl-servant/setup_edgenode, docs/tutorial/yurtctl.md, pkg/yurtctl/constants/constants.go
1. change setup_edgenode to support converting ack cluster
2. fix some minor bugs
3. revise the yurtctl tutorial by adding ack related contents
=> add support for ack 

Makefile, build/release-images.sh, config/yurtctl-servant/setup_edgenode, docs/todo.md, pkg/yurtctl/cmd/convert/convert.go, pkg/yurtctl/cmd/revert/revert.go, pkg/yurtctl/constants/constants.go
1. allow user to specify the images of yurthub, yurt-controller-manger and yurtctl-servant
2. make relase also build yurtctl-servant images
=> allow user to specify image

docs/tutorial/yurtctl.md, pkg/yurtctl/cmd/cmd.go, pkg/yurtctl/cmd/convert/convert.go, pkg/yurtctl/cmd/markautonomous/markautonomous.go, pkg/yurtctl/cmd/revert/revert.go, pkg/yurtctl/util/kubernetes/util.go
1. implement the `markautonomous` subcommand
2. fix golint warning
3. revise the tutorial based on `markautonomous`
4. extract the common function
=> implement the markautonomous subcommand

pkg/yurthub/README.md
add trouble shooting in readme
=> update yurthub doc 

pkg/yurtctl/cmd/cmd.go, pkg/yurtctl/cmd/convert/convert.go, pkg/yurtctl/cmd/revert/revert.go
1. allow the user to set the verbose level for log
2. add detailed logs
3. not setting err in defer function
=> fix the defer function bug

.travis.yml
=> add .travis.yaml

README.md
There are three changes in this PR:
1. Fix image align
It looks like there is a logo aligning by `align="middle"`, but not work in GitHub README.md. So, I changed it to another format.
2. Add version badge
I also added a version badge, which can redirect to [CHANGELOG.md](https://github.com/alibaba/openyurt/blob/master/CHANGELOG.md).
3. Typo
=> Some improvments in README.md

pkg/yurttunnel/agent/agent.go, pkg/yurttunnel/agent/cmd.go, pkg/yurttunnel/constants/constants.go, pkg/yurttunnel/pki/certmanager/certmanager.go, pkg/yurttunnel/pki/certmanager/csrapprover.go, pkg/yurttunnel/server/cmd.go
1. implement the certmanager util, which will create certificate managers for both yurttunnel-server and yurttunnel-agent. 
2. implement a csr controller that will approve yurttunnel related csrs.
=> Implement the certmanager

CODE_OF_CONDUCT.md, CONTRIBUTING.md
This change adds the code of conduct and contributing documents for the openyurt project.
=> Docs: Add code of conduct and contributing documents

README.md, docs/roadmap.md
This changes add the project roadmap for 2020 Q3.
=> Docs: Add project roadmap

pkg/yurtctl/cmd/revert/revert.go
Bugfix: fix wrong log for yurtctl revert.
=> Bugfix: fix wrong log for yurtctl revert.

README.md, docs/developer-guide.md
This change revises the README.md to add more formal descriptions about this project.
=> Docs: Revise README.md

GOVERNANCE.md, MAINTAINERS.md
This change adds GOVERNANCE.md and MAINTAINERS.md for the project
=> Docs: Add GOVERNANCE.md and MAINTAINERS.md

cmd/yurthub/app/config/config.go, pkg/yurthub/cachemanager/fake_storage_wrapper.go, pkg/yurthub/cachemanager/storage_wrapper.go, pkg/yurthub/gc/gc.go, pkg/yurthub/proxy/remote/loadbalancer.go, pkg/yurthub/storage/fake/fake_storage.go
Give the capacity of slice and map to avoid expansion
=> Improvement: Give the capacity of slice and map

docs/tutorial/yurt-e2e-test.md, test/e2e/common/node/user/user.go, test/e2e/e2e_test.go, test/e2e/yurt/yurt.go, test/e2e/yurtconfig/yurtconfig.go, test/e2e/yurthub/yurthub.go
1) Yurthub node autonomy test, including creating pod, checking pod status after restarting node, and removing pod and so on;
2) Add an example of testing node autonomy in docs
=> Test:add yurthub node autonomy test and docs

docs/developer-guide.md
=> Docs: modify e2e tutorial link

Makefile, build/release-images.sh, config/yaml-template/yurt-controller-manager.yaml, config/yaml-template/yurt-tunnel-agent.yaml, config/yaml-template/yurt-tunnel-server.yaml, config/yaml-template/yurthub.yaml, hack/lib/build.sh, hack/make-rules/genyaml.sh, pkg/yurttunnel/constants/constants.go, pkg/yurttunnel/projectinfo/projectinfo.go
1. allow user to set the label prefix (default: openyurt.io)
2. implement a new make rule that allows users to generate setup yaml file
with different PROJECT_PREFIX, LABEL_PREFIX, image REPO and TAG
e.g.,
```bash
PROJECT_PREFIX=edge LABEL_PREFIX=alibabacloud.com make gen-yaml WHAT=cmd/yurthub
```
=> Feature: allow user to set the label prefix

config/yurtctl-servant/setup_edgenode, hack/lib/build.sh, pkg/controller/nodelifecycle/node_lifecycle_controller.go, pkg/yurthub/proxy/util/util.go
Bugfix: fix some errors found by staticcheck
=> Bugfix: fix some errors found by staticcheck

test/e2e/e2e_test.go, test/e2e/yurthub/yurthub.go, test/e2e/yurttunnel/yurttunnel.go
1)Test: add partial code for yurttunel e2e test
=> TEST: add yurttunnel e2e test some code

test/e2e/yurttunnel/yurttunnel.go
TEST: add run exec code and check result for yurttunnel e2e
=> TEST: add run exec code for yurttunnel e2e

README.zh.md
Translate the README file into Chinese, try to help user understand the project better.
=> Docs: add chinese version README file

CHANGELOG.md, README.md, docs/tutorial/README.md, docs/tutorial/manually-setup.md, docs/tutorial/yurt-tunnel.md
This change prepares the documents for 0.2.0 release.
=> [Doc] Add 0.2.0 CHANGELOG

docs/tutorial/yurtctl.md, hack/lib/release-images.sh
1. update the yurtctl tutorial
2. fix build script bug
=> Docs: update the yurtctl tutorial

README.md
1. Bi-weekly APAC OpenYurt Community meeting
2. Meeting  link and agenda
=> Docs: add APAC Friendly Community meeting info.

pkg/yurtctl/cmd/convert/convert.go, pkg/yurtctl/constants/constants.go, pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go, pkg/yurtctl/util/kubernetes/util.go
bind the cluster role cluster-admin to kube-system:default 
fix #106
=> Debug: grant the privilege of accessing lease resource to YCM

pkg/yurtctl/cmd/revert/revert.go
=> Validate status of worker node before run "revert"

pkg/yurthub/util/connrotation.go
- background:
1. tcp connection creation path:  yurthub proxy request --> http.Transport.RoundTrip() --> connRotation.dialer.Dial() --> net.Dial(), and net.Conn reference is stored in the connRotation.dialer
2. tcp connection is closed in the followint two paths.
- path1:  yurthub healthchecker --> connRotation.dialer.Close(address string)
- path2:  when idle timeout happen, http.Transport --> net.Conn.Close()
in the close path1, net.Conn reference is removed in connRotation.dialer, but in close path2,  the connection reference info will always be remained in the connrotation dialer, so may cause yurthub memory leak.
- solution:
add closable connection and overwrite net.Conn Close func, so close path2 becomes like this:  
--> close path2: when idle timeout happen, http.Transport --> …
=> bugfix: remove conn reference info in dialer when underlying tcp connection is closed by http transport

README.md
=> Add slack channel information in README

cmd/yurt-controller-manager/app/controllermanager.go, cmd/yurt-controller-manager/app/options/options.go, cmd/yurthub/app/options/options.go, cmd/yurthub/app/start.go, pkg/projectinfo/projectinfo.go, pkg/yurtctl/cmd/cmd.go, pkg/yurttunnel/agent/cmd.go, pkg/yurttunnel/server/cmd.go
To better track component functionality and issues, add version information to each component
=> refactor: add print version information for all components

pkg/yurtctl/cmd/revert/revert.go
Seems the new added resource not remove when run `Revert`, it will block second time `Convert`
=> Remove SA, Clusterrole, Clusterrolebinding for controller-mangement when Revert

pkg/yurttunnel/pki/certmanager/csrapprover.go
=> if failed to get the csr object, requeue it using the old key 

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/question.md, .github/PULL_REQUEST_TEMPLATE.md
add template for adding issue and pr
=> docs: add template for adding issue and pr

README.md, README.zh.md
update the links in readME, such as chinese README, Meeting recordings, slack, etc
=> docs: upgrade readme

docs/tutorial/yurtctl.md
=> update docs: add acr convert image

pkg/yurttunnel/pki/certmanager/csrapprover.go
fix an panic when `yca.csrInformer.Lister().Get(csrName)` returns nil and error, and then comes into `approveYurttunnelCSR` process because not return when error happened, then a panic will be triggered.
First of all, this scenario is not easy to reproduce. 
It requires that an update of the CSR has just occurred before the CSR is deleted. This starts the CSR sync processing, and Lister can returns an error.
=> bugfix: fix panic when csr is not found in lister

pkg/yurttunnel/iptables/iptables.go, pkg/yurttunnel/pki/certmanager/csrapprover.go, pkg/yurttunnel/server/cmd.go
refactor the usage of sharedIndexInformer:
--> after configured all of resource informers completed, then start the sharedIndexInformer, rather than configured one informer then start this informer. because the later configuration to already started informer can not take effect.
make test
make build
and run yurt-tunnel to verify iptables setting on cloud node is correct and
certificate of tunnel-server has been created.
=> refactor: the usage of sharedIndexInformer

go.mod, go.sum, pkg/yurttunnel/agent/cmd.go, pkg/yurttunnel/handlerwrapper/tracerequest/tracereq.go, pkg/yurttunnel/iptables/iptables.go, pkg/yurttunnel/server/anpserver.go, pkg/yurttunnel/server/cmd.go, pkg/yurttunnel/server/interceptor.go
1. refactor tunnel setup for interceptor, add a context dialer into interceptor for setting up tunnel
2. support log flush feature
3. other small fix
make test
make build
and exec command `kubectl logs -f/kubectl exec` to check the tunnel proxy is work or not
=> refactor: add a context dialer for setting up tunnel conn and support logs flush

pkg/yurttunnel/iptables/iptables.go
Trim one or more '-' in ProjectPrefix.
=> Fix: trim all trailing '-' characters of project prefix

pkg/yurttunnel/server/cmd.go
=> Fix wrong function call

pkg/yurtappmanager/controller/controllers.go, pkg/yurtappmanager/controller/nodepool/nodepool_controller.go, pkg/yurtappmanager/controller/nodepool/nodepool_enqueue_handlers.go, pkg/yurtappmanager/webhook/add_nodepool.go, pkg/yurtappmanager/webhook/nodepool/mutating/nodepool_create_update_handler.go, pkg/yurtappmanager/webhook/nodepool/mutating/webhooks.go, pkg/yurtappmanager/webhook/nodepool/validating/nodepool_create_update_handler.go, pkg/yurtappmanager/webhook/nodepool/validating/nodepool_validation.go, pkg/yurtappmanager/webhook/nodepool/validating/webhooks.go
This PR implements the nodepool controller, which will
1. group nodes based on the label
2. manage nodepool related attributes (labels/annotations/taints) for corresponding nodes
NONE
NONE
This PR doesn't need to be verified.
This PR only includes the main logic of node controller, and it can't be compiled yet. Makefile rules and other configuration files will be added in the next PR.
=> feature: nodepool controller

pkg/yurtctl/cmd/convert/convert.go, pkg/yurtctl/util/kubernetes/util.go
create a cluster-info configmap in the cluster before converting a k8s cluster to openyurt cluster, because yurthub will use this configmap to bootstrap the edge node.  and when k8s cluster was set up by kubeadm tool, the cluster-info configmap is created by default.
=> Feature: create cluster-info configmap by yurtctl for adapting cert-mode=hubself of yurthub

config/setup/yurt-tunnel-agent.yaml, config/setup/yurt-tunnel-server.yaml, config/yaml-template/yurt-tunnel-agent.yaml, config/yaml-template/yurt-tunnel-server.yaml, config/yurtctl-servant/setup_edgenode, pkg/yurtctl/constants/yurt-tunnel-agent-tmpl.go, pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go
refactor the templates of yurt-hub and yurt-tunnel.
(1) fix yurt-tunnel volume  path.
(2)add volume kubernetes for yurthub.
No issue, the reason for the modification is as follows:
yurthub use volume kubernetes for caching.
make test
make build
_output/bin/yurtctl convert --provider [minikube|ack|kubeadm]
=> refactor the templates of yurt-hub and yurt-tunnel.

Makefile, README.md, config/yurt-app-manager/release/yurt-app-manager-v0.3.0.yaml, docs/developer-guide.md, docs/tutorial/yurt-app-manager-dev.md, docs/tutorial/yurt-app-manager.md, hack/lib/build.sh
Signed-off-by: kadisi <iamkadisi@163.com>
add tutorial for yurt-app-manager  
ref #171 
@Fei-Guo @charleszheng44 @rambohe-ch
=> add tutorial for yurt-app-manager 

config/yurt-app-manager/default/kustomization.yaml, config/yurt-app-manager/default/manager_auth_proxy_patch.yaml, config/yurt-app-manager/default/manager_webhook_patch.yaml, config/yurt-app-manager/manager/manager.yaml, config/yurt-app-manager/manager/patches.yaml, config/yurt-app-manager/prometheus/monitor.yaml, config/yurt-app-manager/rbac/auth_proxy_service.yaml, config/yurt-app-manager/release/yurt-app-manager-v0.3.0.yaml, config/yurt-app-manager/webhook/service.yaml, pkg/yurtappmanager/webhook/util/configuration/configuration.go, pkg/yurtappmanager/webhook/util/controller/webhook_controller.go, pkg/yurtappmanager/webhook/util/util.go
Signed-off-by: kadisi <iamkadisi@163.com>
change yurt app manager yaml, update labels and name
cc @rambohe-ch
=> change yurt app manager yaml

CHANGELOG.md, README.md, README.zh.md
This change prepares the documents for 0.3.0 release.
=> [Doc] Add 0.3.0 CHANGELOG

README.md, README.zh.md
update version info and replace unit with pool in Readme
=> [Doc] update readme

config/yurt-app-manager/manager/manager.yaml
Signed-off-by: kadisi <iamkadisi@163.com>
=> delete system namespaces for yurt-app-manager yaml

README.md, README.zh.md
=> docs: revise readme

pkg/yurttunnel/server/serveraddr/addr_test.go
=> Add serveraddr/addr.go unit test

pkg/yurtappmanager/controller/nodepool/nodepool_controller.go, pkg/yurtappmanager/controller/nodepool/nodepool_controller_test.go
1. remove redundant function
2. Add unit tests for node controller. 
NONE
unit tests:
TestConciliateAnnotations
TestConciliateLables
TestConciliateTaints
TestContainTaint
TestIsNodeReady
TestMergeMap
TestRemoveTaint
`go test -v github.com/alibaba/openyurt/pkg/yurtappmanager/controller/nodepool`
None
=> add ut for nodepool controller

hack/lib/build.sh, hack/lib/common.sh, hack/lib/init.sh, hack/lib/release-images.sh, hack/make-rules/build-e2e.sh, hack/make-rules/build.sh
1. save multi-platform binaries in the subdirectory
2. use a symlink to binaries for the current platform
Fixes: #195
make build
=> Using symlink to binaries for current platform

pkg/yurttunnel/server/serveraddr/addr.go
=> slove ips repeated question from addr.go

README.md, README.zh.md, docs/roadmap.md
- add 2021 roadmap
- add cncf info for openyurt
=> revise readme and 2021 roadmap

.github/workflows/markdown-link-check.config.json
=> Docs: revise link check of workflow

MAINTAINERS.md, OWNERS
=> Docs: welcome yixingjia from VMware as OpenYurt Maintainer

README.md, README.zh.md
update mailing list and slack info
fixes #241
=> docs: update mailing list and slack link

config/setup/yurt-controller-manager.yaml, config/setup/yurt-tunnel-agent.yaml, config/setup/yurt-tunnel-server.yaml, config/setup/yurthub.yaml, config/yaml-template/yurt-controller-manager.yaml, config/yaml-template/yurt-tunnel-agent.yaml, config/yaml-template/yurt-tunnel-server.yaml, docs/tutorial/manually-setup.md, docs/tutorial/yurt-tunnel.md, docs/tutorial/yurtctl.md, pkg/yurtctl/cmd/convert/convert.go, pkg/yurtctl/cmd/revert/edgenode.go, pkg/yurtctl/cmd/revert/revert.go, pkg/yurtctl/constants/yurt-tunnel-agent-tmpl.go, pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go
update yaml file for yurt-tunnel, and revise tutorial docs.
make build WHAT=cmd/yurtctl
=> docs: revise tutorial docs and yaml file

pkg/yurthub/storage/disk/storage.go
=> bugfix: modify the RWMutex lock to Mutex lock

config/setup/yurt-tunnel-agent.yaml, config/yaml-template/yurt-tunnel-agent.yaml
=> solve the problem #274

pkg/yurttunnel/dns/dns.go
Follow up #270
bugfix: fix the bug that dns controller updates dns records incorrectly
/cc @rambohe-ch
=> bugfix: fix the bug that dns controller updates dns records incorrectly

pkg/yurtctl/cmd/convert/convert.go, pkg/yurtctl/cmd/convert/edgenode.go, pkg/yurtctl/constants/constants.go
Feature: add `yurthub-healthcheck-timeout` flag for `yurtctl convert` command.
This PR makes the Yurthub health-check timeout configurable for extreme scenarios, such as slow image downloads.
`yurtctl convert`
=> feature: add 'yurthub-healthcheck-timeout' flag for 'yurtctl convert' command

pkg/yurtctl/cmd/convert/convert.go, pkg/yurtctl/cmd/convert/edgenode.go, pkg/yurtctl/constants/constants.go
This PR improves version compatibility of `yurtctl`, followup #290 
Fixes: #293
=> improve version compatibility of yurtctl

pkg/yurthub/proxy/util/util.go
Fixed incorrect annotation in code comments.
=> Fixed incorrect representation in code comments.

CHANGELOG.md, README.md, README.zh.md, hack/lib/init.sh
More than 20 friends had contributed to version OpenYurt 0.4.0, Thanks.
=> [Doc] Add 0.4.0 CHANGELOG

OWNERS
=> Add the Owner configuration

docs/tutorial/README.md
=> update tutorial README

.github/PULL_REQUEST_TEMPLATE.md
=>  change pull request template

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/failing-test.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/question.md
=> perfect issue template

.github/PULL_REQUEST_TEMPLATE.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Fixes #
```release-note
```
=> change pull request template

GOVERNANCE.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
add community membership info into governance.md file 
/assign @Fei-Guo 
```release-note
```
=> doc: add community membership into governance.md

pkg/controller/nodelifecycle/scheduler/taint_manager.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Fixes #
```release-note
```
=> add logs for eviction error

CHANGELOG.md, README.md
add changelog of releasing node-resource-manager
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Fixes #
```release-note
```
=> v0.4.0: release node-resource-manager

pkg/yurtctl/util/kubernetes/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Fixes #327 
```release-note
```
=> Yurtctl code adds the verification of cluster version 1.20 and above.

README.md, README.zh.md
This PR updates the slack invitation link which is valid for 30 days (unfortunately).
=> Update slack invitation link

config/setup/yurt-tunnel-agent.yaml, config/yaml-template/yurt-tunnel-agent.yaml
add tolerations for yurt-tunnel-agent in order to avoid confict with nodepool taints
/kind bug
=> add tolerations for yurt-tunnel-agent in order to avoid confict with nodepool taints

pkg/yurthub/healthchecker/health_checker.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Close the underlying connection between yurthub and kube-apiserver every time when the heartbeat check fails.
Fixes #
```release-note
```
=> enhancement: close the underlying connections every time the heartbeat fails

cmd/yurthub/app/config/config.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
Pod will make https request to access master in default `InClusterConfig`, so we need to modify mutated master server address to yurthub's https server address.
Fixes #
```release-note
```
=> fix mutated master service address from yurthub's http server address to https server address.

CHANGELOG.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
add release note of OpenYurt v0.4.1
Fixes #
```release-note
```
=> doc: add release note of OpenYurt v0.4.1

README.md, docs/tutorial/yurtctl.md, pkg/yurtctl/cmd/cmd.go, pkg/yurtctl/cmd/join/phases/constants.go, pkg/yurtctl/cmd/join/phases/prepare.go, pkg/yurtctl/cmd/reset/phases/cleanfile.go, pkg/yurtctl/cmd/reset/reset.go, pkg/yurtctl/constants/constants.go
/kind feature
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
add subcommand reset to yurtctl, reference proposal https://github.com/openyurtio/openyurt/blob/master/docs/proposals/20210607-adding-subcommands-server-join-reset-for-yurtctl.md
Fixes #
```release-note
```
=> add reset subcommand.

pkg/yurttunnel/pki/pki.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
`RootCAs` defines the set of root certificate authorities that clients use when verifying server certificates.
`ClientCAs` defines the set of root certificate authorities that servers use if required to verify a client certificate by the policy in ClientAuth.
`TunnelServer` who includes `MasterServer` and `AgentServer` should use `ClientCAs`.
Fixes #
```release-note
NONE
```
=> fix server tls config

pkg/yurtctl/cmd/cmd.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind feature
Fixes #
```release-note
```
=> Yurtctl: more comfortable command line

cmd/yurthub/app/start.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
Fixes #
```release-note
```
=> remove excess chan that will block the program

hack/lib/build.sh, hack/lib/common.sh, hack/lib/init.sh, hack/lib/release-images.sh, hack/make-rules/build.sh, hack/make-rules/release-images.sh
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
Fixes #
```release-note
```
=> The shebang must be on the first line. Delete blanks and move comments

cmd/yurthub/app/start.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind feature
Fixes #
```release-note
```
=> Yurthub: remove duplicate error logs

README.md, docs/tutorial/yurtctl.md, go.mod, go.sum, pkg/yurtctl/cmd/cmd.go, pkg/yurtctl/cmd/convert/convert.go, pkg/yurtctl/cmd/join/phases/join-cloud-node.go, pkg/yurtctl/cmd/join/phases/join-edge-node.go, pkg/yurtctl/cmd/join/phases/postcheck.go, pkg/yurtctl/cmd/join/phases/type.go, pkg/yurtctl/cmd/yurtinit/init.go, pkg/yurtctl/cmd/yurtinit/phases/controlplane.go, pkg/yurtctl/cmd/yurtinit/phases/install_cni.go, pkg/yurtctl/cmd/yurtinit/phases/install_yurt_addons.go, pkg/yurtctl/cmd/yurtinit/phases/labelCloudNode.go, pkg/yurtctl/cmd/yurtinit/phases/prepare.go, pkg/yurtctl/cmd/yurtinit/phases/types.go, pkg/yurtctl/constants/constants.go, pkg/yurtctl/util/kubernetes/apply_addons.go, pkg/yurtctl/util/kubernetes/util.go, pkg/yurtctl/util/system/util.go
yurtctl add init subcommand.
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind feature
Add init subcommand for yurtctl to create an OpenYurt cluster. Proposal: 
https://github.com/openyurtio/openyurt/blob/master/docs/proposals/20210607-adding-subcommands-server-join-reset-for-yurtctl.md
Fixes #
```release-note
```
=> Add init subcommand for yurtctl.

cmd/yurthub/app/start.go, pkg/yurthub/filter/constant.go, pkg/yurthub/filter/discardcloudservice/filter.go, pkg/yurthub/filter/filter.go, pkg/yurthub/filter/masterservice/filter.go, pkg/yurthub/filter/servicetopology/filter.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Add name info for filters in yurthub, meanwhile, add filter name in the log message in order to monitor status of the filter.
Fixes #
```release-note
```
=> enhancement: add name info for filters

docs/tutorial/yurt-tunnel.md, pkg/yurtctl/cmd/convert/edgenode.go
> fix typo
Fixes #
```release-note
```
=> fix typo; covert->convert

docs/proposals/20210722-yurtcluster-operator.md
/kind design
Update yurtcluster operator proposal
Fixes #
```release-note
NONE
```
=> Update yurtcluster operator proposal

hack/lib/release-images.sh
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
At present, we use golang version v1.13.15 to release OpenYurt images, on some arm64 arch nodes, system call from golang runtime may cause error, so we need to update golang version. and we select `golang:1.15-alpine` as OpenYurt build image.
Fixes #
```release-note
```
=> update golang version to v1.15.13

config/setup/yurthub.yaml, config/yaml-template/yurthub-cfg.yaml, config/yaml-template/yurthub.yaml, docs/tutorial/manually-setup.md, hack/lib/build.sh, pkg/yurtctl/cmd/convert/convert.go, pkg/yurtctl/util/edgenode/common.go, pkg/yurtctl/util/kubernetes/apply_addons.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
yurthub need to list/watch nodepool resource, so we need add these `RBAC` rights to `system:nodes` group because a node certificate have been applied by yurthub.
Fixes #
```release-note
```
=> bugfix: add rabc setting for yurthub

OWNERS
@SataQiu
openyurtio/openyurt
@rambohe-ch 
#452
#451
#442
#429
#378
#290
#283
#270
#202
- Issues :
#427
#453
[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation
=> Add SataQiu as a reviewer of openyurtio/openyurt

config/setup/yurt-controller-manager.yaml, config/setup/yurt-tunnel-server.yaml, config/setup/yurthub-cfg.yaml, config/yaml-template/yurt-controller-manager.yaml, config/yaml-template/yurt-tunnel-server.yaml, config/yaml-template/yurthub-cfg.yaml, pkg/yurtctl/constants/constants.go, pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go, pkg/yurtctl/util/edgenode/common.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
optimize rbac setting of certificate generation in yurt-controller-manager, yurt-tunnel-server, edge-hub components.
the reference link is here: https://raw.githubusercontent.com/kubernetes/website/main/content/zh/examples/access/certificate-signing-request/clusterrole-approve.yaml
Fixes #
```release-note
```
=> enhancement: optimize rabc setting of openyurt components

pkg/yurtctl/cmd/convert/convert.go, pkg/yurtctl/cmd/convert/edgenode.go, pkg/yurtctl/cmd/revert/edgenode.go, pkg/yurtctl/cmd/revert/revert.go, pkg/yurtctl/constants/constants.go, pkg/yurtctl/util/edgenode/util.go, pkg/yurtctl/util/edgenode/util_test.go
Fixes https://github.com/openyurtio/openyurt/issues/460
/assign @Peeknut 
removed `pod-manifest-path`  for both `yurtctl convert` and `yurtctl revert`
```release-note
rm --pod-manifest-path
```
=> read podManifestPath from kubeadm file

pkg/yurtctl/cmd/convert/edgenode.go
/kind bug
Fixes  https://github.com/openyurtio/openyurt/issues/486
=> rm duplicated code

cmd/yurthub/app/start.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
The health checker of yurthub is not needed in cloud mode. This PR will disable it when yurthub is working in cloud mode.
Fixes #
```release-note
```
=> enhancement: disable health checker in cloud mode

CHANGELOG.md, README.md, README.zh.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
update changeLog and readme for releasing OpenYurt v0.5.0
Fixes #
```release-note
```
=> docs: revise changelog and readme for releasing v0.5.0

config/setup/yurt-tunnel-server.yaml, config/yaml-template/yurt-tunnel-server.yaml, pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go
/kind bug
To avoid using different version of yurt-tunnel-agent and yurt-tunnel-server.
Fixes #511 
```release-note
```
=> pull yurt-tunnel-server image when IfNotPresent

README.md, README.zh.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
revise readme
Fixes #
```release-note
```
=> revise openyurt readme

pkg/yurthub/filter/constant.go, pkg/yurthub/filter/discardcloudservice/handler.go, pkg/yurthub/filter/servicetopology/handler.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
If LB service with `openyurt.io/skip-discard=true` annotation, discardcloudservice filter in yurthub will not filter the LB service, so end users can use the LB service at edge side.
Fixes #
```release-note
```
=> enhancement: add openyurt.io/skip-discard annotation verify for discardcloudservice filter

README.zh.md
This PR adds the live dome for openyurt + edgex integration in the README.zh.md
=> Add demo in the README.zh.md

OWNERS
@adamzhoul 
openyurtio
@rambohe-ch
- PRs reviewed/authored:
#516
#506
#500
#494
#492
#490
#473
#463
#459
- Issues :
#547
#546
#545
#544
#505
#502
#499
#498
#489
#488
#486
#485
#462
#461
#460
=> Add adamzhoul as reviewer of openYurt

OWNERS
@DrmagicE 
openyurtio
@rambohe-ch 
#513 
#510 
#509 
#495 
#483 
#381 
#222 
#218 
#205
- Issues :
#527
#450
#376
#504
#476
#212
=> Add DrmagicE as reviewer of OpenYurt

pkg/controller/nodelifecycle/node_lifecycle_controller.go, pkg/controller/nodelifecycle/node_lifecycle_controller_test.go, pkg/controller/nodelifecycle/scheduler/rate_limited_queue.go, pkg/controller/nodelifecycle/scheduler/taint_manager.go, pkg/controller/nodelifecycle/scheduler/taint_manager_test.go, pkg/controller/nodelifecycle/scheduler/timed_workers.go, pkg/controller/util/node/controller_utils.go
…pkg/controller path
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
The import package sort adjustment in the go file 
Fixes #564 
```release-note
```
=> The import package sort adjustment in the go file under the openyurt/pkg/controller path.

pkg/node-servant/components/yurthub.go, pkg/node-servant/convert/options.go, pkg/node-servant/job.go, pkg/node-servant/revert/options.go
…pkg/node-servant
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
The order of the go file import package is not standardized.
Fixes #574 
```release-note
```
=> The import package sort adjustment in the go file.

pkg/yurtctl/util/system/util.go
/kind bug
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Fixes #
issue: https://github.com/openyurtio/openyurt/issues/568
```release-note
```
=> modeprobe br-netfilter

MAINTAINERS.md
@gnunu
openyurtio
@rambohe-ch
* PRs reviewed / authored:
[Proposal: OpenYurt Convertor Operator for converting K8S to OpenYurt](https://github.com/openyurtio/openyurt/pull/389)
[Proposal: add dynamic load balancer support for openyurt](https://github.com/openyurtio/openyurt/pull/528)
[Proposal: add ingress feature support to nodepool](https://github.com/openyurtio/openyurt/pull/373)
* Issues :
[[feature request]Should an Operator be good to turn vanilla k8s cluster to OpenYurt one?](https://github.com/openyurtio/openyurt/issues/328)
=> Add gnunu (shaoqiang.chen@intel.com) as a maintainer of OpenYurt.

MAINTAINERS.md
Update the maintainer's affiliation and email.
NONE
NONE
NONE
=> Docs: update Chao's affiliation

MAINTAINERS.md
@qclc 
openyurtio
@rambohe-ch 
https://github.com/openyurtio/openyurt/pull/225
https://github.com/openyurtio/openyurt/pull/244
https://github.com/openyurtio/openyurt/pull/326
https://github.com/openyurtio/openyurt/pull/359
https://github.com/openyurtio/openyurt/pull/369
https://github.com/openyurtio/openyurt/pull/554
https://github.com/openyurtio/yurt-device-controller/pull/1
https://github.com/openyurtio/yurt-device-controller/pull/2
https://github.com/openyurtio/yurt-device-controller/pull/4
https://github.com/openyurtio/yurt-device-controller/pull/5
https://github.com/openyurtio/yurt-device-controller/pull/6
https://github.com/openyurtio/yurt-device-controller/pull/8
https://github.com/openyurtio/yurt-device-controller/pull/11 …
=> Add qclc as maintainer of OpenYurt

MAINTAINERS.md
@DrmagicE 
openyurtio
@rambohe-ch 
#513 
#510 
#509 
#495 
#483 
#381 
#222 
#218 
#205
- Issues :
#527
#450
#376
#504
#476
#212
=> Add DrmagicE as maintainer of OpenYurt

MAINTAINERS.md
@lwmqwer
openyurtio
@rambohe-ch
* Subproject: 
[Yurt-edgex-controller](https://github.com/openyurtio/yurt-edgex-manager)
* Issues:
#521
=> Add lwmqwer as maintainer of OpenYurt

hack/lib/release-images.sh
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
When build release from a proxy env, http[s]_proxy is needed within the build container.
Fixes #
```release-note
NONE
```
=> use https[s] proxy in docker for release build if necessary

docs/tutorial/README.md, docs/tutorial/service-topology.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
At present, there is a lack of documentation related to service topology.
Fixes #590 
/assign @rambohe-ch @qclc
=> Docs: add docs about service topology.

pkg/yurthub/certificate/certificate.go, pkg/yurthub/certificate/kubelet/cert_mgr.go, pkg/yurthub/healthchecker/health_checker.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Correct some comment lines who have obvious mistakes.
Fixes #
```release-note
```
=> correct the comment line

go.mod, pkg/util/iptables/iptables.go, pkg/util/iptables/iptables_linux.go, pkg/util/iptables/iptables_test.go, pkg/util/iptables/iptables_unsupported.go, pkg/util/iptables/monitor_test.go, pkg/util/iptables/save_restore.go, pkg/util/iptables/save_restore_test.go, pkg/util/iptables/testing/fake.go, pkg/yurthub/network/iptables.go, pkg/yurttunnel/trafficforward/iptables/iptables.go, pkg/yurttunnel/trafficforward/iptables/iptables_test.go
From kubernetes introduction: [ttps://github.com/kubernetes/kubernetes#to-start-using-k8s](https://github.com/kubernetes/kubernetes#to-start-using-k8s)
Fixes #453
```
none
```
```
none
```
=> Remove k8s.io/kubernetes dependency for yurt-tunnel

pkg/yurtctl/util/kubernetes/apply_addons.go, pkg/yurtctl/util/kubernetes/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Fixes #
```release-note
```
=> declare a const instead the string

hack/make-rules/build.sh
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind feature
hotfix build linux arch in macOS  'ln' not in this os
```release-note
in macOS exec `GOOS=linux GOARCH=amd64 make build WHAT=cmd/yurtctl`,but build after  the local dir ln  into  linux dir.
so I fix the `HOST_PLATFORM` default value is `$(go env GOOS)/$(go env GOARCH)`
```
=> ci(master): ln hotfix to build in macOS

pkg/yurttunnel/util/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Fixes #
```release-note
```
=> use const instead the magical number

hack/lib/release-images.sh, pkg/yurthub/filter/initializer/initializer.go, pkg/yurthub/filter/interfaces.go, pkg/yurthub/filter/servicetopology/filter.go, pkg/yurthub/filter/servicetopology/handler.go, pkg/yurthub/network/dummyif_linux.go, pkg/yurthub/proxy/remote/loadbalancer.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
add some comments to improve code readability.
adjust the order of some packages.
fix typo.
=> add some comments and adjust the order of some packages.

pkg/yurtctl/cmd/revert/cloudnode.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Fixes #
```release-note
```
=> Note bug: changing edge nodes to cloud nodes

hack/lib/release-manifest.sh
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
replace  DOCKER_BUILD_BASE_IDR => DOCKER_BUILD_BASE_DIR
Fixes #
```release-note
```
=> ci(master): replace  DOCKER_BUILD_BASE_IDR => DOCKER_BUILD_BASE_DIR

Makefile, pkg/util/iptables/iptables_unsupported_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind feature
add makefile ci tools and fix error golint in macos
Fixes #
```release-note
```
=> ci(master): add golint makefile

hack/lib/common.sh
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
replace ${binary_name} => $1
Fixes #
```release-note
```
=> ci(master): replace ${binary_name} => $1

docs/tutorial/prometheus.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
coredns min version tips
Fixes #
```release-note
```
=> ci(master): doc coredns min version tips

pkg/yurtctl/util/kubernetes/util.go
Enable `yurtctl convert` and `yurtctl revert` to support kubernetes v1.19 and v1.21.
Fixes #677 
```release-note
```
=> support of kubernetes v1.19 and v1.21

README.md, README.zh.md
update expired slack channel links in the ReadMe file
=> docs: update expired slack channel links

pkg/yurttunnel/util/util.go
=> Separator = replaced by cons

pkg/yurtctl/cmd/revert/revert.go
string var repaced by constant
=> string var repaced by constant

cmd/yurthub/app/options/options.go, pkg/yurthub/util/util.go
=> port repaced by constant

cmd/yurt-controller-manager/app/controllermanager.go
=> str replaced by const

.github/stale.yml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind feature
add stale bot config file
Fixes #701 
```release-note
```
=> [feature]add stale config file

CHANGELOG.md, README.md, README.zh.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
revise readme and changLog for releasing OpenYurt v0.6.0
Fixes #
/assign @Fei-Guo @gnunu @kadisi @SataQiu 
```release-note
```
=> [docs] revise readme and changelog for OpenYurt v0.6.0

README.zh.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
update README.zh.md file
Fixes #
```release-note
```
=> [docs] revise README.zh.md

pkg/controller/nodelifecycle/metrics.go
=> replaced zone by const

pkg/yurtctl/constants/constants.go, pkg/yurtctl/util/kubernetes/util.go
0755 dirmode replaced by Const
=> 0755 dirmode replaced by Const

pkg/yurtctl/util/edgenode/util.go
string var “=” repalced by const
=> string var repalced by const

pkg/yurtctl/cmd/yurtinit/init.go
=> fix dirmod replaced by Const

OWNERS
@zzguang 
openyurtio
@kadisi 
* PRs reviewed / authored:
[proposal: add ingress feature support to nodepool #373](https://github.com/openyurtio/openyurt/pull/373)
[ingress: update nodepool ingress proposal #645](https://github.com/openyurtio/openyurt/pull/645)
[ingress: add nodepool endpoints filtering for nginx ingress controller #696](https://github.com/openyurtio/openyurt/pull/696)
[Add YurtIngress operator implementation #32](https://github.com/openyurtio/yurt-app-manager/pull/32)
[ingress: fix YurtIngress CR status update error #33](https://github.com/openyurtio/yurt-app-manager/pull/33)
[update README to add YurtAppDaemon and YurtIngress #34](https://github.com/openyurtio/yurt-app-manager/pull/34)
[ingress: update yurtingress tutorial link …
=> add zzguang as reviewer of OpenYurt

OWNERS
@Congrool
@openyurtio
@rambohe-ch
openyurtio/openyurt#496
openyurtio/openyurt#512
openyurtio/openyurt#517
openyurtio/openyurt#520
openyurtio/openyurt#530
openyurtio/openyurt#540
openyurtio/openyurt#636
openyurtio/openyurt#655
openyurtio/openyurt#673
openyurtio/openyurt#678
openyurtio/openyurt#694
openyurtio/openyurt#698
openyurtio/openyurt.io#51
- Issues:
openyurtio/openyurt#484
openyurtio/openyurt#511
openyurtio/openyurt#531
openyurtio/openyurt#562
openyurtio/openyurt#677
openyurtio/yurt-app-manager#31
[devstats]: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community membership]: https://github.com/openyurtio/community/blob/main/community-membership.md
[dingding]: 31993519
[cncf/gitdm]: …
=> add Congrool as reviewer of OpenYurt

cmd/yurt-node-servant/convert/convert.go, cmd/yurt-node-servant/preflight-convert/preflight.go, cmd/yurt-node-servant/revert/revert.go, cmd/yurt-tunnel-agent/app/start.go, cmd/yurt-tunnel-server/app/start.go, pkg/node-servant/constant.go, pkg/util/certmanager/certmanager.go, pkg/yurtctl/cmd/clusterinfo/clusterinfo.go, pkg/yurtctl/cmd/convert/convert.go, pkg/yurtctl/cmd/join/join.go, pkg/yurtctl/cmd/markautonomous/markautonomous.go, pkg/yurtctl/cmd/revert/revert.go, pkg/yurthub/cachemanager/cache_manager.go, pkg/yurthub/cachemanager/cache_manager_test.go, pkg/yurttunnel/handlerwrapper/tracerequest/tracereq.go, pkg/yurttunnel/server/serveraddr/addr.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
backport bugfix and features to branch release-v0.6, and will add tag v0.6.1
Fixes #
```release-note
```
=> 【backport】Release v0.6.1

pkg/yurtctl/cmd/yurtinit/init.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
use sealer v0.6.1 to render yaml with env variables instead of using the sed command.
Fixes #
```release-note
```
=> update sealer version to render yaml with env variables

pkg/yurthub/healthchecker/health_checker.go
> /kind bug
/kind feature
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Fixes #
```release-note
```
=> just log error

pkg/yurtctl/cmd/convert/convert.go, pkg/yurtctl/util/kubernetes/util.go
fix a typo in yurtctl util.go which uses 'lable' as 'label'.
```release-note
fix a typo in yurtctl util.go which uses 'lable' as 'label'.
```
=> fix: a typo in yurtctl util.go which uses 'lable' as 'label'

pkg/yurtctl/constants/yurt-app-manager-tmpl.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Fixes #
```shell
W0310 08:08:58.619318       1 warnings.go:67] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
W0310 08:08:58.619362       1 warnings.go:67] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
``` …
=> upgrade webhook version

docs/roadmap.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
add OpenYurt v0.7.0/v0.8.0 roadmap contents.
Fixes #
```release-note
```
=> [docs] revise roadmap for v0.7.0/v0.8.0

pkg/util/certmanager/certmanager.go, pkg/yurttunnel/trafficforward/iptables/iptables.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Add log for debug and clean code.
Fixes #
```release-note
```
=> just clean code

pkg/yurttunnel/trafficforward/dns/dns.go, pkg/yurttunnel/trafficforward/dns/handler.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Process dns sync err.
Fixes #
```release-note
```
=> dns sync err process

pkg/yurthub/network/iptables.go, pkg/yurthub/network/network.go
/kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Process return error.
Fixes #
```release-note
```
=> iptables error process

README.md, README.zh.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
update slack link because of current link expired
Fixes #744 
```release-note
```
=> update slack link

.github/workflows/back-port.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind feature
add back port feature for github actions.
Fixes #
```release-note
```
=> add back port for github actions

pkg/yurttunnel/constants/constants.go, pkg/yurttunnel/kubernetes/kubernetes.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Fixes #
```release-note
```
=> use constants instead the string

README.md, README.zh.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
1. adjust community meeting from bi-weekly to weekly, and added meeting will be used for SIGs status synchronization.
2. update slack link
Fixes #
/assign @Fei-Guo @yixingjia @charleszheng44 @kadisi @DrmagicE @gnunu @qclc 
```release-note
```
=> adjust to weekly meeting and revise slack link

.github/workflows/release.yaml, Makefile
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Add a release workflow for updating images daily and updating images when a new tag is created.
Fixes #
/assign @Congrool 
```release-note
```
=> [enhancement] add release workfolow for daily release and tag event.

.github/workflows/back-port.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
add a comment(/backport) to backport pr to branch that specified by label. 
Fixes #
```release-note
```
=> [fix] revise backport workflow

config/setup/yurt-tunnel-server.yaml, config/yaml-template/yurt-tunnel-server.yaml
> /kind bug
The user of tunnel-proxy-client should be `tunnel-proxy-client` rather than `tunnel-server-proxy-client`.
Refer to: 
**The constants what yurtctl will use**
https://github.com/openyurtio/openyurt/blob/master/pkg/yurtadm/constants/yurt-tunnel-server-tmpl.go#L45-L58
**CN in the certificate of tunnel-proxy-client**
https://github.com/openyurtio/openyurt/blob/master/pkg/util/certmanager/certmanager.go#L136
Fixes #
```release-note
```
=> revise user in the rbac of tunnel-proxy-client

.github/workflows/release.yaml, Makefile
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
fix buildx arm64 error
Fixes #
```release-note
```
=> fix buildx arm64 error

hack/dockerfiles/Dockerfile.yurt-tunnel-server
/kind bug
Add conntrack-tools into yurt-tunnel-server dockerfile.
=> Fix: yurt-tunnel-server can not find conntrack executable

CHANGELOG.md, README.md, README.zh.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
revise readme and changeLog for OpenYurt v0.7.0
Fixes #
```release-note
```
=> revise docs for releasing OpenYurt v0.7.0

CHANGELOG.md, docs/roadmap.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
add ControlPlane/DataPlane/IoT SIGs roadmap contents for OpenYurt v0.8.0
Fixes #
```release-note
```
=> add roadmap for OpenYurt v0.8.0

pkg/yurtadm/util/edgenode/common.go
/kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
`yurtadm join` do not support paas parameters enableDummyIf and enableNodePool.
Fixes #
```release-note
```
=> check yurthub parameter exist when exec yurtadm join

hack/lib/common.sh, hack/make-rules/build.sh
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Fixes #
```release-note
```
=> cleanup openyurt shell

pkg/yurthub/filter/approver_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
optimize unit test for approver of yurthub
Fixes #
```release-note
```
=> fix approver unit test miss

Makefile
Signed-off-by: nunu <shaoqiang.chen@intel.com>
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
add proxy build-arg for docker build for those building from behind a proxy.
Fixes #
```release-note
NONE
```
=> add proxy to docker build-arg in case of proxy env

Makefile
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
fix small misses of makefile
Fixes #
```release-note
```
=> fix Makefile miss

go.mod, go.sum, pkg/yurthub/proxy/local/faketoken.go, pkg/yurthub/proxy/proxy.go
> /kind bug
Bound Service Account Token Volume is enabled in K8s 1.22. When edge node disconnected with K8s APIServer, kubelet can't get TokenRequest after edge node reboot. Then the token file in pod will be empty and In-cluster config will load failed. Because of that flannel or multus can't work correctly, and kubelet call cni-plugin(eg: multus) to configure other pod's network will be failed. In this case, edge node can't work after reboot.
If let yurthub return a fake token when edge node disconnects with K8s APIServer, each pod will have a fake token and In-cluster config will load succeed. So edge node can work correctly after reboot. If fake token's expiration time is 1 minute, kubelet will request token for each minute.When edge node reconnect with K8s APIServer, kubelet will get …
=> yurthub return fake token when edge node disconnected with K8s APIServer

.github/workflows/release.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Fixes #
```release-note
```
=> docker release ci only execute on openyurt repo

README.md, README.zh.md
Update Readme to the Requirements Reference
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Readme was referencing the wrong link for the documentation. Updated link to the correct one. 
Fixes #
```release-note
```
=> Docs: Update Readme to the Requirements Reference

.github/workflows/sync-charts.yaml, charts/openyurt/Chart.yaml, charts/openyurt/README.md, charts/openyurt/templates/_helpers.tpl, charts/openyurt/templates/yurt-controller-manager.yaml, charts/openyurt/templates/yurt-tunnel-agent.yaml, charts/openyurt/templates/yurt-tunnel-server.yaml, charts/openyurt/values.yaml, hack/lib/sync-charts.sh
> /kind bug
/kind feature
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Fixes #
```release-note
```
=> openyurt chart and sync to repo

.github/workflows/sync-charts.yaml, charts/openyurt/templates/yurt-tunnel-server.yaml
> /kind bug
/kind feature
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Fixes #
```release-note
```
=> fix sync chart secret

docs/tutorial/0001-flannel-keep-vtep-mac.patch, docs/tutorial/0002-ipam-keep-pod-ip.patch
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
restore code patch for flannel network solution.
Fixes #
```release-note
```
=> restore flannel network patch

.github/workflows/ci.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
add codecov token for uploading reports.
Fixes #
```release-note
```
=> add codecov token

.github/workflows/ci.yaml, README.md, README.zh.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
1. add codecov badge
2. remove build binaries step in workflow because e2e-tests step has already included this work.
Fixes #
```release-note
```
=> remove build binaries in workflow and add codecov badge

OWNERS
@luckymrwang 
@[openyurt](https://github.com/openyurtio)
@rambohe-ch 
- [support more than one podCIDR #20](https://github.com/openyurtio/raven-controller-manager/pull/20)
- [support calico #13](https://github.com/openyurtio/raven-controller-manager/pull/13)
- [raven# support more than one podCIDR #52](https://github.com/openyurtio/raven/pull/52)
- [Use camel case instead of snake case #747](https://github.com/openyurtio/openyurt/pull/747)
- [fix server tls config #404](https://github.com/openyurtio/openyurt/pull/404)
- [change yurthub's protocol from http to https #386](https://github.com/openyurtio/openyurt/pull/386)
- [change cache path from fixed to configurable parameter #349](https://github.com/openyurtio/openyurt/pull/349)
- [correct the comment line …
=> add luckymrwang as reviewer of OpenYurt

pkg/yurthub/filter/masterservice/handler_test.go
/kind bug
non-code files are included when codecov computes the coverage. Thus, it always fails when we add docs because the test coverage rate will decrease.
For example: [pr921](https://github.com/openyurtio/openyurt/pull/921/checks?check_run_id=7401365549)
Fixes #
```release-note
```
=> CI fix: codecov failure 

OWNERS
@zzguang 
openyurtio
@kadisi 
* PRs reviewed / authored:
#373
#422 
#645
#696
#749
#816
https://github.com/openyurtio/yurt-app-manager/pull/32
https://github.com/openyurtio/yurt-app-manager/pull/33
https://github.com/openyurtio/yurt-app-manager/pull/34
https://github.com/openyurtio/yurt-app-manager/pull/37
https://github.com/openyurtio/openyurt.io/pull/48
https://github.com/openyurtio/openyurt.io/pull/72
https://github.com/openyurtio/openyurt.io/pull/73
https://github.com/openyurtio/openyurt.io/pull/104
https://github.com/openyurtio/openyurt.io/pull/128
https://github.com/openyurtio/openyurt.io/pull/151
https://github.com/openyurtio/community/pull/40
https://github.com/openyurtio/yurt-app-manager/pull/38
https://github.com/openyurtio/yurt-app-manager/pull/51 …
=> Add zzguang as approver of OpenYurt

go.mod, pkg/controller/kubernetes/controller/testutil/test_utils.go, pkg/controller/kubernetes/util/node/node.go, pkg/controller/kubernetes/util/node/node_test.go, pkg/controller/kubernetes/util/taints/taints_test.go, pkg/controller/nodelifecycle/node_lifecycle_controller_test.go, pkg/controller/nodelifecycle/scheduler/taint_manager_test.go
Fixes #918 
```release-note
```
=> add unit tests for yurt-controller-manager

.github/PULL_REQUEST_TEMPLATE.md
=> remove redundant sig storage label in pr template

docs/roadmap.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
revise roadmap for OpenYurt v1.0 and v1.1
Fixes #
```release-note
```
=> revise roadmap

.github/workflows/ci.yaml, Makefile, hack/make-rules/verify_mod.sh
Refer to openyurtio/yurt-app-manager#94
Fixes #
```release-note
```
=> verify go mod in CI

.github/workflows/ci.yaml
Fixes #946 
```release-note
```
refer to https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsif
=> post result to codecov only in openyurt repo

config/setup/yurt-tunnel-dns.yaml
/kind bug
To make the settings consistent with manual setup docs. https://github.com/openyurtio/openyurt.io/pull/187
Fixes #
```release-note
```
=> Fix: fix tunnel dns settings 

hack/lib/download.sh
> /kind bug
/kind feature
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Download yurtadm by `curl -fsSl https://raw.githubusercontent.com/openyurtio/openyurt/master/hack/lib/download.sh | bash -s 1.4.6`
Fixes #
```release-note
```
=> download yurtadm shell

pkg/yurttunnel/trafficforward/dns/dns.go, pkg/yurttunnel/trafficforward/dns/dns_test.go, pkg/yurttunnel/trafficforward/dns/handler.go, pkg/yurttunnel/trafficforward/dns/handler_test.go, pkg/yurttunnel/trafficforward/iptables/iptables.go, pkg/yurttunnel/trafficforward/iptables/iptables_test.go, pkg/yurttunnel/util/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
add unit tests for yurt-tunnel component.
Fixes #916 
```release-note
```
=> add unit tests for yurt-tunnel

pkg/yurthub/network/iptables.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
in order to improve the compatibility with more operating system(like CentOS 8.5.2111), remove no track network setting in yurthub.
Fixes #943 #891 
```release-note
```
=> remove no track network setting for yurthub

charts/openyurt/Chart.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> increate chart version

.github/workflows/release.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead.
As the above notes, update ubuntu-18.04 to ubuntu-20.04 in release pipeline.
Fixes #
```release-note
```
=> update ubuntu-18.04 to ubuntu-20.04

.github/workflows/sync-charts.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> check ci repo

charts/openyurt/Chart.yaml, charts/openyurt/README.md, charts/openyurt/templates/yurthub-cfg.yaml
Complement missing openyurt charts. And bump chart version to 1.0.0
Fixes # https://github.com/openyurtio/openyurt/issues/987
```release-note
```
=> enhancement: complement openyurt helm charts

pkg/yurtadm/util/kubernetes/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> kubeadm join check download file exist

charts/openyurt/Chart.yaml, charts/openyurt/templates/yurt-tunnel-agent.yaml, charts/openyurt/templates/yurt-tunnel-server.yaml, charts/openyurt/values.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> extend chart parmeters

charts/openyurt/templates/yurthub-cfg.yaml, config/setup/yurthub-cfg.yaml, config/yaml-template/yurthub-cfg.yaml, pkg/yurtctl/constants/constants.go, pkg/yurthub/filter/approver.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
enable service topology filter for coredns in default setting
Fixes #
```release-note
```
=> enable service topology filter for coredns in default setting

pkg/yurthub/filter/servicetopology/handler.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> fix log level

CHANGELOG.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
revise changeLog for OpenYurt v1.0
Fixes #
```release-note
```
=> revise changelog for v1.0

pkg/yurtadm/cmd/yurtinit/init.go, pkg/yurtadm/cmd/yurtinit/options.go
update openyurt cluster image and yurtadm init.
all cluster image info is in : https://github.com/windydayc/openyurt-cluster-image
docs will be updated in openyurt.io.
=> update yurtadm init

charts/openyurt/Chart.yaml, charts/openyurt/values.yaml
=> charts use 1.0.0 image

pkg/yurtctl/cmd/yurttest/kindinit/init.go, pkg/yurtctl/cmd/yurttest/kindinit/init_test.go
/kind bug
Since we've released v0.7.1 and v1.0.0, we should update valid openyurt version of yurtctl test.
Fixes #
```release-note
```
=> update valid openyurt version of yurtctl test

pkg/yurthub/gc/gc.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> gc error process

pkg/controller/daemonpodupdater/daemon_pod_updater_controller.go, pkg/controller/daemonpodupdater/daemon_pod_updater_controller_test.go
Signed-off-by: hxcGit <houxc_mail@163.com>
Currently, the default `maxUnavailable` in `daemonPodUpdater controller` is `1`. Set this to `10%`.
This value will be set as default in three cases:
- Not set
- Set to `0`
- Set to `0%`
Note: when the length of nodeToDaemonPods is less than or equal to 10, the default value is equal to 1.
=> set default maxUnavailable to 10%

docs/roadmap.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
update SIG controlplane's roadmap for OpenYurt v1.1 and v1.2
Fixes #
```release-note
```
=> update roadmap for SIG controlplane

CHANGELOG.md, README.md, README.zh.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
revise changeLog and readme docs for OpenYurt v1.1.0 release.
Fixes #
```release-note
```
=> add release note and changeLog for OpenYurt v1.1.0

CHANGELOG.md, charts/openyurt/Chart.yaml, charts/openyurt/values.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
update helm charts for OpenYurt v1.1.0
Fixes #
```release-note
```
=> update helm charts for OpenYurt v1.1.0

charts/openyurt/Chart.yaml, charts/openyurt/templates/yurthub-cfg.yaml, charts/openyurt/values.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> expose helm values for yurthub cacheagents

pkg/util/certmanager/pki_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> add_pki_test.go

pkg/util/certmanager/store/filestore_wrapper_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> add_filestore_wrapper_test.go

pkg/util/certmanager/factory/factory_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> add_factory_test.go

charts/openyurt/templates/yurthub-cfg.yaml
add `quote`  fix error(when use helm3,error validating data: unknown object type "nil" in ConfigMap.data.cache_agents)
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> fix: unknown object type "nil" in yurthub-cfg.yaml

pkg/util/strings/util_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> add_util_test.go

pkg/util/iptables/testing/fake_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> add_fake_test.go

pkg/yurtadm/cmd/join/join_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> add_join_test.go

pkg/yurttunnel/handlerwrapper/wraphandler/wraphandler_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> add_wraphandler_test.go

pkg/controller/poolcoordinator/cert/certificate.go
Fix miss spelling of ".key" to ".pub"
=> Fix: pub key bug

charts/openyurt/templates/pool-coordinator.yaml
fix https://github.com/openyurtio/openyurt/issues/1116
=> fix: issue 1116

cmd/yurthub/app/config/config.go
Add back kubeConfig init logic  to fix npe.
=> Fix: add back kubeConfig init logic to fix npe

go.mod, go.sum, pkg/profile/profile_test.go, pkg/yurthub/certificate/hubself/cert_mgr_test.go, pkg/yurthub/storage/disk/storage.go, pkg/yurthub/storage/disk/storage_test.go, pkg/yurthub/storage/etcd/etcd_suite_test.go, pkg/yurthub/storage/etcd/key_test.go, pkg/yurthub/storage/etcd/keycache.go, pkg/yurthub/storage/etcd/keycache_test.go, pkg/yurthub/storage/etcd/mock/kv.go, pkg/yurthub/storage/etcd/storage.go, pkg/yurthub/storage/etcd/storage_test.go
/kind bug
BugFix:
1. initialize etcdClient before using componentKeyCache
2. `Create` function of disk storage cannot create dir for rootKey
All unit test errors are expected to be solved in this pr.
Fixes #
```release-note
```
=> Bugfix of pool-coordinator and enable unit test to pass

pkg/yurthub/poolcoordinator/certmanager/certmanager.go, pkg/yurthub/poolcoordinator/certmanager/certmanager_test.go
unit test
Add unit tests for poolcoordinator certmanager.
Fixes #
```release-note
```
=> test: add unit test for poolcoordinator cert manager

Makefile
Signed-off-by: fsl <1171313930@qq.com>
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> fix: add common builder

README.md, README.zh.md
Signed-off-by: fsl <1171313930@qq.com>
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> fix: update slack link

go.sum, pkg/yurtadm/cmd/cmd.go, pkg/yurtadm/cmd/docs/docs.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> generate yurtadm docs

charts/openyurt/templates/pool-coordinator.yaml, charts/openyurt/templates/yurt-controller-manager.yaml, cmd/yurt-controller-manager/app/controllermanager.go, cmd/yurt-controller-manager/app/core.go, pkg/controller/certificates/csrapprover.go, pkg/controller/poolcoordinator/cert/certificate.go, pkg/controller/poolcoordinator/cert/certificate_test.go, pkg/controller/poolcoordinator/cert/poolcoordinator_cert_manager.go, pkg/controller/poolcoordinator/cert/poolcoordinator_cert_manager_test.go, pkg/controller/poolcoordinator/cert/secret.go, pkg/controller/poolcoordinator/cert/secret_test.go, pkg/controller/poolcoordinator/cert/util.go, pkg/controller/poolcoordinator/cert/util_test.go, pkg/util/ip/ip.go, pkg/util/ip/ip_test.go, pkg/util/kubeconfig/kubeconfig.go, pkg/util/kubeconfig/kubeconfig_test.go
> /kind bug
/kind feature
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> add poolcoordinator certmanager controller 

charts/openyurt/README.md, charts/openyurt/templates/pool-coordinator.yaml, charts/openyurt/values.yaml
/kind feature
add pool-coordinator chart.
use yurtappdaemon to control the deploy of pool-coordinator.
the secrets should be created first before the pool-coordinator chart installed.
Fixes #
```release-note
add pool-coordinator chart. 
```
=> feat: add pool-coordinator charts

pkg/yurthub/poolcoordinator/coordinator.go, pkg/yurthub/storage/disk/key.go, pkg/yurthub/storage/disk/key_test.go
/kind bug
Translate disk storage key to etcd storage key before using etcdstorage to update the pool cache. Otherwise, ErrUnrecognizedKey will occur.
Fixes #
```release-note
```
=> bugfix: cannot upload local cache

charts/openyurt/templates/yurthub-cfg.yaml
/kind bug
Yurthub needs to list/watch endpoints and endpointslices from cloud APIServer which needs authorization of listing/watching these resources.
Fixes #
```release-note
```
=> rbac: add endpoints/endpointslices list/watch to yurt-hub clusterrole

pkg/yurthub/proxy/local/local.go, pkg/yurthub/proxy/pool/pool.go, pkg/yurthub/proxy/remote/loadbalancer.go
/kind bug
These log will be confused when debuging. The cloud cluster may be healthy when using pool proxy, and the local pool-coordinator may be unhealthy when using lb proxy.
Fixes #
```release-note
```
=> improve proxy log message

CHANGELOG.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
revise changeLog for v1.2
Fixes #
```release-note
```
=> revise changeLog for v1.2

docs/roadmap.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
add 2023 roadmap for SIG controlplane
Fixes #
```release-note
```
=> add 2023 roadmap for SIG controlplane

charts/openyurt/values.yaml
/kind bug
There seems no such image repo called `docker.io/google_containers/kube-apiserver` and `docker.io/google_containers/etcd`. Replace them with `k8s.gcr.io/kube-apiserver` and `k8s.gcr.io/etcd` respectively.
Fixes #
```release-note
```
=> fix unavailable coordinator image

.github/dependabot.yml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
add ignore package for dependabot
Fixes #
```release-note
```
=> add ignore package for dependabot

.github/workflows/ci.yaml
Now OpenYurt is using golang 1.17(#1192) and golang-ci-lint 1.40 (#1224), so align versions of these tools in CI workflow.
Fixes #
```release-note
```
=> align versions of CI tools

charts/openyurt/values.yaml
/kind bug
This PR migrate from `k8s.gcr.io` to `registry.k8s.io`
reference: https://github.com/kubernetes/k8s.io/issues/4780
```release-note
NONE
```
=> fix: update k8s registry url

RELEASE-PROCESS.md, RELEASES.md, SECURITY.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
add security and release docs
Fixes #
```release-note
```
=> add security and release docs

hack/make-rules/add_controller.sh
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> add a blank line to follow the rule of golangci-lint

cmd/yurt-node-servant/node-servant.go, pkg/node-servant/constant.go, pkg/node-servant/job.go, pkg/yurtadm/constants/constants.go, pkg/yurtadm/util/edgenode/edgenode.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
clean up info of yurtctl and template of kcm nodelifecycle controller
Fixes #
```release-note
```
=> clean up yurtctl and template of kcm controller

test/e2e/autonomy/autonomy.go
/kind bug
as mentioned in  #1109, we can only delete the nat rules related to yurt-e2e-test-nginx for kube-proxy test. 
Fixes #1109
/assign @Congrool 
In fact, the original `iptables -F` command only cleared the default rules on the filter table and did not affect the rules of the nat table.
None
=> Bugfix: delete specific iptables while testing kube-proxy

charts/openyurt/Chart.yaml, charts/openyurt/templates/pool-coordinator.yaml, charts/openyurt/templates/yurt-controller-manager.yaml, charts/openyurt/templates/yurt-manager.yaml, charts/openyurt/values.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> Upgrade openyurt to v1.2.1

.golangci.yaml, cmd/yurt-tunnel-server/app/start.go, pkg/yurthub/certificate/token/token.go, pkg/yurthub/network/network.go, pkg/yurthub/poolcoordinator/resources/resources.go, pkg/yurthub/proxy/util/util.go, pkg/yurthub/transport/transport.go, pkg/yurttunnel/server/interceptor_test.go, pkg/yurttunnel/trafficforward/dns/util_test.go, pkg/yurttunnel/trafficforward/iptables/iptables.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
I add static check to golangci-lint and fixed some of the following problems
Fixes #
```release-note
```
=> Chore: add static check to golangci-lint

.github/workflows/trivy-scan.yml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> Add trivy scan

SECURITY.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
revise security setting with trivy info.
Fixes #
```release-note
```
=> add trivy info

README.md, README.zh.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> Add OpenSSF Scorecard for README.md

.github/workflows/back-port.yaml, .github/workflows/release.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> ci: bump ubuntu from 20.04 to 22.04

.github/workflows/ci.yaml, Makefile
/kind feature
use golangci-lint@v1.47.3 and add version check
Fixes #1297 
/assign @kadisi 
```release-note
```
=> feat: optimize make lint

.github/workflows/sonarcloud.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> Add Scorecard schedule

pkg/webhook/util/health/checker.go, pkg/webhook/util/writer/atomic/atomic_writer.go, pkg/webhook/util/writer/fs.go, pkg/yurthub/certificate/token/token_test.go, pkg/yurthub/proxy/proxy.go, pkg/yurthub/server/nonresource_test.go, pkg/yurthub/util/connrotation_test.go, pkg/yurthub/util/util_test.go
/kind bug
Fixes #1308 
@rambohe-ch 
```release-note
```
=> cleanup: io/ioutil

.github/workflows/trivy-scan.yml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
because yurt-tunnel and yurt-controller-manager are deprecated, so remove them in trivy to improve efficiency.
Fixes #
```release-note
```
=> yurt-tunnel and yurt-controller-manager component are deprecated

.github/workflows/trivy-scan.yml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> Fix branch not found

.github/workflows/ci.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> Fix:  delete more DOCKER_BUILDX_VERSION env

charts/openyurt/templates/yurt-manager.yaml, charts/openyurt/values.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
1. native K8s components have occupied ports: 10250~10259
2. OpenYurt YurtHub component has occupied ports: 10260~10269
3. OpenYurt Yurt-Manager component has occupied ports: 10270~10279 
Fixes #
```release-note
```
=> adjust ports for yurt-manager component to 10270~10279

hack/dockerfiles/build/Dockerfile.yurthub, hack/dockerfiles/release/Dockerfile.yurthub, hack/iptables-wrapper-installer.sh
/kind feature
Since CentOS8, nftables is used instead of iptables by default.
Fixes #1135
```release-note
NONE
```
=> feat: yurthub automatically recognize nftables or iptables (#1135)

hack/make-rules/image_build.sh
/kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
when running build in a setup with proxy, we need to add proxy envs.
Fixes #
```release-note
```
=> add system proxy for docker run

pkg/controller/csrapprover/csrapprover_controller.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Improve csr approver controller by using injector to prepare kube client and mapper.
Fixes #
```release-note
```
=> improve csr approver controller with injector

charts/openyurt/templates/yurt-controller-manager.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind bug
When i use daemonset auto updating, yurt-controller-manager have error, update failed.
```
I0328 09:04:36.175128   56436 daemon_pod_updater_controller.go:468] Auto update pod kube-keepalived-vip-ynp-g584f/kube-keepalived-vip-ynp-g584f-ppgbp
I0328 09:04:36.175177   56436 daemon_pod_updater_controller.go:240] error syncing event cattle-keepalived/kube-keepalived-vip-ynp-g584f: unable to delete pods: pods "kube-keepalived-vip-ynp-g584f-ppgbp" is forbidden: User …
```
=> 【FIX】fix yurt-controller-manager clusterrole missing pod delete

pkg/controller/nodepool/nodepool_controller.go
/kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> fix nodepool kind

charts/openyurt/templates/yurt-manager.yaml
/kind feature
Fixes #1350 
@kadisi 
```release-note
```
=> feat: change yurt-manager ClusterRoleBinding name

pkg/controller/poolcoordinator/cert/util.go, pkg/webhook/gateway/v1alpha1/gateway_handler.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
1. remove dummy logs of pool-coordinator cert, we only need to print logs after pool-coordinator service ready
2. fix path of gateway wehbooks
Fixes #
```release-note
```
=> fix misses

charts/openyurt/templates/yurt-manager-auto-generated.yaml, cmd/yurt-manager/app/manager.go, pkg/controller/nodepool/nodepool_enqueue_handlers.go, pkg/controller/poolcoordinator/cert/secret.go, pkg/webhook/util/configuration/configuration.go, pkg/webhook/util/controller/webhook_controller.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
1. move controllers setup after manager creation
2. don't print some dummy logs in a interval
3. fix nodepool controller corner case
4. fix gateway webhook mutate/validate path
5. fix some typo errors
Fixes #
```release-note
```
=> fix some misses in yurt-manager

charts/openyurt/templates/yurt-manager-auto-generated.yaml, cmd/yurt-controller-manager/app/controllermanager.go, cmd/yurt-controller-manager/app/core.go, pkg/controller/add_daemonpodupdater.go, pkg/controller/daemonpodupdater/daemon_pod_updater_controller.go, pkg/controller/daemonpodupdater/daemon_pod_updater_controller_test.go, pkg/controller/daemonpodupdater/util.go, pkg/controller/daemonpodupdater/util_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Related #1067 
```release-note
```
=> migrate daemonpod controller to yurt-manager

cmd/yurt-manager/app/options/generic.go, pkg/features/features.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
Fixes (https://github.com/openyurtio/raven/issues/95)
```release-note
```
=> feat: add feature gate

pkg/controller/servicetopology/endpointslice/endpointslice_controller.go, pkg/controller/servicetopology/endpointslice/endpointslice_enqueue_handlers.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> fix: modify the naming format

MAINTAINERS.md
@luckymrwang 
@[openyurt](https://github.com/openyurtio)
@rambohe-ch 
- https://github.com/openyurtio/raven/pull/106
- https://github.com/openyurtio/openyurt-helm/pull/13
- https://github.com/openyurtio/raven/pull/99
- https://github.com/openyurtio/raven/pull/97
- https://github.com/openyurtio/raven/pull/96
- https://github.com/openyurtio/raven/pull/93
- https://github.com/openyurtio/raven/pull/91
- https://github.com/openyurtio/openyurt/pull/1373
- https://github.com/openyurtio/openyurt/pull/1305
- https://github.com/openyurtio/openyurt.io/pull/97
- https://github.com/openyurtio/openyurt.io/pull/132
- https://github.com/openyurtio/openyurt.io/pull/133
- https://github.com/openyurtio/openyurt.io/pull/137
- …
=> add luckymrwang as maintainer of OpenYurt

pkg/webhook/staticpod/v1alpha1/staticpod_validation.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Use K8s internal util function to facilitate validate `PodTemplateSpec`.
Fixes #
```release-note
```
=> add validation for StaticPod PodTemplateSpec

charts/openyurt/templates/yurthub-staticpod.yaml, charts/openyurt/values.yaml, pkg/controller/staticpod/staticpod_controller.go, pkg/yurtadm/cmd/join/join.go, pkg/yurtadm/cmd/join/join_test.go, pkg/yurtadm/cmd/join/joindata/data.go, pkg/yurtadm/constants/constants.go, pkg/yurtadm/util/kubernetes/kubernetes.go, pkg/yurtadm/util/yurthub/yurthub.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #1080 
```release-note
```
=> feat: install yurthub component on edge nodes depending on StaticPod cr resource

pkg/node-servant/static-pod-upgrade/util/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Review engineering code to make better engineering contributions.
Fixes #
none
none
```release-note
```
none
=> misspelling about log info

charts/openyurt/templates/yurt-manager.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> expose yurtmanager metrics port for prometheus use

hack/make-rules/kustomize_to_chart.sh
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
support mac os
Fixes #
```release-note
```
=> support mac os

charts/openyurt/templates/yurthub-staticpod.yaml, pkg/yurtadm/cmd/join/join.go, pkg/yurtadm/cmd/join/join_test.go, pkg/yurtadm/cmd/join/joindata/data.go, pkg/yurtadm/constants/constants.go, pkg/yurthub/certificate/token/token.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
1. improve yurthub staticpod yaml
2. remove yurthub image parameter in yurtadm join command, because yurthub image should be defined in yurthub static pod.
Fixes #
```release-note
```
=> improve yurtadm join command

charts/openyurt/values.yaml, cmd/yurt-manager/app/options/generic.go, pkg/webhook/util/util.go, test/e2e/cmd/init/constants/constants.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
1. improve yurt-manager port, adjust webhook port from 10270 to 10273, because pool coordinator has already used port 10270.
2. change node affinity for yurt-manager in order to make yurt-manager work on master node.
Fixes #
```release-note
```
=> improve yurt-manager ports and affinity

pkg/controller/servicetopology/endpointslice/endpointslice_controller.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
If v1.EndpointSlice Kind is not supported in K8s, the following error message will be printed in yurt-manager component:
```
E0508 08:59:34.674508       1 discovery.go:78] Failed to find resources in group version discovery.k8s.io/v1: the server could not find the requested resource, waiting time 15.655818364s
```
and this error message will make user confused, and we need to user `InjectMapper` to verify whether specified resource is supported or not. so i improved `service …
=> improve service topology by using inject funcs

pkg/apis/addtoscheme_raven_v1alpha1.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind bug
Fixes #1434
/assign @njucjc 
```release-note
```
=> fix: raven-controller-manager supports calico

charts/yurt-manager/values.yaml, charts/yurthub/templates/yurthub-staticpod.yaml, charts/yurthub/values.yaml, cmd/yurt-manager/app/manager.go, pkg/node-servant/components/yurthub.go, pkg/profile/profile.go, pkg/yurtadm/cmd/join/join.go, pkg/yurtadm/cmd/join/join_test.go, pkg/yurtadm/cmd/join/joindata/data.go, pkg/yurtadm/constants/constants.go, pkg/yurtadm/util/yurthub/yurthub.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
1. In OpenYurt v1.2, `yurtadm join` command uses hard-code yurthub manifest to install yurthub static pod.
2. And in OpenYurt v1.3, `yurtadm join` command  will get `static-pod-cm-kube-system-yurthub` configmap from kube-apiserver and install yurthub static pod. and `static-pod-cm-kube-system-yurthub` configmap is generated and managed by StaticPod controller and yurthub StaticPod CR resource.
and in this pull request, we will keep the hard-code yurthub manifest for `yurtadm …
=> improve yurtadm join for keeping consistency with v1.2

charts/yurt-manager/crds/apps.openyurt.io_staticpods.yaml, pkg/apis/apps/v1alpha1/default.go, pkg/apis/apps/v1alpha1/staticpod_types.go, pkg/controller/staticpod/staticpod_controller.go, pkg/controller/staticpod/staticpod_controller_test.go, pkg/controller/staticpod/upgradeinfo/upgrade_info.go, pkg/controller/staticpod/util/util.go, pkg/webhook/staticpod/v1alpha1/staticpod_validation.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #1450 
```release-note
```
=> rename auto to AdvancedRollingUpdate

CHANGELOG.md, charts/yurthub/templates/yurthub-staticpod.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind bug
1. modify `staticPodManifest` field from `yurt-hub` to `yurthub`.
2. update changeLog with `AdvancedRollingUpdate`
Fixes #1454 
```release-note
```
=> fix yurthub static pod upgrade error

pkg/yurthub/otaupdate/upgrader/static_pod.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> fix ota upgrade dir non-existent

CHANGELOG.md
This PR fixes syntax errors to make  readers read better.
Fixes syntax errors.
NONE
```release-note
```
=> fix syntax errors

charts/pool-coordinator/Chart.yaml, charts/yurt-manager/Chart.yaml, charts/yurthub/Chart.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> upgrade chart version

pkg/util/util.go, pkg/yurthub/otaupdate/util/util.go, pkg/yurthub/proxy/local/faketoken.go, pkg/yurthub/proxy/local/local.go, pkg/yurthub/proxy/pool/pool.go, pkg/yurthub/proxy/remote/loadbalancer.go, pkg/yurthub/server/certificate.go, pkg/yurthub/server/nonresource.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Code optimization:
replacing commonly used HTTP strings with enumerations.
Fixes #
```release-note
```
=> optimization: replacing commonly used HTTP strings with enumerations.

README.md
=> Fix the grammatical errors in README.md

pkg/webhook/builder/webhook.go
Error strings should not be capitalized (unless beginning with proper nouns or acronyms) or end with punctuation, since they are usually printed following other context.
NONE
```release-note
```
=> fix format err in pkg/webhook/builder/webhook.go

pkg/controller/yurtstaticset/upgradeinfo/upgrade_info.go, pkg/controller/yurtstaticset/upgradeinfo/upgrade_info_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
When user want to upgrade static pod by yurtstaticset, if the environment already have static pod, and the yurtstaticset.spec.template is also not change when first time make, the controller will still make some worker pod to upgrade static pod even if the pod is not change. 
So we need to improve the upgrade calculate way, except hash.
Fixes #
```release-note
```
=> improve yurtstaticset upgrade for existing static pod

cmd/yurthub/app/start.go, pkg/yurthub/util/dumpstack.go, pkg/yurthub/util/dumpstack_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #1475
```release-note
```
=> feat: support SIGUSR1 signal for yurthub

CHANGELOG.md, README.md, README.zh.md, charts/README.md, charts/pool-coordinator/Chart.yaml, charts/pool-coordinator/templates/_helpers.tpl, charts/pool-coordinator/templates/pool-coordinator.yaml, charts/pool-coordinator/values.yaml, charts/yurthub/templates/yurthub-cfg.yaml, docs/proposals/20220307-nodepool-governance-capability.md, docs/proposals/20220414-multiplexing-cloud-edge-traffic.md, docs/proposals/20220627-yurthub-cache-refactoring.md, docs/roadmap.md, hack/lib/sync-charts.sh
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
Unify the naming rules of each component in openyurtio/openyurt repo, it is more understandable for end users.
Fixes #1482 
```release-note
```
=> rename pool-coordinator to yurt-coordinator for other

test/e2e/yurt/yurtstaticset.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #1477 
```release-note
```
=> feat: add e2e test case for yurtstaticset controller

pkg/controller/yurtcoordinator/podbinding/podbinding_controller.go
/kind bug
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
1. check whether tolerationSeconds is nil
2. handle some unhandled errors(configureTolerationForPod)
3. avoid conflicts of variable names and imported packages
Fixes #
```release-note
```
=> check nil in podbinding_controller.go and handle some errors

pkg/controller/servicetopology/adapter/adapter.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
delete unused functions.
Fixes #
```release-note
```
=> delete unused functions

pkg/yurtadm/cmd/cmd.go, pkg/yurtadm/cmd/join/join.go, pkg/yurtadm/cmd/join/join_test.go, pkg/yurtadm/cmd/join/joindata/data.go, pkg/yurtadm/cmd/join/phases/prepare.go, pkg/yurtadm/cmd/staticpods/install/install.go, pkg/yurtadm/cmd/staticpods/staticpods.go, pkg/yurtadm/cmd/staticpods/uninstall/uninstall.go, pkg/yurtadm/constants/constants.go, pkg/yurtadm/util/edgenode/edgenode.go, pkg/yurtadm/util/edgenode/edgenode_test.go, pkg/yurtadm/util/kubernetes/kubernetes.go, pkg/yurtadm/util/yurthub/yurthub.go, pkg/yurtadm/util/yurthub/yurthub_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
It is very hard for user to install/uninstall static pods on node manually, and we should install/uninstall static pods based on YurtStaticSet resource. so we need add the above features.
Fixes #1472 
```release-note
```
=> add yurtadm to install/uninstall staticpod

charts/yurt-coordinator/Chart.yaml, charts/yurt-manager/Chart.yaml, charts/yurt-manager/values.yaml, charts/yurthub/Chart.yaml, charts/yurthub/values.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
update chart version for release v1.3.2
Fixes #
```release-note
```
=> update chart version from v1.3.0 to v1.3.2

pkg/yurthub/filter/discardcloudservice/filter.go, pkg/yurthub/filter/discardcloudservice/filter_test.go, pkg/yurthub/filter/inclusterconfig/filter.go, pkg/yurthub/filter/inclusterconfig/filter_test.go, pkg/yurthub/filter/initializer/initializer.go, pkg/yurthub/filter/initializer/initializer_test.go, pkg/yurthub/filter/masterservice/filter.go, pkg/yurthub/filter/masterservice/filter_test.go, pkg/yurthub/filter/nodeportisolation/filter.go, pkg/yurthub/filter/nodeportisolation/filter_test.go, pkg/yurthub/filter/servicetopology/filter.go, pkg/yurthub/filter/servicetopology/filter_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
add unit test cases for yurthub filters.
Fixes #
```release-note
```
=> add unit test cases for yurthub filters

.github/workflows/registry.yaml, .github/workflows/release-assets.yaml, .goreleaser.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
add a workflow for release yurtadm binaries as assets when a version is released.
Fixes #1085 
```release-note
```
=> feat: add yurtadm binaries release workflow

pkg/controller/platformadmin/config/EdgeXConfig/config-nosecty.json, pkg/controller/platformadmin/config/EdgeXConfig/config.json, pkg/controller/platformadmin/config/EdgeXConfig/manifest.yaml
/kind feature
/sig iot
support edgex minnesota through auto-collector
Fixes #1581 
I'm just a porter representing the auto-collector🤣
=> feat: support edgex minnesota through auto-collector

charts/yurt-coordinator/Chart.yaml, charts/yurt-manager/Chart.yaml, charts/yurt-manager/values.yaml, charts/yurthub/Chart.yaml, charts/yurthub/values.yaml
update chart version for release v1.3.2
Fixes #
```release-note
```
=> update chart version from v1.3.2 to v1.3.4

pkg/yurtadm/util/kubernetes/util.go
backport of #1576 for release-v1.0
/kind bug
=> change access permission to default in general.

.github/workflows/ci.yaml, .github/workflows/registry.yaml, .github/workflows/release-assets.yaml, .goreleaser.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
backport #1577 to branch release-v1.2
Fixes #
```release-note
```
=> backport: feat: add yurtadm binaries release workflow

pkg/webhook/yurtappdaemon/v1alpha1/yurtappdaemon_validation.go
=> replace string var by const

pkg/yurthub/filter/constant.go, pkg/yurthub/filter/hostnetworkpropagation/filter.go, pkg/yurthub/filter/hostnetworkpropagation/filter_test.go, pkg/yurthub/filter/manager/manager.go, pkg/yurthub/filter/manager/manager_test.go, pkg/yurthub/filter/nodeportisolation/filter.go, pkg/yurthub/filter/nodeportisolation/filter_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
Add a new filter named `hostnetworkpropagation` for set pod.spec.HostNetwork field when nodepool.spec.HostNetwork is true. so can make sure all pods in HostNetwork nodepool can work in HostNetwork mode.
Fixes #1621 
```release-note
```
=> feat: add nodepool hostnetwork propagation filter

cmd/yurthub/app/options/options.go, pkg/yurthub/certificate/interfaces.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind bug
join token and bootstrap file are only checked when token bootstrap mode is selected.
Fixes #
```release-note
```
=> fix verify join token and bootstrapfile only in token bootstrap mode

pkg/node-servant/components/yurthub.go, pkg/node-servant/constant.go, test/e2e/cmd/init/constants/constants.go, test/e2e/cmd/init/converter.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind bug
fix node-servant convert not use yss template to deploy yurthub
Fixes #
```release-note
```
=> fix node-servant convert not use yss template to deploy yurthub

pkg/yurtmanager/controller/daemonpodupdater/daemon_pod_updater_controller.go, pkg/yurtmanager/controller/daemonpodupdater/util.go, pkg/yurtmanager/controller/daemonpodupdater/util_test.go, pkg/yurtmanager/controller/util/node/controller_utils.go, pkg/yurtmanager/controller/util/pod/pod_util.go, pkg/yurtmanager/controller/util/pod/pod_util_test.go, pkg/yurtmanager/controller/yurtstaticset/upgradeinfo/upgrade_info.go, pkg/yurtmanager/controller/yurtstaticset/upgradeinfo/upgrade_info_test.go, pkg/yurtmanager/controller/yurtstaticset/util/util.go, pkg/yurtmanager/controller/yurtstaticset/yurtstaticset_controller.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
modify the logic for judging static pods and combine the utils for pod and node
Fixes #
```release-note
```
=> modify the logic for judging static pods and combine the utils for pod and node

charts/yurt-manager/values.yaml
/kind feature
Fixes #1721 
```release-note
```
=> feat: use node-role.kubernetes.io/control-plane for yurt-manager node selection

charts/yurt-manager/templates/yurt-manager.yaml, cmd/yurt-manager/app/manager.go, test/e2e/cmd/init/constants/constants.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Add liveness and readiness probe for yurt-manager component.
Fixes #
```release-note
```
=> add ping healthz and readyz for yurt-manager component

charts/yurt-coordinator/Chart.yaml, charts/yurt-manager/Chart.yaml, charts/yurthub/Chart.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
upgrade helm chart version to v1.4.0
Fixes #
```release-note
```
=> upgrade helm charts version to v1.4.0

pkg/yurtmanager/controller/raven/dns/dns_controller.go
> /kind bug
This may cause panic
Fixes #
```release-note
```
=> fix dns controller get raven dns configmap

charts/yurt-manager/Chart.yaml, charts/yurt-manager/templates/yurt-manager.yaml, charts/yurt-manager/values.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
For use private image registry case.
Fixes #
```release-note
```
=> add imagepullsecrets for chart

MAINTAINERS.md, OWNERS, cmd/yurtadm/OWNERS, pkg/yurtadm/OWNERS, pkg/yurtmanager/controller/raven/OWNERS, pkg/yurtmanager/webhook/gateway/OWNERS
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
According to file: https://github.com/openyurtio/community/blob/main/OWNERS.md, update maintainers and owners of OpenYurt.
Fixes #
```release-note
```
=> update maintainers and owners of OpenYurt

CHANGELOG.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
add some archive info in changeLog
Fixes #
```release-note
```
=> add archive info in changelog

cmd/yurt-manager/app/manager.go, cmd/yurt-manager/app/options/gatewaycontroller.go, cmd/yurt-manager/app/options/nodepoolcontroller.go, cmd/yurt-manager/app/options/platformadmincontroller.go, cmd/yurt-manager/app/options/yurtappdaemoncontroller.go, cmd/yurt-manager/app/options/yurtappoverridercontroller.go, cmd/yurt-manager/app/options/yurtappsetcontroller.go, cmd/yurt-manager/app/options/yurtstaticsetcontroller.go
=> Comments alse need camelCase format

charts/yurt-manager/crds/raven.openyurt.io_gateways.yaml, pkg/apis/raven/v1alpha1/gateway_conversion.go, pkg/apis/raven/v1alpha1/gateway_types.go
/kind feature
Fixes #
```release-note
```
=> feat: remove gateway v1alpha1 nat fields

hack/lib/common.sh, hack/lib/init.sh, pkg/apis/apps/well_known_labels_annotations.go, pkg/projectinfo/projectinfo.go, pkg/yurtadm/cmd/join/join.go, pkg/yurthub/filter/hostnetworkpropagation/filter.go, pkg/yurthub/filter/hostnetworkpropagation/filter_test.go, pkg/yurthub/filter/nodeportisolation/filter.go, pkg/yurthub/filter/nodeportisolation/filter_test.go, pkg/yurthub/filter/servicetopology/filter.go, pkg/yurthub/filter/servicetopology/filter_test.go, pkg/yurtmanager/controller/nodepool/nodepool_controller.go, pkg/yurtmanager/controller/nodepool/nodepool_controller_test.go, pkg/yurtmanager/controller/nodepool/nodepool_enqueue_handlers.go, pkg/yurtmanager/controller/nodepool/nodepool_enqueue_handlers_test.go, pkg/yurtmanager/controller/platformadmin/platformadmin_controller.go, pkg/yurtmanager/controller/yurtappdaemon/workloadcontroller/util.go, pkg/yurtmanager/controller/yurtappdaemon/workloadcontroller/util_test.go, pkg/yurtmanager/webhook/node/v1/node_default.go, pkg/yurtmanager/webhook/node/v1/node_default_test.go, pkg/yurtmanager/webhook/node/v1/node_validation.go, pkg/yurtmanager/webhook/node/v1/node_validation_test.go, pkg/yurtmanager/webhook/nodepool/v1beta1/nodepool_validation.go, pkg/yurtmanager/webhook/nodepool/v1beta1/nodepool_validation_test.go, test/e2e/util/nodepool.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
1. remove `nodepool.openyurt.io/type` label of node because it is unused
2. improve `apps.openyurt.io/nodepool` label of node, and user can define this label when compile openyurt components. this means users can define this label as their interest. 
Fixes #
```release-note
```
=> improve node labels that are managed by nodepool

config/setup/raven-proxy-dns.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> fix dns host using configmap name

test/e2e/yurt/yurtappoverrider.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> fix: yurappoverrider e2e test

Makefile
/kind bug
/sig iot
Fixed an issue where the yurt-iot-dock of multiple architectures was not pushed when shipping a new version.
=> fix(yurt-iot-dock): multi-architecture yurt-iot-dock was not pushed

charts/yurt-manager/Chart.yaml, charts/yurt-manager/values.yaml, charts/yurthub/Chart.yaml, charts/yurthub/values.yaml
/kind bug
Fixes #1846 
```release-note
```
=> upgrade helm charts image version to v1.4.0

pkg/yurtmanager/controller/platformadmin/platformadmin_controller.go, test/e2e/cmd/init/init.go, test/e2e/e2e_test.go, test/e2e/util/nodepool.go, test/e2e/util/util.go, test/e2e/yurt/iot.go
/sig iot
Fixes: #1545 
Added e2e test for iot systems.
=> test: added e2e test for iot systems

pkg/yurthub/filter/filter.go
/kind feature
BOOKMARK and ERROR response should be skipped in yurthub filter.
Fixes #1868
=> feat: bookmark and error response should be skipped in yurthub filter (#1868)

pkg/yurtiotdock/controllers/device_controller.go
/kind bug
yurt-iot-dock will crash when device controller reconciles the device properties
Fixes #1872
=> Fix: yurt-iot-dock crashes when setting the device properties (#1872)

pkg/apis/apps/v1alpha1/default.go, pkg/node-servant/static-pod-upgrade/upgrade.go, pkg/yurtmanager/controller/yurtstaticset/util/util.go, pkg/yurtmanager/controller/yurtstaticset/yurtstaticset_controller.go, pkg/yurtmanager/webhook/yurtstaticset/v1alpha1/yurtstaticset_validation.go
Check two new upgrade models AdvancedRollingUpdate and OTA using case-insensitive string judgment instead of using "==".
By introducing `strings.EqualFold(stringA, stringB)`, we can ignore the difference between upper and lower case before models check.
Fixes #1870
=> feat: improve yurtstaticset upgrade model check (#1870)

charts/yurt-manager/templates/yurt-manager.yaml
/kind bug
add resources configuration into yurt-manager deployment
Fixes #1855
```release-note
```
=> add resources configuration into yurt-manager deployment

pkg/yurthub/cachemanager/cache_manager.go, pkg/yurthub/gc/gc.go, pkg/yurthub/storage/etcd/key_test.go
https://github.com/openyurtio/openyurt/issues/1881
to solve issue https://github.com/openyurtio/openyurt/issues/1881
Fixes #
https://github.com/openyurtio/openyurt/issues/1881
=> improve key logs in yurthub component

charts/yurt-manager/Chart.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
The following two pull requests have update helm charts of yurt-manager component, so we need to upgrade yurt-manager helm chart to a new version: 1.4.3
https://github.com/openyurtio/openyurt/pull/1884
https://github.com/openyurtio/openyurt/pull/1897
by the way, we don't need to upgrade appversion because of the code of yurt-manager component has not been modified.
Fixes #
```release-note
```
=> upgrade yurt-manager helm chart version to 1.4.3

test/fuzz/Dockerfile.builder, test/fuzz/go.mod, test/fuzz/oss_fuzz_build.sh, test/fuzz/oss_fuzz_run.sh, test/fuzz/yurtappdaemon_fuzzer.go, test/fuzz/yurtappset_fuzzer.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> add yurt controller fuzz

cmd/yurt-manager/app/options/csrapprovercontroller.go, cmd/yurt-manager/app/options/options.go, pkg/yurtmanager/controller/apis/config/types.go, pkg/yurtmanager/controller/csrapprover/config/types.go, pkg/yurtmanager/controller/csrapprover/csrapprover_controller.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
improve the configuration of concurrent csr approver worker in yurt-manager component
Fixes #
```release-note
```
=> improve concurrent csr approver workers configuration

cmd/yurt-manager/app/options/yurtstaticsetcontroller.go, pkg/yurtmanager/controller/yurtstaticset/config/types.go, pkg/yurtmanager/controller/yurtstaticset/yurtstaticset_controller.go
improve the configuration of concurrent yurtstaticset worker in yurt-manager component
Fixes #1915
=> feat: improve configuration of concurrent yurtstaticset workers (#1915)

docs/proposals/20240102-upgrade-yurtappset-to-v1beta1.md
Adjust the API design of yurtappset
1. combine workloadTemplate & workloadTweaks to make one field to contain all workload setttings
2. combine basicTweaks & advancedTweaks to make it easier to understand
Fixes #
```release-note
```
=> Adjust the API design of yurtappset

README.md
Readme file update with new slack url , kindly update the new url.
=> fix:readme slack url

cmd/yurt-manager/app/options/yurtappdaemoncontroller.go, pkg/yurtmanager/controller/yurtappdaemon/config/types.go, pkg/yurtmanager/controller/yurtappdaemon/yurtappdaemon_controller.go
improve the configuration of concurrent yurtappdaemon workers in yurt-manager component
Fixes #1912
=> feat: improve configuration of concurrent yurtappdaemon workers (#1912)

cmd/yurt-manager/app/options/yurtappoverridercontroller.go, pkg/yurtmanager/controller/yurtappoverrider/config/types.go, pkg/yurtmanager/controller/yurtappoverrider/yurtappoverrider_controller.go
improve the configuration of concurrent yurtappoverrider workers in yurt-manager component
Fixes #1913
=> feat: improve configuration of concurrent yurtappoverrider workers (#1913)

pkg/yurtmanager/controller/raven/gatewaypickup/gateway_pickup_controller.go, pkg/yurtmanager/controller/raven/gatewaypickup/gateway_pickup_controller_test.go, pkg/yurtmanager/controller/raven/util/constants.go
> /sig network
This PR allows traffic from non-clustered nodes to be forwarded via raven to hosts or containers in other regions
Fixes #
```release-note
```
=> The gateway can forward traffic from extra source cidrs

.codecov.yml, sonar-project.properties
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
1. The modification are not effective in the https://github.com/openyurtio/openyurt/pull/2000. The "ignore" field should be flush left. 
2. It's more reasonable for Sonar to exclude generated code when checking for duplicate code.
Fixes #
```release-note
None
```
=> feat: modify sonar and codecov config

.github/workflows/ci.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
1. upgrade actions/checkout from v3 to v4
2. upgrade actions/setup-go from v4 to v5
3. upgrade codecov/codecov-action from v3 to v4
4. remove actions/cache because actions/setup-go@v4 has already included cache feature.
Fixes #
```release-note
```
=> upgrade github actions version

pkg/yurtmanager/webhook/util/controller/webhook_controller.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind bug
yurt-manager component only handle CRD resource of OpenYurt project, because certificates of other components will be effected.
Fixes #
```release-note
```
=> fix only openyurt crd conversion should be handled for upgrading cert

.github/workflows/ci.yaml, README.md, README.zh.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> fix: update md lint

cmd/yurt-manager/app/options/endpointscontroller.go, cmd/yurt-manager/app/options/options.go, pkg/yurtmanager/controller/apis/config/types.go, pkg/yurtmanager/controller/servicetopology/endpoints/config/types.go, pkg/yurtmanager/controller/servicetopology/endpoints/endpoints_controller.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes # 1910
```release-note
```
=> feat: improve the configuration of concurrent servicetopology-endpoints workers

.github/workflows/release-assets.yaml, .gitignore, Makefile
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
revise Makefile
Fixes #
```release-note
```
=> revise makefile for releasing images

pkg/yurthub/server/nonresource.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
support cache raven apis resource in local disk, so raven pod can restart when cloud-edge network connection is offline.
Fixes #
```release-note
```
=> [yurthub]support cache raven apis resource in yurthub component

pkg/yurthub/cachemanager/cache_manager.go, pkg/yurthub/proxy/remote/loadbalancer.go, pkg/yurthub/proxy/util/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
improve log level of yurthub logs because we don't want yurthub to print too many logs.
Fixes #
```release-note
```
=> improve log level of yurthub logs

go.mod
…ce-allocation.
> /kind bug
To address the issue of:
go: k8s.io/dynamic-resource-allocation@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/endpointslice@v0.0.0: invalid version: unknown revision v0.0.0
Fixes #
<!--
`NONE`
```
=> updates the go.mod for k8s.io/endpointslice and k8s.io/dynamic-resource-allocation

cmd/yurt-manager/app/options/nodebucketcontroller.go, pkg/yurtmanager/controller/nodebucket/config/types.go, pkg/yurtmanager/controller/nodebucket/nodebucket_controller.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
improve the configuration of concurrent node bucket workers in yurt-manager component
Fixes #
```release-note
```
=> improve concurrent node bucket workers configuration

charts/yurt-manager/templates/yurt-manager-auto-generated.yaml, cmd/yurt-manager/app/client/client.go, hack/lib/complement-rbac.sh, hack/make-rules/generate_manifests.sh, pkg/yurtmanager/controller/base/controller.go, pkg/yurtmanager/controller/csrapprover/csr_approver_controller.go, pkg/yurtmanager/controller/daemonpodupdater/daemon_pod_updater_controller.go, pkg/yurtmanager/controller/loadbalancerset/loadbalancerset/load_balancer_set_controller.go, pkg/yurtmanager/controller/nodebucket/node_bucket_controller.go, pkg/yurtmanager/controller/nodelifecycle/node_life_cycle_controller.go, pkg/yurtmanager/controller/nodepool/nodepool_controller.go, pkg/yurtmanager/controller/platformadmin/platform_admin_controller.go, pkg/yurtmanager/controller/raven/dns/gateway_dns_controller.go, pkg/yurtmanager/controller/raven/gatewayinternalservice/gateway_internal_service_controller.go, pkg/yurtmanager/controller/raven/gatewaypickup/gateway_pickup_controller.go, pkg/yurtmanager/controller/raven/gatewaypublicservice/gateway_public_service_controller.go, pkg/yurtmanager/controller/servicetopology/endpoints/service_topology_endpoints_controller.go, pkg/yurtmanager/controller/servicetopology/endpointslice/service_topology_endpointslice_controller.go, pkg/yurtmanager/controller/yurtappdaemon/yurt_app_daemon_controller.go, pkg/yurtmanager/controller/yurtappoverrider/yurt_app_overrider_controller.go, pkg/yurtmanager/controller/yurtappset/yurt_app_set_controller.go, pkg/yurtmanager/controller/yurtcoordinator/cert/yurt_coordinator_cert_controller.go, pkg/yurtmanager/controller/yurtcoordinator/delegatelease/delegate_lease_controller.go, pkg/yurtmanager/controller/yurtcoordinator/podbinding/pod_binding_controller.go, pkg/yurtmanager/controller/yurtstaticset/yurt_static_set_controller.go, pkg/yurtmanager/webhook/server.go, pkg/yurtmanager/webhook/yurtappset/v1beta1/yurtappset_handler.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
1. move list/watch rbac settings from controllers to base controller, because base controller list/watch resources only.
2. specify secret name `yurt-manager-webhook-certs` for webhook rbac setting
3. controllers will get/list unstructured resources from cache instead of kube-apiserver.
Fixes #
```release-note
```
=> improve yurt-manager rbac

pkg/yurtmanager/webhook/deploymentrender/v1alpha1/deploymentrender_handler.go, pkg/yurtmanager/webhook/gateway/v1alpha1/gateway_handler.go, pkg/yurtmanager/webhook/gateway/v1beta1/gateway_handler.go, pkg/yurtmanager/webhook/node/v1/node_handler.go, pkg/yurtmanager/webhook/nodepool/v1beta1/nodepool_handler.go, pkg/yurtmanager/webhook/platformadmin/v1alpha1/platformadmin_handler.go, pkg/yurtmanager/webhook/platformadmin/v1alpha2/platformadmin_handler.go, pkg/yurtmanager/webhook/pod/v1alpha1/pod_handler.go, pkg/yurtmanager/webhook/server.go, pkg/yurtmanager/webhook/util/util.go, pkg/yurtmanager/webhook/yurtappdaemon/v1alpha1/yurtappdaemon_handler.go, pkg/yurtmanager/webhook/yurtappoverrider/v1alpha1/yurtappoverrider_handler.go, pkg/yurtmanager/webhook/yurtappset/v1beta1/yurtappset_handler.go, pkg/yurtmanager/webhook/yurtstaticset/v1alpha1/yurtstaticset_handler.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Extract a new function named `RegisterWebhook` for setting up all webhooks. include controller webhook and independent webhook.
Fixes #
```release-note
```
=> improve webhook setup

charts/yurt-manager/templates/yurt-manager-auto-generated.yaml, cmd/yurt-manager/app/options/endpointscontroller.go, cmd/yurt-manager/app/options/endpointslicecontroller.go, cmd/yurt-manager/app/options/options.go, pkg/yurtmanager/controller/apis/config/types.go, pkg/yurtmanager/controller/servicetopology/endpoints/service_topology_endpoints_controller.go, pkg/yurtmanager/controller/servicetopology/endpointslice/config/types.go, pkg/yurtmanager/controller/servicetopology/endpointslice/service_topology_endpointslice_controller.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
1. add  `concurrent-endpointslice-workers` parameter for service topology endpointslice controller in yurt-manager.
2. typo fix: EndPoints --> Endpoints
3. remove nodepool rbac setting for endpoints controller and endpointslice controller because it is unused by these controllers.
Fixes #
```release-note
```
=> feat: improve concurrent workers parameter for service topology endpointslice controller

cmd/yurt-manager/app/options/options.go, cmd/yurt-manager/app/options/yurtappsetcontroller.go, pkg/yurtmanager/controller/yurtappset/config/types.go, pkg/yurtmanager/controller/yurtappset/yurt_app_set_controller.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
By adding new startup parameter `concurrent-yurtappset-worker` for yurtappset controller
Fixes #
```release-note
```
=> feat: improve concurrent workers parameter for yurtappset controller

cmd/yurt-manager/app/options/gatewaydnscontroller.go, cmd/yurt-manager/app/options/gatewayinternalsvccontroller.go, cmd/yurt-manager/app/options/gatewaypickupcontroller.go, cmd/yurt-manager/app/options/gatewaypublicsvccontroller.go, cmd/yurt-manager/app/options/options.go, pkg/yurtmanager/controller/apis/config/types.go, pkg/yurtmanager/controller/raven/dns/config/types.go, pkg/yurtmanager/controller/raven/dns/gateway_dns_controller.go, pkg/yurtmanager/controller/raven/gatewayinternalservice/config/types.go, pkg/yurtmanager/controller/raven/gatewayinternalservice/gateway_internal_service_controller.go, pkg/yurtmanager/controller/raven/gatewaypickup/gateway_pickup_controller.go, pkg/yurtmanager/controller/raven/gatewaypublicservice/config/types.go, pkg/yurtmanager/controller/raven/gatewaypublicservice/gateway_public_service_controller.go, pkg/yurtmanager/controller/raven/util/constants.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
improve concurrent workers parameter for raven controllers
Fixes #
```release-note
```
=> feat: improve concurrent workers for raven controllers

pkg/yurthub/cachemanager/cache_manager_test.go, pkg/yurthub/filter/approver/approver.go, pkg/yurthub/filter/approver/approver_test.go, pkg/yurthub/filter/manager/manager_test.go, pkg/yurthub/filter/responsefilter/filter_test.go, pkg/yurthub/proxy/local/local_test.go, pkg/yurthub/proxy/proxy.go, pkg/yurthub/proxy/remote/loadbalancer.go, pkg/yurthub/proxy/util/util.go, pkg/yurthub/proxy/util/util_test.go, pkg/yurthub/util/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
1. use entire user agent for cloud working mode, so requests that posted by controller clients of each yurt-manager can be monitored in yurthub metrics
2. wrap response in order to recored the traffic for any resource requests instead only for requests that be cached.
Fixes #
```release-note
```
=> feat: improve metrics of yurthub component

cmd/yurt-manager/app/manager.go, cmd/yurthub/app/start.go, pkg/projectinfo/metrics.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
Add version metrics for yurt-manager and yurthub components. then you can get `openyurt_version_info` from the following link.
- yurt-manager: curl http://{pod-ip}:10271/metrics
- yurthub: curl http://127.0.0.1:10267/metrics
Fixes #
```release-note
```
=> feat: add version metrics for yurt-manager and yurthub components

charts/yurt-manager/templates/yurt-manager-auto-generated.yaml, pkg/yurtmanager/controller/base/controller.go, pkg/yurtmanager/controller/daemonpodupdater/daemon_pod_updater_controller.go, pkg/yurtmanager/controller/nodelifecycle/node_life_cycle_controller.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
1. remove list/watch secrets rbac from base controller
2. remove create pods rbac from daemon updater controller
3. add patch nodes rbac for nodelifecycle controller
Fixes #
```release-note
```
=> feat: improve rbac settings of yurt-manager component

CHANGELOG.md, README.md, README.zh.md, charts/yurt-coordinator/Chart.yaml, charts/yurt-iot-dock/Chart.yaml, charts/yurt-manager/Chart.yaml, charts/yurthub/Chart.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
upgrade the following docs for OpenYurt v1.5:
1. helm charts
2. readme and changeLog
Fixes #
```release-note
```
=> upgrade OpenYurt to v1.5

.github/workflows/release-assets.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
goreleaser/goreleaser-action v1.26.2 can not support multiple platforms, so fix to v1.25.1 to solve this error at this time.
and we will upgrade to v2.x.x in the late future.
Fixes #
```release-note
```
=> fix goreleaser run error

.github/workflows/sync-charts.yaml, charts/yurt-coordinator/Chart.yaml, charts/yurt-iot-dock/Chart.yaml, charts/yurt-manager/Chart.yaml, charts/yurt-manager/templates/yurt-manager.yaml, charts/yurt-manager/values.yaml, charts/yurthub/Chart.yaml, charts/yurthub/templates/yurthub-cloud-yurtstaticset.yaml, charts/yurthub/templates/yurthub-yurtstaticset.yaml, charts/yurthub/values.yaml, hack/lib/sync-charts.sh
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
From OpenYurt v1.5.0, Helm Charts of OpenYurt are hosted in the `openyurtio/charts` repo. so sync charts script is improved to adapt the new repo.
by the way, update image tag to v1.5.0.
Fixes #
```release-note
```
=> fix appVersion to v1.5.0 and sync charts to openyurtio/charts

.github/workflows/sync-charts.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
enable `sync-charts` github action can be triggered manually.
Fixes #
```release-note
```
=> feat: enable trigger sync charts manually

pkg/yurtmanager/webhook/platformadmin/v1alpha1/platformadmin_default_test.go, pkg/yurtmanager/webhook/platformadmin/v1alpha2/platformadmin_default_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
add platformadmin ut with tongyilingma
Fixes #
=> feat: add platformadmin ut with tongyilingma

pkg/yurthub/network/iptables_test.go, pkg/yurthub/proxy/local/faketoken_test.go, pkg/yurtmanager/controller/raven/gatewayinternalservice/gateway_internal_service_enqueue_handlers_test.go, pkg/yurtmanager/controller/raven/gatewaypickup/gateway_pickup_enqueue_handlers_test.go, pkg/yurtmanager/controller/raven/gatewaypublicservice/gateway_public_service_enqueue_handlers_test.go, pkg/yurtmanager/webhook/platformadmin/v1alpha1/platformadmin_validation_test.go, pkg/yurtmanager/webhook/platformadmin/v1alpha2/platformadmin_validation_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
feat: add ut by tongyilingma
Fixes #
@rambohe-ch
=> feat: add ut by tongyilingma

pkg/yurthub/otaupdate/util/util_test.go
Fixes https://github.com/openyurtio/openyurt/issues/2082
```release-note
```
=> Add test unit cases for util

README.md, README.zh.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
=> fix: update scorecard link

.github/workflows/trivy-scan.yml, cmd/yurt-manager/app/manager.go, cmd/yurt-manager/app/options/generic.go, pkg/yurtmanager/controller/apis/config/types.go
When yurt-manager specifies a kubeconfig and sets automountServiceAccountToken to false, yurt-manager will fail to start.
```none```
=> using the kubeconfig flag in controller-runtime.

README.md, README.zh.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
update openssf best practices over 100%, and got passing badge
Fixes #2185 
```release-note
```
=> update openssf best practices badge

CONTRIBUTING.md
=> doc: update contributing.md

pkg/yurtmanager/webhook/util/controller/webhook_controller.go
/kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
YurtManager watches ValidatingWebhookConfiguration and MutatingWebhookConfiguration and update its `clientConfig` according to the `WEBHOOK_HOST` environment variable. 
However, some CRDs (eg. `NodePool`) also include the `clientConfig` field in `spec.conversion.webhook`, and the Helm chart already set it. It seems the YurtManager forgot to update it while updating `crd.Spec.Conversion.Webhook.ClientConfig.CABundle`.
Fixes #
```release-note
```
=> fix: CRD WebhookConversion respect WEBHOOK_HOST env

cmd/yurthub/app/config/config.go, pkg/yurthub/filter/interfaces.go, pkg/yurthub/filter/manager/manager.go, pkg/yurthub/filter/manager/manager_test.go, pkg/yurthub/filter/objectfilter/chain.go, pkg/yurthub/filter/responsefilter/filter.go, pkg/yurthub/proxy/multiplexer/multiplexerlist.go, pkg/yurthub/proxy/multiplexer/multiplexerproxy.go, pkg/yurthub/proxy/multiplexer/multiplexerwatch.go, pkg/yurthub/proxy/multiplexer/testing/fake_filtermanager.go, pkg/yurthub/proxy/pool/pool.go, pkg/yurthub/proxy/proxy.go, pkg/yurthub/proxy/remote/loadbalancer.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
1. remove `filterchain` definition in responsefilter
2. add bool return value for `FindObjectFilter` func in FilterFinder interface.
Fixes #
```release-note
```
=> feat: improve filter chain and FilterFinder interface

CONTRIBUTING.md, README.md, README.zh.md
/kind bug 
Fixes # https://github.com/openyurtio/openyurt/issues/2264
```release-note
```
=> docs: update contributing link and pub date

test/e2e/util/nodepool.go, test/e2e/yurt/nodepool.go
Fixes the nodepool e2e test which is currently commented out
Fixes https://github.com/openyurtio/openyurt/issues/2282
no
In the e2e test, worker2 is not assigned to anything; we instead evaluate 2 scenarios:
1. Create an empty nodepool without nodes then delete it (this is allowed as the webhook won't return validation error).
2. Create a nodepool with worker2 (currently unmapped). Assert it became ready in the nodepool. We don't delete this  as there's no simple way to recreate it in the kind cluster (for now).
=> test: fix nodepool e2e test

pkg/yurtadm/util/yurthub/yurthub.go, pkg/yurtadm/util/yurthub/yurthub_test.go
/kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
https://github.com/openyurtio/openyurt/issues/2270
Fixes #2270
None
=> fix: always overwrite server-addr in yurt-static-set-yurt-hub configmap by yurtadm command

pkg/yurtmanager/controller/daemonpodupdater/daemon_pod_updater_controller.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
fix small typos.
Fixes #
```release-note
```
=> fix small typos

cmd/yurthub/app/start.go, pkg/yurthub/gc/gc.go, pkg/yurthub/healthchecker/cloudapiserver/fake_checker.go, pkg/yurthub/healthchecker/cloudapiserver/health_checker.go, pkg/yurthub/healthchecker/cloudapiserver/health_checker_test.go, pkg/yurthub/healthchecker/cloudapiserver/node_lease.go, pkg/yurthub/healthchecker/cloudapiserver/node_lease_test.go, pkg/yurthub/healthchecker/cloudapiserver/prober.go, pkg/yurthub/healthchecker/cloudapiserver/prober_test.go, pkg/yurthub/healthchecker/interfaces.go, pkg/yurthub/healthchecker/leaderhub/leader_hub.go, pkg/yurthub/healthchecker/leaderhub/leader_hub_test.go, pkg/yurthub/otaupdate/ota.go, pkg/yurthub/otaupdate/ota_test.go, pkg/yurthub/proxy/autonomy/autonomy.go, pkg/yurthub/proxy/nonresourcerequest/nonresource.go, pkg/yurthub/proxy/nonresourcerequest/nonresource_test.go, pkg/yurthub/proxy/proxy.go, pkg/yurthub/proxy/remote/loadbalancer.go, pkg/yurthub/proxy/remote/loadbalancer_test.go, pkg/yurthub/server/server.go, pkg/yurtmanager/controller/hubleaderconfig/hubleaderconfig_controller.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
add health checker with net.Dial for checking healthy status of leader hub.
by the way,  the pull request which uses leader hub health checker will be posted as soon as possible.
Fixes #2294 
```release-note
```
=> feat: add health checker for leader hub

cmd/yurthub/app/options/options.go, pkg/yurthub/healthchecker/cloudapiserver/fake_checker.go, pkg/yurthub/otaupdate/ota_test.go, pkg/yurthub/proxy/nonresourcerequest/nonresource_test.go, pkg/yurthub/proxy/proxy.go, pkg/yurthub/proxy/remote/loadbalancer.go, pkg/yurthub/proxy/remote/loadbalancer_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
1. Add UpdateBackends() function for LoadBalancer interface, in order to update backends dynamically.
2. Improve LoadBalancing strategy for LoadBalancer, especially for round-robin loadbalancing strategy.
Fixes #
```release-note
```
=> feat: Improve load balancer for supporting update backends dynamically.

charts/yurt-manager/crds/apps.openyurt.io_nodepools.yaml, pkg/apis/apps/v1beta2/nodepool_types.go, pkg/yurtmanager/controller/hubleader/hubleader_controller.go, pkg/yurtmanager/controller/hubleader/hubleader_controller_test.go, pkg/yurtmanager/controller/hubleaderconfig/hubleaderconfig_controller.go, pkg/yurtmanager/controller/hubleaderconfig/hubleaderconfig_controller_test.go, pkg/yurtmanager/webhook/nodepool/v1beta2/nodepool_default.go, pkg/yurtmanager/webhook/nodepool/v1beta2/nodepool_default_test.go, test/e2e/yurt/hubleader.go
/kind feature
Rename the enablePoolScopeMetadata field in v1beta2.NodePool.Spec for clarity
Fixes https://github.com/openyurtio/openyurt/issues/2315
```release-note
NONE
```
After https://github.com/openyurtio/openyurt/pull/2302
=> Rename nodepool enablepoolscopemetadata

charts/yurt-manager/templates/yurt-manager-auto-generated.yaml, charts/yurt-manager/templates/yurt-manager.yaml, cmd/yurt-manager/app/options/hubleaderrbaccontroller.go, cmd/yurt-manager/app/options/options.go, cmd/yurt-manager/names/controller_names.go, pkg/yurtmanager/controller/apis/config/types.go, pkg/yurtmanager/controller/base/controller.go, pkg/yurtmanager/controller/hubleaderconfig/hubleaderconfig_controller.go, pkg/yurtmanager/controller/hubleaderrbac/config/types.go, pkg/yurtmanager/controller/hubleaderrbac/hubleaderrbac_controller.go, pkg/yurtmanager/controller/hubleaderrbac/hubleaderrbac_controller_test.go, test/e2e/yurt/hubleader.go
/kind feature
Adds RBAC cluster role for Yurt Hub multiplexer
Fixes https://github.com/openyurtio/openyurt/issues/2293
```release-note
NONE
```
=> feat: add hub leader RBAC controller

docs/proposals/20240808-enhance-operational-efficiency-of-K8s-cluster-in-IDC.md
malformed file path， and fix reference paths.
```NONE```
=> Update proposal file names to support go mod.

.github/workflows/sonarcloud.yaml
> /kind bug
Fix sonarcloud action error.
```
NONE
```
=> upgrade upload-artifact to v4.

docs/proposals/20220627-yurthub-cache-refactoring.md, docs/proposals/20230706-yurtappoverrider.md, docs/proposals/20231205-yurt-express.md, docs/proposals/YYYYMMDD-template.md, pkg/node-servant/config/options.go, pkg/yurthub/multiplexer/multiplexer.go, pkg/yurtmanager/controller/yurtappset/adapter/deployment_adapter_test.go, pkg/yurtmanager/controller/yurtappset/revision_test.go, test/e2e/cmd/init/init_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fix typos
Fixes #
```release-note
NONE
```
=> chore: Fix typos

pkg/yurttunnel/server/serveraddr/addr.go
fix some function names in comment
Fixes #
```release-note
```
=> chore: fix some function names in comment

charts/yurt-iot-dock/Chart.yaml, charts/yurt-manager/Chart.yaml, charts/yurthub/Chart.yaml
- 将 yurt-iot-dock、yurt-manager 和 yurthub 的 Chart 版本从 1.6.0 改为 1.6.1
- 将 yurt-iot-dock、yurt-manager 和 yurthub 的 appVersion 从 v1.6.0 改为 v1.6.1
/kind bug 
fix issue 
Fixes # https://github.com/openyurtio/openyurt/issues/2362
```release-note
```
=> build(charts): 更新 Helm Chart版本

ROADMAP.md
2025 roadmap
-->
```release-note
none
```
=> 2025 roadmap.

pkg/yurthub/metrics/metrics.go, pkg/yurthub/multiplexer/multiplexer.go, pkg/yurthub/multiplexer/multiplexer_test.go, pkg/yurthub/proxy/proxy.go, pkg/yurthub/proxy/remote/remote.go, pkg/yurthub/proxy/util/util.go, pkg/yurthub/proxy/util/util_test.go, pkg/yurthub/util/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
1. add metric: target_for_multiplexer_requests_collector, is used for collecting requests which sent by multiplexer for pool scope metadata and which server will be forwarded(leader hub or kube-apiserver)
2. rename metric `in_flight_multiplexer_requests_collector` to `aggregated_in_flight_requests_collector `
3. rename metric `in_flight_multiplexer_requests_total` to `aggregated_in_flight_requests_total `
4. improve proxy handler for serving requests.
Fixes #
```release-note …
```
=> feat: improve proxy handler for yurthub and optimize metrics of multiplexer

cmd/yurthub/app/config/config.go, pkg/yurthub/multiplexer/multiplexer.go, pkg/yurthub/multiplexer/multiplexer_test.go, pkg/yurthub/proxy/proxy.go, pkg/yurthub/proxy/remote/loadbalancer.go, pkg/yurthub/proxy/remote/loadbalancer_test.go
/kind feature
Add consistent hashing strategy for yurt hub remote proxy load balancer strategy
Fixes https://github.com/openyurtio/openyurt/issues/2341
```release-note
NONE
```
=> feat: add consistent hashing strategy for yurthub

.goreleaser.yaml
Supports installing Hub using the systemd method.
-->
```release-note
NONE
```
=> release assets add yurthub binary.
