openyurtio/openyurt

- config/yurtctl-servant/setup_edgenode
- docs/todo.md
- pkg/yurtctl/cmd/cmd.go
- pkg/yurtctl/cmd/convert/convert.go
- pkg/yurtctl/cmd/revert/revert.go
- pkg/yurtctl/constants/constants.go
- pkg/yurtctl/util/kubernetes/util.go
- pkg/yurtctl/util/strings/util.go
1. implement revert subcommand, which allows user to revert a yurtcluster back to a kubernetes cluster
2. extract common functions and put them in pkg/yurtctl/util/kubernetes/util.go
3. fix golint issues
4. add yurtctl tutorial draft docs/tutorial/yurtctl.md
5. add docs/todo.md
> implement `revert` subcommand

- pkg/yurthub/healthchecker/health_checker_test.go
- pkg/yurthub/storage/disk/storage.go
- pkg/yurthub/storage/disk/storage_test.go
- pkg/yurthub/storage/factory/factory.go
This change fixes health_checker_test and storage_test. 
The ports 8080/8081/8082 can easily be occupied by other processes. This change picks ports that are less likely to be occupied.
"/etc/kubernetes/cache" directory often needs permission to create. This change creates test directory in "/tmp/cache/".
> Fix yurthub tests

- config/yurtctl-servant/setup_edgenode
- pkg/yurtctl/cmd/convert/convert.go
- pkg/yurtctl/cmd/revert/revert.go
- pkg/yurtctl/constants/constants.go
- pkg/yurtctl/util/kubernetes/util.go
1. validate apiserver version before performing conversion and reversion
2. create kubelet-client-current.pem if it doesn't exist
3. fix setup_edgenode bug that may crash the kubelet
> validate apiserver version before performing conversion and reversion

- config/setup/yurthub.yaml
- config/yurtctl-servant/setup_edgenode
- docs/tutorial/manually-setup.md
- pkg/yurthub/README.md
Instead of getting the apiserver's address from the env during the runtime, let servant pod set it before deploying the yurthub.
fix #47
> set the server-addr before deploying the yurthub

- pkg/yurthub/storage/disk/storage.go
- what this PR does ?
yurthub's data cache processing is:
- step1. create temporary data files without O_SYNC
- step2. delete old data files
- step3. rename temporary data file into cache data file
after up steps completed, the cache data may not persisted on local disk for not sync write, so when power of machine is suddenly off, the cache data is lost.
in this PR, we modify the up step1 from not sync write to sync write
> fix a sudden power off may result in local cache loss

- config/yurtctl-servant/setup_edgenode
yurtctl used to keep the --bootstrap-kubeconfig option, if the bootstrap
kubeconfig exist, which may results in the 10.kubeadm.conf being reset.
To fix this, we remove the --bootstrap-kubeconfig option from the
10.kubeadm.conf when converting kubernetes to yurt cluster.
> fix the yurtctl bug

- config/setup/yurt-tunnel-agent.yaml
- config/setup/yurt-tunnel-server.yaml
- pkg/yurttunnel/agent/agent.go
- pkg/yurttunnel/agent/anpagent.go
- pkg/yurttunnel/agent/cmd.go
- pkg/yurttunnel/handlerwrapper/handlerwrapper.go
- pkg/yurttunnel/handlerwrapper/printreqinfo/printreqinfo.go
- pkg/yurttunnel/handlerwrapper/wraphandler/wraphandler.go
- pkg/yurttunnel/server/anpserver.go
- pkg/yurttunnel/server/cmd.go
- pkg/yurttunnel/server/server.go
1. implement the handlerwrapper, which takes in one http.handler and wraps it within another
2. decouple the anp tunnel server/agent using TunnelServer and TunnelAgent interface
> Refactor: implement the HandlerWrapper and decouple server/agent interface from implementation 

- docs/tutorial/manually-setup.md
remove kubelet config bootstrap args when manually
> remove kubelet config bootstrap args when manually

- pkg/yurtctl/lock/lock.go
- pkg/yurtctl/lock/lock_test.go
fix #84 
implement the timeout mechanism for yurtctl lock. The lock can only be held by an owner for no longer than 5 minutes, as all operations (convert and revert) should be completed within 3 minutes.
The timeout mechanism is just a short-term workaround, in the future version, we will use a CRD and controller to manage the openyurt cluster, which also prevents the contention between users.
> Feature: add timeout to yurtctl lock

- cmd/yurt-tunnel-agent/agent.go
- cmd/yurt-tunnel-server/server.go
- config/yurtctl-servant/setup_edgenode
- pkg/projectinfo/projectinfo.go
- pkg/yurtctl/cmd/cmd.go
- pkg/yurtctl/cmd/convert/convert.go
- pkg/yurtctl/cmd/markautonomous/markautonomous.go
- pkg/yurtctl/cmd/revert/revert.go
- pkg/yurtctl/constants/constants.go
- pkg/yurtctl/constants/yurt-tunnel-agent-tmpl.go
- pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go
- pkg/yurtctl/util/kubernetes/util.go
- pkg/yurttunnel/agent/cmd.go
- pkg/yurttunnel/constants/constants.go
- pkg/yurttunnel/iptables/iptables.go
- pkg/yurttunnel/pki/certmanager/certmanager.go
- pkg/yurttunnel/server/anpserver.go
- pkg/yurttunnel/server/cmd.go
- pkg/yurttunnel/server/server.go
- test/e2e/yurthub/yurthub.go
- test/e2e/yurttunnel/yurttunnel.go
1. allow users to deploy yurttunnel using `yurtctl convert`, for example: 
```bash
yurtctl convert --cloud-nodes minikube --provider minikube --deploy-yurttunnel
``` 
or
```bash
yurtctl convert --provider minikube -c minikube -t -v 4
```
2. if yurttunnel is deployed, `yurtctl revert` will remove it
3. share projectinfo across packages (i.e. yurtctl, yurttunnel, test)
> Feature: Deploy the yurt-tunnel using yurtctl convert option

- hack/lib/build.sh
- hack/lib/common.sh
- hack/lib/init.sh
- hack/lib/release-images.sh
- hack/make-rules/release-images.sh
1. enable compile when use WHAT string begins with cmd/, for example: make build WHAT=cmd/yurthub
2. fix customize project info(for example: PROJECT_PREFIX=edge) compile error for make build/release
> Bugfix: fix compile error when use customize settings

- cmd/yurthub/app/config/config.go
- cmd/yurthub/app/options/options.go
- cmd/yurthub/app/start.go
- pkg/projectinfo/projectinfo.go
- pkg/yurthub/certificate/kubelet/cert_mgr.go
because of user can define name of hub by using makefile PROJECT_PREFIX setting, so hub log should not include “yurt” string. and it's need to keep consistent with  the name of hub.
> Refactor: refactor hub log without yurt instead of using projectinfo

- cmd/yurthub/app/config/config.go
- cmd/yurthub/app/options/options.go
- cmd/yurthub/app/start.go
- pkg/yurthub/certificate/hubself/cert_mgr.go
- pkg/yurthub/certificate/initializer/initializer.go
- pkg/yurthub/certificate/kubelet/cert_mgr.go
- pkg/yurthub/util/util.go
yurthub is currently communicating with master using the kubelet component's certificate(/etc/kubernetes/kubelet.conf), and when the node certificate expires, yurthub will not work because kubelet cannot update the node certificate via yurthub.
To solve this case, add node certificate generation and cycle updating ability to yurthub, so yurthub without kubelet node certificate can communicate with master. and when node certificate expires, yurthub can update it by itself.
> Feature: add hubself cert manage mode that use bearer token to bootstrap yurthub agent

- pkg/yurthub/server/certificate.go
- pkg/yurthub/server/server.go
- feature background:
when the following conditions are met at the same time, the node certificate cannot be updated normally even if the cloud-edge network is restored.
- the cloud-edge network is disconnected
- node certificate expires
- bootstrap token expires
- solution:
an API is provided that allows users to update the bootstrap token to rotate certificates.
- the command for update join token:
curl -XPUT -d '{"jointoken": "newxxx.jointokenxxx"}' "http://127.0.0.1:10261/v1/token"
> Feature: add handler for updating join token for hub agent

- pkg/yurthub/proxy/proxy.go
- pkg/yurthub/proxy/util/util.go
- pkg/yurthub/proxy/util/util_test.go
1. separate the max in-flight limit request handler and trace request handler
2. refactor newWrapperResponseWriter by including http.Flusher and http.CloseNotifier interface
3. adjust max in-flight request handler at the entry point of http request
> refactor: proxy handler of yurthub

- pkg/yurthub/certificate/hubself/cert_mgr.go
- pkg/yurthub/proxy/local/local.go
- pkg/yurthub/proxy/util/util.go
- pkg/yurthub/storage/disk/storage.go
- pkg/yurthub/storage/disk/storage_test.go
- pkg/yurthub/storage/store.go
- background:
1. at present, when cache data of yurthub(under /etc/kubernetes/cache directory) is removed, local proxy will return empty object slice for kubelet request.
2. when network between edge and cloud is disconnected, yurthub will use empty cache to response kubelet request. if response of list pods request is empty objects slice(len(ListPods.Items[])=0)，all pods that are running on the current node will be killed. so it will effect the edge business.
- solution:
if specified data is not found in cache data(for example: list pods)，yurthub not return empty objects slice for request, yurthub will return 404 status code for request, so kubelet only re-request data but not kill pods.
> refactor: when cache data of hub agent is removed not on purpose, return 404 instead of empty objects for kubelet request

- pkg/yurttunnel/handlerwrapper/handlerwrapper.go
- pkg/yurttunnel/handlerwrapper/initializer/initalizer.go
- pkg/yurttunnel/handlerwrapper/tracerequest/tracereq.go
- pkg/yurttunnel/handlerwrapper/wraphandler/wraphandler.go
- pkg/yurttunnel/server/anpserver.go
- pkg/yurttunnel/server/cmd.go
- pkg/yurttunnel/server/server.go
- background:
1. the package importing order decide the order in which the middleware will be called, but the go fmt will modify the import order automatically. so the import order can not take effect.
2. wrap handler is useful for user to extend ability of tunnel server handler, but if the extended handler need some setting from outside, there is no way at present.
- solution
1. add `Register()` func and register wrap handler explicitly in init() func.
2. add initializer for adding setting(like sharedinformerfactory) into wrap handler(middleware)
> refactor: add initializer for adding sharedinformerfactory into middleware and register middleware explicitly by adding register func.

- pkg/projectinfo/projectinfo.go
- pkg/yurttunnel/agent/anpagent.go
- pkg/yurttunnel/constants/constants.go
- pkg/yurttunnel/iptables/iptables.go
- pkg/yurttunnel/pki/certmanager/certmanager.go
- pkg/yurttunnel/pki/certmanager/csrapprover.go
- pkg/yurttunnel/server/cmd.go
refactor logs output and security of yurt-tunnel
1. modify the name of tunnel in logs according to projectinfo, not hard-code yurt-tunnel
2. modify the insecure address of yurt tunnel server to `127.0.0.1` because of security requirement.
> refactor: make sure the name of tunnel in logs according to projectinfo

- pkg/yurtctl/cmd/convert/convert.go
- pkg/yurtctl/cmd/revert/revert.go
- pkg/yurtctl/constants/constants.go
- pkg/yurtctl/util/kubernetes/util.go
Found no ` such Comfigmap`: `kube-system/yurttunnel-server-cfg` created when use `yurtctl` when I try this:
https://github.com/alibaba/openyurt/issues/138#issuecomment-723555668
> Create CM for configuration of request redirect to tunnel server

- pkg/yurttunnel/agent/agent.go
- pkg/yurttunnel/agent/cmd.go
- pkg/yurttunnel/pki/certmanager/certmanager.go
- pkg/yurttunnel/server/serveraddr/addr.go
refactor the process of getting tunnel server address for the following reasons:
1. put the getting tunnel server info func(`GetYurttunelServerDNSandIP`) in certmanager dir is confusing
2. in func `GetTunnelServerAddr`, get x-tunnel-server-svc twice and it is not necessary.
so we did the following refactor
1. create a new dir named `serveraddr` and put it as sub dir of server.
2. add `getTunnelServerResources` and `extractTunnelServerDNSandIPs` func to separate resource getting and resource extraction, for avoiding get service twice.
> refactor: extract the process of getting tunnel server info into serveraddr dir

- pkg/yurtctl/cmd/revert/revert.go
`tunnel server` is a `deployment` rather than `daemonset`.
> Remove tunnel server when revert

- hack/lib/init.sh
when executed `make build` command,  you can configure git version by GIT_VERSION parameter, and configure image repo by REPO parameter. the command like this:
```
make build GIT_VERSION=xxx REPO=xxx
```
> refactor: git version and image repo can be setup as required by user

- cmd/yurt-tunnel-agent/agent.go
- cmd/yurt-tunnel-server/server.go
- go.mod
- pkg/yurttunnel/agent/anpagent.go
- pkg/yurttunnel/agent/cmd.go
- pkg/yurttunnel/handlerwrapper/handlerwrapper.go
- pkg/yurttunnel/handlerwrapper/tracerequest/tracereq.go
- pkg/yurttunnel/handlerwrapper/wraphandler/wraphandler.go
- pkg/yurttunnel/iptables/iptables.go
- pkg/yurttunnel/kubernetes/kubernetes.go
- pkg/yurttunnel/pki/certmanager/certmanager.go
- pkg/yurttunnel/pki/certmanager/csrapprover.go
- pkg/yurttunnel/server/anpserver.go
- pkg/yurttunnel/server/cmd.go
- pkg/yurttunnel/server/interceptor.go
- pkg/yurttunnel/server/serveraddr/addr.go
because underlying imported lib(anp) in yurt tunnel used klog/v2 as logger, so adapt klog/v2 in yurt tunnel for optimizing log output
> refactor: adapt k8s.io/klog/v2 for yurt tunnel

- pkg/yurttunnel/iptables/iptables.go
The `configmap` which used for request redirect named `yurt-tunnel-server-cfg`, the code will generated a wrong name:
`yurttunnel-server-cfg`, that's make the functionality not work.
> the configmap of request redirect is not correct

- Makefile
Will raise exception:
`hack/make-rules/release-images.sh: 19: hack/make-rules/release-images.sh: Bad substitution`
> Fix "make release" issue

- pkg/yurttunnel/handlerwrapper/handlerwrapper.go
- pkg/yurttunnel/handlerwrapper/wraphandler/wraphandler.go
- pkg/yurttunnel/server/anpserver.go
- pkg/yurttunnel/server/cmd.go
- pkg/yurttunnel/server/server.go
take the handler wrappers creation out of new tunnel server. because handler wrappers are not part of tunnel server, it is only used by tunnel server. so we need to prepare handler wrappers before new tunnel server.
make test
make build
run tunnel server and check tracereq middleware is registered in handler.
> refactor: create handler wrappers before new tunnel server

- pkg/yurttunnel/iptables/iptables.go
- pkg/yurttunnel/server/cmd.go
take the sync iptables process as a function(`func syncIptablesSetting()`), so delete the duplicated code.
make build
make test
and verify the iptables rule generated by tunnel server are correct.
> refactor: reduce the duplication of syncing iptables setting

- docs/proposals/YYYYMMDD-template.md
This PR adds a template which will be used to document all design proposals for news features. 
The submitter does not need to fill every part of the template but should follow the major flow and provide sufficient context.
> Add proposal template

- pkg/yurtctl/constants/constants.go
deploy servantJob and yurt-controller-manager using host network mode.
The two components were deployed using container network mode by default.  Now, modify them to host network mode.
(1)add hostNetwork:true for ServantJobTemplate.
(2)add hostNetwork:true for YurtControllerManagerDeployment.
NONE
When k8s cluster don't install container network plugin，the two components will fail to deploy.
make test
make build
_output/bin/yurtctl convert --provider [minikube|ack]
> fix: deploy servantJob and yurt-controller-manager using host network mode.

- pkg/yurtctl/constants/constants.go
Fix: add list and watch authority of pods, nodes, leases and daemonsets for yurt-controller-manager
(1)add watch authority of nodes for yurt-controller-manager
(2)add watch authority of events for yurt-controller-manager
(3)add list/watch authority of leases for  yurt-controller-manager
(4)add list/watch authority of daemonsets for yurt-controller-manager
NONE
yurt-controller-manager  reports an error of insufficient authority, when it's running. 
make test
make build
_output/bin/yurtctl convert --provider [minikube|ack]
> Fix: add list and watch authority of pods, nodes, leases and daemonsets for yurt-controller-manager

- config/setup/yurt-tunnel-agent.yaml
- config/setup/yurt-tunnel-server.yaml
- config/yaml-template/yurt-tunnel-agent.yaml
- config/yaml-template/yurt-tunnel-server.yaml
- pkg/yurtctl/constants/yurt-tunnel-agent-tmpl.go
- pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go
refactor the template of yurt-tunnel.
(1) delete nodeselector beta.kubernetes.io/os=amd64
(2) modify imagePullPolicy to IfNotPresent
(3)add volume tunnel-agent-dir/tunnel-server-dir
No issue, the reason for the modification is as follows:
(1) yurt-tunnel-agent need support multiple cpu arch, include arm, arm64 and amd64.
(2) If the imagePullPolicy is always, the corresponding pod cann't be restarted when the edge node is disconnected.
(3) yurt-tunnel will use dir /var/lib/yurthub deposit certificate.
make test
make build
_output/bin/yurtctl convert --provider [minikube|ack|kubeadm]
> refactor the  template of  yurt-tunnel

- pkg/yurtctl/cmd/convert/convert.go
- pkg/yurtctl/cmd/revert/revert.go
Delete clusterrolebinding system:controller:node-controller to disable node-controller.
(1) delete clusterrolebinding system:controller:node-controller when convert to OpenYurt cluster.
(2) create clusterrolebinding system:controller:node-controller when revert to k8s cluster.
because when revert openyurt to kubernetes, a new serviceaccount and secret need to be created, so node-controller must be restarted before new serviceaccount and secret can take effect.
make test
make build
_output/bin/yurtctl convert --provider [minikube|ack|kubeadm]
> Delete clusterrolebinding system:controller:node-controller to disable node-controller.

- config/yurtctl-servant/setup_edgenode
- pkg/yurtctl/util/kubernetes/util.go
(1) support domain name for server addr.
(2)add  Usages and  Groups when creating bootstrap token.
No issue, the reason for the modification is as follows:
(1)minikube use domain name control-plane.minikube.internal to access apiserver.
(2)bootstrap token need set  authentication,signing for  Usages and system:bootstrappers:kubeadm:default-node-token for groups.
make test
make build
_output/bin/yurtctl convert --provider [minikube|ack|kubeadm]
> fix: yurtctl fail to convert minikube cluster.

- pkg/yurtappmanager/controller/nodepool/nodepool_controller.go
Signed-off-by: kadisi <iamkadisi@163.com>
If the host has the same  as taint the node pool before joining the node pool, joining fails
> bugfix: nodepool taint sync error

- pkg/yurthub/proxy/util/util.go
when client close the connection in advance, reserveproxy.ServeHTTP will panic, and everything after ServeHTTP will be skipped except "defer". so the element in reqChan(function WithMaxInFlightLimit) leaks.
reproduce:
1. send a watch curl to yurthub, and stop using ctrl+c （eg. `curl '127.0.0.1:10261/apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=1235193475&timeout=5m&timeoutSeconds=300&watch=true' -o /dev/null -v`）
2. do step-1 for 250 times(depends on the config `MaxRequestInFlight`)
3. send any request to yurt, you'll get 429
this pr moves the operation of the chan into defer, to make sure it will run after ServeHTTP
see the reproduce steps mentioned above
> fix bug when ServeHTTP panic

- docs/tutorial/manually-setup.md
A simple fix for manually-setup tutorial.  The command `systemctl restart` should be `systemctl restart kubelet`
> Docs: fix `systemctl restart` in manually-setup tutorial

- go.mod
- go.sum
- pkg/yurtctl/cmd/clusterinfo/clusterinfo.go
- pkg/yurtctl/cmd/cmd.go
Add a yurtctl subcommand cluster-info, that list edge and cloud nodes
fixes #207 
1. make build
2.  ./_output/bin/yurtctl cluster-info
> [feature request] yurtctl cluster-info subcommand that list edge/cloud nodes

- docs/tutorial/yurtctl.md
Modify the documentation of the yurtctl command according to pr206：
1）Add yurtctl command option description：--pod-manifest-path、--kubeadm-conf-path
2）Add the usage of subcommand `convert/revert edgenode `
> [Doc] Add yurtctl command option description and the usage of subcommand `convert/revert edgenode `

- cmd/yurt-controller-manager/app/options/options.go
Add `--feature-gates ` flag to yurt-controller-manager.
Reference:
https://github.com/kubernetes/kubernetes/blob/v1.16.15/cmd/kube-controller-manager/app/options/options.go#L251
fixes #212
**step1**
Start a 2 nodes Kubernetes cluster, name the master node as `master`  and  the worker node as `worker`:
```
$ kubectl get nodes
NAME     STATUS   ROLES    AGE   VERSION
master   Ready    master   30h   v1.16.15
worker   Ready    <none>   30h   v1.16.15
```
Install and run `yurt-controller-manager` with the following `--feature-gates` flags:
```
./yurt-controller-manager  --kubeconfig $your-kubeconfig --feature-gates=LegacyNodeRoleBehavior=false
```
**step2**
Stop the `kubelet` on the worker node.
**step3**
Watch the output log of `yurt-controller-manager` and wait for the `NodeNotReady` event …
> feat: Add --feature-gate flag to yurt-controller-manager

- docs/tutorial/manually-setup.md
Add Note message for the Docker pull rate limit issue.
Signed-off-by: Yixing Jia <yixingjia@gmail.com>
Since Docker turn on pull rate limit on anonymous request, in that case use a secret to pull the image should be considered.
> Update the Manual document

- docs/proposals/00_openyurt-glossary.md
This PR adds the glossary that defines the frequently used terms. 
NONE
NONE
NONE
NONE
> Doc: Add definitions of terms

- config/setup/yurt-tunnel-agent.yaml
- config/setup/yurt-tunnel-server.yaml
- go.mod
- go.sum
- pkg/yurttunnel/agent/cmd.go
- test/integration/yurttunnel_test.go
1. upgrade the apiserver-network-proxy to the latest release version
2. use `destHost` proxy strategy by default
NONE
NONE
follow the yurt-tunnel tutorial
NONE
> Feature: upgrade apiserver-network-proxy to v0.0.15

- cmd/yurthub/app/config/config.go
- cmd/yurthub/app/options/options.go
- cmd/yurthub/app/start.go
- config/yaml-template/yurthub.yaml
- pkg/yurtctl/util/edgenode/common.go
- pkg/yurthub/profile/profile.go
- pkg/yurthub/server/certificate.go
- pkg/yurthub/server/server.go
Initially, yurtHubServer that listen on 127.0.0.1:10261 handle all requests from clients on edge node, so request can not be proxied to kube-apiserver but instead  handled by yurthub itself when path of request is conflict with local yurthub requests.
in order to solve the above conflict, we divide the yurtHubServer into hubServer and porxyServer, and they listen on different port.
- proxyServer listens on 127.0.0.1:10261,  keep the same port as before
- hubServer listen on 127.0.0.1:10267,  can handle requests like pprof, token update, healthz, metrics etc. 
by the way, we add a parameter `--profiling` to enable/disable debug pprof yurthub, default is enable pprof.
> refactor: divide the yurthubServer into hubServer and proxyServert

- pkg/yurthub/healthchecker/health_checker.go
- pkg/yurthub/metrics/metrics.go
- pkg/yurthub/proxy/util/util.go
- pkg/yurthub/server/server.go
- pkg/yurthub/util/connrotation.go
add prometheus metrics for yurthub as following:
- server_healthy_status: healthy status of remote server. 1: healthy, 0: unhealthy
- in_flight_requests: how many in flight requests are handled by hub agent
- in_flight_request_counter: counter of in flight requests handled by hub agent
- closable_conn_counter: counter of underlay tcp connection for hub agent to remote server
- rejected_request_counter:  counter of rejected requests for exceeding in flight limit in hub agent
- `make release WHAT=cmd/yurthub ARCH=amd64` to build yurthub image
- run new yurthub image
- on the edge node, curl http://127.0.0.1:10267/metrics to verify metrics for yurthub, and the metrics output as following:
```
node_yurthub_closable_conns_collector{server="xx.xx.xx.xx:6443"} 2 …
```
> feature: add promtheus metrics for yurthub

- README.md
- README.zh.md
- config/yurtctl-servant/Dockerfile
- hack/lib/release-images.sh
- pkg/yurtctl/cmd/convert/convert.go
- pkg/yurtctl/cmd/convert/edgenode.go
- pkg/yurtctl/constants/constants.go
- pkg/yurtctl/util/edgenode/util.go
- pkg/yurtctl/util/kubernetes/util.go
1.Only one node in the cluster is installed with openyurt, and then any node in the cluster can be converted.
2.Add support for the conversion between kind and OpenYurt cluster.
fixes #230.
make test
make build
cp _output/bin/yurtctl /bin/
yurtctl convert
yurtctl revert
> Add support for the conversion between kind and OpenYurt cluster

- cmd/yurt-tunnel-agent/app/config/config.go
- cmd/yurt-tunnel-agent/app/options/options.go
- cmd/yurt-tunnel-agent/app/start.go
- cmd/yurt-tunnel-server/app/config/config.go
- cmd/yurt-tunnel-server/app/options/options.go
- cmd/yurt-tunnel-server/app/start.go
- pkg/profile/profile.go
- pkg/yurthub/server/server.go
- pkg/yurttunnel/constants/constants.go
- pkg/yurttunnel/handlerwrapper/tracerequest/tracereq.go
- pkg/yurttunnel/iptables/iptables.go
- pkg/yurttunnel/server/interceptor.go
- pkg/yurttunnel/server/metrics/metrics.go
- pkg/yurttunnel/util/util.go
- add a meta server for yurttunnel in order to handle http requests like profiling and metrics.
- default meta port on which serve meta requests by yurt-tunnel-server is: 10265, and can be set by user with --meta-port parameter.
- default meta port on which serve meta requests by yurt-tunnel-agent is: 10266, and also can be set by user with --meta-port parameter.
make all
make release WHAT=cmd/yurt-tunnel-server
make release WHAT=cmd/yurt-tunnel-agent
and check pprof and metrics at `http://127.0.0.1:10265(6)/metrics` or `http://127.0.0.1:10265(6)/debug/pprof`
> feature: add meta server for handling prometheus metrics and pprof by yurttunnel

- pkg/yurthub/cachemanager/cache_manager.go
- pkg/yurthub/cachemanager/cache_manager_test.go
- pkg/yurthub/cachemanager/fake_storage_wrapper.go
- pkg/yurthub/cachemanager/storage_wrapper.go
- pkg/yurthub/storage/disk/storage.go
- pkg/yurthub/storage/disk/storage_test.go
- pkg/yurthub/storage/store.go
- background:
1. At present, we use `component/resource/namespace/name` as file path to store response objects from kube-apiserver on local disk.
2.  If response objects from kube-apiserver are empty(like kubelet list runtimeclass, csidriver), cache info will not be created on local disk.
3. when cloud-edge network becomes disconnected, kubelet will list runtimeclass, csidriver from local disk cache, and yurthub return 404 to kubele. so kubelet will re-list runtimeclass and csidriver frequently.
- solution:
1. if response objects from kube-apiserver are empty(like kubelet list runtimeclass, csidriver), yurthub can create key info `component/resource` in local disk with `nil` data. 
2. so when kubelet list runtimeclass, csidriver from local disk cache, yurthub will return empty list to …
> bugfix: list runtimeclass and csidriver from cache error when cloud-edge network disconnected

- pkg/yurthub/util/util_test.go
Fixes https://github.com/openyurtio/openyurt/issues/248.
> fix t.Fatalf from a non-test goroutine

- pkg/yurthub/cachemanager/cache_manager.go
- pkg/yurthub/cachemanager/cache_manager_test.go
- pkg/yurthub/cachemanager/storage_wrapper.go
- pkg/yurthub/kubernetes/serializer/serializer.go
- pkg/yurthub/proxy/local/local_test.go
1. Replace the original [serializer.WithoutConversionCodecFactory](https://github.com/alibaba/openyurt/blob/7095962687e2666a27d14e436b96ef893b228beb/pkg/yurthub/kubernetes/serializer/serializer.go#L48) with a custom WithVersionCodecFactory so that the GVK information can be preserved during deserialization. 
2. Delete both the [resourceToKindMap](https://github.com/openyurtio/openyurt/blob/4d7463a40801c29d09c4f7d10ba46b73cb019915/pkg/yurthub/cachemanager/cache_manager.go#L46) and the [resourceToListKindMap](https://github.com/openyurtio/openyurt/blob/4d7463a40801c29d09c4f7d10ba46b73cb019915/pkg/yurthub/cachemanager/cache_manager.go#L62)
3. On the basis of the existing NegotiatedSerializer increase a new [unstructuredNegotiatedSerializer](https://github.com/qclc/openyurt/blob/8e464566f0bd04 …
> Enhance YurtHub's caching ability

- cmd/yurt-tunnel-server/app/config/config.go
- cmd/yurt-tunnel-server/app/options/options.go
- cmd/yurt-tunnel-server/app/start.go
- config/setup/yurt-tunnel-server.yaml
- config/yaml-template/yurt-tunnel-server.yaml
- pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go
- pkg/yurttunnel/dns/dns.go
- pkg/yurttunnel/dns/event.go
- pkg/yurttunnel/dns/handler.go
- pkg/yurttunnel/dns/util.go
- pkg/yurttunnel/iptables/iptables.go
- pkg/yurttunnel/util/util.go
In the edge computing scenario, the IP addresses of the edge nodes are likely to be the same. So we can not rely on the node IP to forward the request but should use the node hostname(unique in one cluster). 
This PR provides the ability for the tunnel-server to handle requests in the form of `scheme://[hostname]:[port]/[req_path]`.
The dns controller will generate a ConfigMap named `yurt-tunnel-nodes` in the `kube-system` namespace.
You need to manually config CoreDNS to use it according to the steps like the following:
First, mount the ConfigMap as volume of CoreDNS Pod, for example
```yaml
volumeMounts:
- mountPath: /etc/edge
name: hosts
readOnly: true
...
volumes:
- configMap:
defaultMode: 420
name: yurt-tunnel-nodes
name: hosts
```
Second, update CoreDNS ConfigMap …
> feature: add dns controller to sync cluster node dns records

- hack/lib/release-images.sh
Since we have migrated `yurt-app-manager` to a independent repository, `make release` will now produce the following error：
```shell
can't load package: package /opt/src/cmd/yurt-app-manager: cannot find package
make: *** [release] Error 1
```
This PR removes `yurt-app-manager` from the build targets to fix this bug.
Ref: #280 
make release
> bugfix: remove yurt-app-manager from the build targets

- pkg/yurttunnel/constants/constants.go
- pkg/yurttunnel/handlerwrapper/tracerequest/tracereq.go
- pkg/yurttunnel/server/interceptor.go
- background:
when Host of request to yurt-tunnel-server for accessing edge component(like kubelet) is hostname, not node ip,
yurt-tunnel-agent can not proxy the request to edge component(like kubelet) because edge component listen on
ip address not hostname.
- solution:
before proxy request to yurt-tunnel-agent in yurt-tunnel-server, we can modify request in `tracerequest handlerWrapper`. and we add the following two routine:
1. transform hostname to nodeIP for request in order to send request to nodeIP address at tunnel-agent
2. put hostname into X-Tunnel-Proxy-Host request header in order to select the correct backend agent.
make all
and run yurt-tunnel in k8s cluster and make sure it work correctly.  @SataQiu
> feature: transform hostname to nodeIP for request.

- config/setup/yurt-tunnel-server.yaml
- config/yaml-template/yurt-tunnel-server.yaml
- pkg/yurtctl/cmd/convert/convert.go
- pkg/yurtctl/cmd/revert/revert.go
- pkg/yurtctl/constants/constants.go
- pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go
- pkg/yurttunnel/constants/constants.go
- pkg/yurttunnel/dns/dns.go
- pkg/yurttunnel/dns/handler.go
- pkg/yurttunnel/pki/certmanager/certmanager.go
- background: 
1. In order to deploy promtheus(also metrics-server) and yurt-tunnel-server on different cloud nodes,  prometheus need to use  {hostname:port} (take port=9100 as a example) to access edge node through yurt-tunnel-server and yurt-tunnel-agent and resolve hostname to service ip of yurt-tunnel-server. on the same time, we need to add 9100:10264 mapping info in yurt-tunnel-server service for redirect port.
2. the original yurt-tunnel-server service(`x-tunnel-server-svc`) is used by yurt-tunnel-agent to connect yurt-tunnel-server. and `x-tunnel-server-svc` service may be configured as NodePort type or LoadBalancer type for public network access. 
3. If `x-tunnel-server-svc` service type is LoadBalancer, the proxy ports  in `x-tunnel-service-svc` service will be listened by …
> enhancement: add tunnel server internal service in order to prevent x-tunnel-server-svc attached SLB to listen unsecure port

- hack/lib/release-images.sh
bugfix: keep image tar file name consistent with image name.
For example, the image `openyurt/yurtctl-servant:v0.3.0-amd64` should be saved as `yurtctl-servant-linux-amd64.tar` instead of `yurtctl-linux-amd64.tar`.
make release
> bugfix: keep image tar file name consistent with image name

- Makefile
- cmd/yurthub/app/config/config.go
- cmd/yurthub/app/options/options.go
- cmd/yurthub/app/start.go
- go.mod
- go.sum
- pkg/yurthub/network/dummyif_linux.go
- pkg/yurthub/network/dummyif_test.go
- pkg/yurthub/network/dummyif_unsupported.go
- pkg/yurthub/network/iptables.go
- pkg/yurthub/network/network.go
- pkg/yurthub/server/server.go
- background:
Yurthub is a node daemon that serves as a proxy for the outbound traffic from the Kubernetes node daemons(like kubelet, kube-proxy and so on), and yurthub is listening on `127.0.0.1:10261` for proxying outbound traffic. so components with hostNetwork=false can not use yurthub to proxy outbound request because of traffic from `container network namespace` to `127.0.0.1` can not route on edge node.
- solution:
Add a dummy network interface on edge node by yurthub, and yurthub listens on `new dummy interface`, so components in its own network namespace can access yurthub through dummy interface. 
the default ip address of new dummy interface is: `169.254.2.1`, the interface name is: `yurthub-dummy0`
- usage for components on edge node:
to access kube-apiserver through yurthub …
> [feature]: add dummy network interface for yurthub

- config/setup/yurt-controller-manager.yaml
- config/yaml-template/yurt-controller-manager.yaml
- pkg/yurtctl/constants/constants.go
It solves the problem that the cloud node configuration taint causes the pod of yurt controller manage to be unable to schedule to the cloud node
fixes #298
> It solves the problem that the cloud node configuration taint causes the pod of yurt controller manage to be unable to schedule to the cloud node

- pkg/yurtctl/cmd/convert/edgenode.go
- pkg/yurtctl/cmd/revert/edgenode.go
- pkg/yurtctl/util/edgenode/util.go
fix bugs of yurtctl:
- The command in servant-convert/revert-job did not run successfully, but the job status is success
- Use of the flag `--kubeadm-conf-path`
NOTE: After yurtctl is modified, you need to recompile the yurtctl servant image and use it yourself, because the default image of servant-convert/revert-job is out of date after modify it.
> fix bugs of yurctl 

- config/setup/yurt-tunnel-server.yaml
- config/yaml-template/yurt-tunnel-server.yaml
- pkg/yurtctl/cmd/revert/revert.go
- pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go
- pkg/yurtctl/util/edgenode/util.go
- pkg/yurttunnel/pki/certmanager/certmanager.go
- pkg/yurttunnel/server/serveraddr/addr.go
- pkg/yurttunnel/server/serveraddr/addr_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
1. update clusterrole of yurt-tunnel-server in order to support dns mode
2. add x-tunnel-server-internal-svc info into yurt-tunnel-server certificate
3. fix kubeconfig path error for `yurtctl covert edgenode` cmd
Fixes #
/assign @Fei-Guo
/assign @Peeknut 
```release-note
```
> bugfix: update clusterrole and certificate for yurt-tunnel-server and fix kubeconfig path error for yurtctl

- pkg/yurtctl/cmd/convert/convert.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
This is the solution
no cloud node is specified when executing the yurtctl convert command, but the program does not report an error.
Fixes #335 
```release-note
```
> Add parameter verification of specified cloud node.

- pkg/yurtctl/cmd/convert/convert.go
- pkg/yurtctl/constants/yurt-app-manager-tmpl.go
- pkg/yurtctl/util/kubernetes/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind feature
New function development.
Fixes #340 
```release-note
```
> New function development -- yurtctl adds parameter enable app manager to control automatic deployment of yurtappmanager.

- pkg/yurttunnel/pki/certmanager/certmanager.go
- pkg/yurttunnel/pki/certmanager/store/filestore_wrapper.go
/kind bug
Fix the bug that tunnel-agent/tunnel-server crashes when the local certificate can not be loaded correctly
Fixes #377
```release-note
Fix the bug that tunnel-agent/tunnel-server crashes when the local certificate can not be loaded correctly
```
> Fix the bug that tunnel-agent/tunnel-server crashes when the local certificate can not be loaded correctly

- docs/proposals/20210628-nodepool-ingress-support.md
Signed-off-by: zhenggu1 <zhengguang.zhang@intel.com>
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Fixes #
```release-note
```
> proposal: add ingress feature support to nodepool

- README.md
- README.zh.md
- pkg/yurttunnel/server/interceptor.go
Use `sync.Pool` to reduce memory allocation and avoid GC pressure. 
```release-note
```
> Add sync.Pool to cache *bufio.Reader in tunnel server

- docs/tutorial/yurtctl.md
1. Add NodeSelector for multi-node cluster.
2. Shorten pod eviction time from default 5 minutes to 5 seconds to accelerate autonomy test.
> Docs: better autonomy test tutorial

- cmd/yurthub/app/config/config.go
- cmd/yurthub/app/options/options.go
- cmd/yurthub/app/start.go
- pkg/yurtctl/util/edgenode/common.go
- pkg/yurthub/certificate/hubself/cert_mgr.go
- pkg/yurthub/certificate/hubself/fake_cert_mgr.go
- pkg/yurthub/certificate/interfaces/interfaces.go
- pkg/yurthub/certificate/kubelet/cert_mgr.go
- pkg/yurthub/certificate/kubelet/cert_mgr_test.go
- pkg/yurthub/gc/gc.go
- pkg/yurthub/kubernetes/rest/config.go
- pkg/yurthub/kubernetes/rest/config_test.go
- pkg/yurthub/transport/transport.go
- pkg/yurthub/util/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
1. Fix the bug reported by #348
2. Decouple the GetRestConfig function from certManager
Fixes #348 
```release-note
None
```
> fix the error when cert-mgr-mode set to kubelet

- cmd/yurt-tunnel-agent/app/start.go
- cmd/yurt-tunnel-server/app/options/options.go
- pkg/yurttunnel/pki/certmanager/csrapprover.go
/kind bug
1. before this pr, all csr(pending/approved/other status) will try enqueue every 10 seconds, but the default queue is only 10qps, 100 bucket. tunnel-server is not able to approve csr when large number of csr comes.
2. the connection is not available before certificate signed, so tunnel-agent must wait for the certificate signed
None
```release-note
None
```
> improve tunnel availability

- cmd/yurthub/app/config/config.go
- cmd/yurthub/app/options/options.go
- cmd/yurthub/app/start.go
- go.mod
- go.sum
- pkg/yurthub/cachemanager/cache_agent.go
- pkg/yurthub/cachemanager/cache_manager.go
- pkg/yurthub/filter/approver.go
- pkg/yurthub/filter/chain.go
- pkg/yurthub/filter/filter.go
- pkg/yurthub/filter/initializer/initializer.go
- pkg/yurthub/filter/interfaces.go
- pkg/yurthub/filter/masterservice/filter.go
- pkg/yurthub/filter/masterservice/handler.go
- pkg/yurthub/filter/servicetopology/filter.go
- pkg/yurthub/filter/servicetopology/handler.go
- pkg/yurthub/filter/util/utils.go
- pkg/yurthub/kubernetes/serializer/serializer.go
- pkg/yurthub/proxy/proxy.go
- pkg/yurthub/proxy/remote/loadbalancer.go
- pkg/yurthub/proxy/remote/remote.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind feature
add data filtering framework
1. support endpointslice filter for keeping service traffic in-bound of nodePool
2. support master service mutation for pod use InClusterConfig access kube-apiserver
you can check the proposal here: https://github.com/openyurtio/openyurt/pull/388
Fixes #
/assign @Fei-Guo 
```release-note
```
> feature: add data filtering framework

- pkg/yurthub/storage/disk/storage.go
- pkg/yurthub/storage/disk/storage_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
fix the deadlock of storage when the keys have the same prefix string. 
Fixes #
```release-note
```
> bugfix: the same prefix key lock error

- pkg/yurthub/metrics/metrics.go
- pkg/yurthub/proxy/local/local.go
- pkg/yurthub/proxy/remote/remote.go
- pkg/yurthub/util/util.go
- pkg/yurthub/util/util_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind feature
Add traffic metrics in order to collect the traffic statics from cloud to edge, so we can easily determine which component consumes the most traffic for which type of request.
Fixes #
```release-note
```
> feature: add traffic(from cloud to edge) collector metrics for yurthub

- 20210722-yurtcluster-operator.md
Signed-off-by: nunu <shaoqiang.chen@intel.com>
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Fixes #
```release-note
```
> Proposal: OpenYurt Convertor Operator for converting K8S to OpenYurt

- docs/tutorial/yurtctl.md
- pkg/yurtctl/cmd/convert/convert.go
- pkg/yurtctl/cmd/convert/edgenode.go
- pkg/yurtctl/cmd/revert/edgenode.go
- pkg/yurtctl/cmd/revert/revert.go
- pkg/yurtctl/constants/constants.go
- pkg/yurtctl/util/kubernetes/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
If kube-controlller-manager is deployed as a static pod, `yurtctl convert` turn off `nodelifecycle controller` by modifying `kube-controller-manager.yaml` instead of deleting clusterrolebinding `system:controller:node-controller`. So OpenYurt cluster created by yurtctl can run normally and support the high availability of `kube-controller-manager`.
Fixes #391
```release-note
```
> Yurtctl modify  kube-controllersetting to close the nodelifecycle-controller

- cmd/yurt-controller-manager/app/controllermanager.go
- cmd/yurt-controller-manager/app/core.go
- cmd/yurthub/app/config/config.go
- cmd/yurthub/app/options/options.go
- cmd/yurthub/app/start.go
- pkg/controller/certificates/csrapprover.go
- pkg/yurthub/network/network.go
- pkg/yurthub/pki/certmanager/certmanager.go
- pkg/yurthub/pki/pki.go
- pkg/yurthub/server/server.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind feature
Fixes #361 
```release-note
```
> change yurthub's protocol from http to https

- cmd/yurthub/app/config/config.go
- cmd/yurthub/app/start.go
- pkg/yurthub/cachemanager/cache_agent_test.go
- pkg/yurthub/cachemanager/cache_manager.go
- pkg/yurthub/cachemanager/cache_manager_test.go
- pkg/yurthub/kubernetes/meta/restmapper.go
- pkg/yurthub/kubernetes/meta/restmapper_test.go
- pkg/yurthub/kubernetes/serializer/serializer.go
- pkg/yurthub/proxy/local/local.go
- pkg/yurthub/proxy/local/local_test.go
- pkg/yurthub/proxy/remote/remote.go
- pkg/yurthub/storage/disk/storage.go
- pkg/yurthub/storage/disk/storage_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
1. Add DynamicRESTMapper to store GVK and GVR mappings for non-built-in resources, while providing dynamic update function.
2. Fix error: when the cloud and edge are disconnected, and a List request is made for a registered CR, if the number of this custom resource is zero, edge return the wrong message.
3. Add unit tests to verify new feature
Fixes #325 
```release-note
```
> bugfix: fix querying local empty list error

- cmd/yurt-tunnel-server/app/start.go
- cmd/yurt-tunnel-server/server.go
- pkg/yurttunnel/iptables/iptables.go
- pkg/yurttunnel/iptables/iptables_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
After `yurtctl revert` or delete deployment ` yurt-tunnel-server`, the iptables rules created by `yurt-tunnel-server` still exist and have not been deleted. So the request `kubectl exec/logs` cannot be sent correctly.
Fixes #337
The  ` yurt-tunnel-server`  image needs to be recompiled locally and used during testing.
> Add yurt-tunnel-server graceful shut down

- config/setup/yurt-controller-manager.yaml
- config/yaml-template/yurt-controller-manager.yaml
- pkg/yurtctl/constants/constants.go
/kind bug
Followup #386: update the ClusterRole for yurt-controller-manager
Fix the following errors:
```sh
yurtcontroller-manager version: projectinfo.Info{GitVersion:"v0.4.0", GitCommit:"131c435", BuildDate:"2021-08-06T05:44:31Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
W0806 07:24:33.917457       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0806 07:24:33.921118       1 controllermanager.go:141] Version: v0.0.0-master+$Format:%h$
I0806 07:24:33.921856       1 leaderelection.go:242] attempting to acquire leader lease  kube-system/yurt-controller-manager...
I0806 07:24:33.941093       1 leaderelection.go:252] successfully acquired lease kube-system/yurt-controller-manager
I0806 …
```
> Followup #386: update the ClusterRole for yurt-controller-manager

- cmd/yurthub/app/start.go
- pkg/controller/certificates/csrapprover.go
- pkg/yurthub/certificate/pki.go
- pkg/yurthub/certificate/server/certmanager.go
- pkg/yurthub/server/server.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
1. If pods access dummy ip address of yurthub https server, pods get the error info: x509: certificate is valid for 127.0.0.1, not 169.254.2.1, so we need to add ip address of dummy network interface into server certificate of yurthub.
2. Move server certificate dir and files under `pkg/yurthub/certificate` dir,  so all certificates(include both server and client certificate) can be managed under same dir. 
Fixes #
```release-note
```
> fix pod access yurthub https endpoint error

- pkg/yurthub/proxy/remote/remote.go
- pkg/yurthub/transport/transport.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
- background:
when pods on edge nodes access kube-apiserver through yurthub, yurthub will use client certificate to proxy requests to kube-apiserver. so in order to get authorization by kube-apiserver, we need to add rbac setting of pods to client certificate of yurthub(system:nodes group).
- enhancement:
In order to prevent add additional rbac setting to `system:nodes` group, we use the original bearer token to proxy request to kube-apiserver instead of using …
> enhancement: proxy request with bearer token in header without client certificate

- config/setup/yurt-tunnel-server.yaml
- config/yaml-template/yurt-tunnel-server.yaml
- pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go
- pkg/yurttunnel/constants/constants.go
- pkg/yurttunnel/handlerwrapper/localhostproxy/handler.go
- pkg/yurttunnel/handlerwrapper/localhostproxy/handler_test.go
- pkg/yurttunnel/handlerwrapper/wraphandler/wraphandler.go
- pkg/yurttunnel/util/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind feature
1.  when components(like prometheus) on cloud nodes usually use `NodeIP:Port` to collect component(like yurthub) metrics on edge node, but edge components listen on `127.0.0.1:Port` instead of `NodeIP:Port` for security consideration.  so we need to add this feature to support proxy cloud requests to localhost endpoint of edge nodes.
2. The way of enable this feature:  
- user can configure the `yurt-tunnel-server-cfg` configmap, and add specified tcp ports in …
> feature: support forward cloud requests to edge node's localhost endpoint

- pkg/yurthub/cachemanager/cache_manager.go
- pkg/yurthub/filter/filter.go
Signed-off-by: SataQiu <shidaqiu2018@gmail.com>
/kind bug
```
// The copy built-in function copies elements from a source slice into a
// destination slice. (As a special case, it also will copy bytes from a
// string to a slice of bytes.) The source and destination may overlap. Copy
// returns the number of elements copied, which will be the minimum of
// len(src) and len(dst).
func copy(dst, src []Type) int
```
`func (dr *filterReadCloser) Read(p []byte) (int, error)` will return incomplete data when the data size is larger than the default size of `p` (32768). 
The `Read` function can be called multi times, we should just use `dr.data.Read(p)` instead of `copy`.
Fixes #426 #432
```release-note
bugfix: fix incomplete data copy of resource filter
```
> bugfix: fix incomplete data copy of resource filter

- pkg/yurthub/proxy/proxy.go
Signed-off-by: SataQiu <shidaqiu2018@gmail.com>
/kind bug
`MaxInFlightLimit` wants to show the client component, but the client component info is available only after `RequestClientComponent` chain executed.
https://github.com/openyurtio/openyurt/blob/b7bef6d0f1268b98826f840a5aaceb585516b394/pkg/yurthub/proxy/util/util.go#L235
https://github.com/openyurtio/openyurt/blob/b7bef6d0f1268b98826f840a5aaceb585516b394/pkg/yurthub/util/util.go#L131
This PR move `MaxInFlightLimit` handler chain after `RequestClientComponent`.
Fixes #
```release-note
bugfix: move 'MaxInFlightLimit' handler chain after 'RequestClientComponent'
```
> bugfix: move MaxInFlightLimit handler chain after RequestClientComponent

- cmd/yurthub/app/config/config.go
- pkg/yurthub/filter/discardcloudservice/filter.go
- pkg/yurthub/filter/discardcloudservice/handler.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind feature
- background:
Kube-proxy(ipvs mode) will configure ipvs rules for `LoadBalancer` service on the edge node, so if pods(like yurt-tunnel-agent) on edge nodes use ingress ip of `LoadBalancer` service to access the cloud pods(like yurt-tunnel-server),  the connection will be refused for ipvs rule will dnat the ingress ip to pod ip on the edge node.
And  end user have come across the same error that yurt-tunnel-agent failed to use ingress ip of `x-tunnel-server-svc` …
> feature: add discard cloud service filter in yurthub

- cmd/yurt-tunnel-server/app/start.go
- config/setup/yurt-tunnel-server.yaml
- config/yaml-template/yurt-tunnel-server.yaml
- pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go
- pkg/yurttunnel/dns/dns.go
- pkg/yurttunnel/dns/dns_test.go
- pkg/yurttunnel/iptables/iptables.go
- pkg/yurttunnel/iptables/iptables_test.go
- pkg/yurttunnel/util/util.go
- pkg/yurttunnel/util/util_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind feature
1. Yurt-tunnel can proxy https request from cloud to edge nodes, so components(like prometheus) on the cloud nodes can access the https service(like node-exporter) on the edge node through yurt-tunnel.
2. Beside of `10250` and `10255` Ports, In order to support more tcp ports of https and http service on edge nodes. use can configure the `yurt-tunnel-server-cfg` configmap, and add specified tcp ports in `https-proxy-ports` and `http-proxy-port` field of configmap. …
> feature: support proxy https request from cloud to edge through yurt-tunnel

- pkg/yurthub/gc/gc.go
- pkg/yurthub/kubernetes/rest/config.go
- pkg/yurthub/kubernetes/rest/config_test.go
- pkg/yurthub/server/server.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
- bug:
if yurthub re-startup when network between cloud and edge disconnected, a panic will happen for preparing server tls config. and the panic like as following:
- reason:
yurthub will use healthy server address and certificate under `/var/lib/yurthub/pki` dir to create `rest.Config` for https server. the code is here: https://github.com/openyurtio/openyurt/blob/master/pkg/yurthub/kubernetes/rest/config.go#L83-113
and when cloud-edge network breaks down, healthy …
> bugfix: prepare yurthub server tls config panic

- docs/tutorial/yurtctl.md
two points here:
1.  update description about convert.
this update is for better understating.
the command below is to convert with one node as a cloud node. same as the logic thought.
2. add a note, how to use "," to add more nodes for --cloud-nodes params
this is useful when we deploy our openYurt cluster.
Fixes #
```release-note
NONE
```
> Docs: add more nodes for --cloud-nodes

- cmd/yurthub/app/options/options.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
As discussed in https://github.com/openyurtio/openyurt/issues/358, It's reasonable to make kube-proxy or other addons on edge nodes access kube-apiserver through yurthub. so we change `AccessServerThroughHub` default value to true.
Fixes #
```release-note
```
> enhancement: enable kube-proxy and addons access kube-apiserver through yurthub

- cmd/yurthub/app/start.go
- config/setup/yurthub-cfg.yaml
- pkg/yurthub/cachemanager/cache_agent.go
- pkg/yurthub/cachemanager/cache_agent_test.go
- pkg/yurthub/cachemanager/cache_manager.go
- pkg/yurthub/cachemanager/cache_manager_test.go
- pkg/yurthub/proxy/local/local_test.go
- pkg/yurthub/util/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind feature
- background:
At present, only response for requests from fixed user agents(like kube-proxy, flanneld, coredns, kubelet, yurthub, yurt-tunnel-agent) can be cached in local disk by yurthub. if user's pod access kube-apiserver through yurthub, the response can not be cached on local disk for user agents can not be recognized.
- solution:
1. It's not good idea to enable cache all response for requests through yurthub, because some clients only want to access …
> enhancement: add configmap to configure user agents for specify response cache.

- OWNERS
@qclc 
openyurtio
@rambohe-ch 
https://github.com/openyurtio/openyurt/pull/225
https://github.com/openyurtio/openyurt/pull/244
https://github.com/openyurtio/openyurt/pull/326
https://github.com/openyurtio/openyurt/pull/359
https://github.com/openyurtio/openyurt/pull/369
https://github.com/openyurtio/yurt-device-controller/pull/1
https://github.com/openyurtio/yurt-device-controller/pull/2
https://github.com/openyurtio/yurt-device-controller/pull/4
- Issues :
https://github.com/openyurtio/openyurt/issues/162
https://github.com/openyurtio/openyurt/issues/281
https://github.com/openyurtio/openyurt/issues/325
> Add qclc as a reviewer of openyurt

- cmd/yurt-tunnel-server/server.go
/kind bug
bugfix: use buffered channel for signal notifications
When I upgrade to go 1.17, executing `make` will cause an error:
```sh
go version go1.17.1 darwin/amd64
go fmt ./pkg/... ./cmd/...
pkg/yurthub/network/dummyif_test.go
pkg/yurthub/network/dummyif_unsupported.go
go vet ./pkg/... ./cmd/...
cmd/yurt-tunnel-server/server.go:39:2: misuse of unbuffered os.Signal channel as argument to signal.Notify
make: *** [vet] Error 2
```
FYI: https://github.com/golang/go/blob/ee91bb83198f61aa8f26c3100ca7558d302c0a98/src/os/signal/example_test.go#L14-L17
Fixes #
```release-note
NONE
```
> bugfix: use buffered channel for signal notifications

- pkg/profile/profile_test.go
- pkg/yurttunnel/dns/util.go
- pkg/yurttunnel/dns/util_test.go
- pkg/yurttunnel/handlerwrapper/tracerequest/tracereq_test.go
- pkg/yurttunnel/server/interceptor_test.go
- pkg/yurttunnel/server/serveraddr/addr_test.go
- pkg/yurttunnel/util/util_test.go
> /kind bug
improve the reliability of yurt-tunnel.
Fixes #416  
NONE
> add some unit tests for yurt tunnel

- pkg/yurthub/cachemanager/cache_agent.go
- pkg/yurthub/cachemanager/cache_agent_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
if user agent is an empty string, we need to filter it to avoid cache failure.
Fixes #
```release-note
```
> bugfix: exclude the effect of empty strings for agents

- pkg/yurttunnel/pki/certmanager/certmanager.go
- pkg/yurttunnel/pki/pki.go
- test/e2e/yurt/yurt.go
We need to specify the usage of certificates of yurt-tunnel components clearly.
Fixes #410
> perf: improve the usage of certificates

- cmd/yurthub/app/config/config.go
- cmd/yurthub/app/options/options.go
- cmd/yurthub/app/start.go
- pkg/yurthub/filter/constant.go
- pkg/yurthub/proxy/proxy.go
- pkg/yurthub/proxy/remote/remote.go
- pkg/yurthub/util/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind feature
When YurtHub is deployed on cloud side, some features such as local disk cache, GC manager and `discardcloudservice` filter should be disabled. We need this option to specify where yurthub is working.
Fixes #476
```release-note
```
> feature: add --working-mode flag for yurthub

- .github/workflows/ci.yaml
- hack/make-rules/build-e2e.sh
- hack/make-rules/check_license.sh
- hack/make-rules/generate_client.sh
- pkg/controller/apis/config/types.go
- pkg/yurtctl/constants/yurt-app-manager-tmpl.go
- pkg/yurthub/healthchecker/node_lease_test.go
- pkg/yurthub/kubernetes/rest/config_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind feature
1. add hack script to check newly created files that license header missed or not.
2. revise github actions to include this hack script.
Fixes #478 
I am not sure where the github action should be, but I think it should be in front. Because if the license header missed in files, the following test steps need not to be performed.
```release-note
NONE
```
> feature: add check-license-header script to github action

- pkg/yurtctl/cmd/revert/revert.go
- pkg/yurtctl/util/edgenode/common.go
- pkg/yurtctl/util/kubernetes/apply_addons.go
> /kind bug
clean all resource, when do revert
Fixes #489
```release-note
```
> add DeleteYurthubSetting to revert

- cmd/yurthub/app/config/config.go
- cmd/yurthub/app/options/options.go
- pkg/yurthub/healthchecker/fake_checker.go
- pkg/yurthub/healthchecker/health_checker.go
- pkg/yurthub/proxy/proxy.go
/kind bug
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
yurthub: stop renew node lease when kubelet's heartbeat is stopped
Fixes #420
/assign @rambohe-ch @Fei-Guo 
```release-note
yurthub: improve the healthy check mechanism when kubelet's heartbeat stopped
```
> yurthub: stop renew node lease when kubelet's heartbeat is stopped

- pkg/yurtctl/cmd/convert/convert.go
- pkg/yurtctl/cmd/yurtinit/init.go
- pkg/yurtctl/cmd/yurtinit/phases/install_yurt_addons.go
- pkg/yurtctl/cmd/yurtinit/phases/types.go
- pkg/yurtctl/constants/yurt-tunnel-agent-tmpl.go
- pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go
- pkg/yurtctl/util/kubernetes/apply_addons.go
add --yurt-tunnel-server-address  to yurtctl convert
Fixes #461 
set svc x-tunnel-server-svc a fixed host port : 31008
> Add tunnel server address

- config/setup/yurt-tunnel-server.yaml
- config/yaml-template/yurt-tunnel-server.yaml
- pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go
> add create to yurt-tunnel-server ClusterRole

- pkg/yurttunnel/pki/certmanager/certmanager.go
/kind bug
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
The key usage `certificates.UsageClientAuth` is missing from `yurt-tunnel-server` certmanager.
Fixes #508
/assign @SataQiu @rambohe-ch 
```release-note
```
> bugfix: add client auth key usage to yurt-tunnel-server certmanager

- docs/enhancements/20210729-uniteddaemonset.md
- docs/enhancements/20210729-yurtappdaemon.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind feature
Fixes #
```release-note
```
> Proposal: YurtAppDaemon

- .github/workflows/ci.yaml
- Makefile
- hack/kind-config-template.yaml
- hack/lib/release-images.sh
- hack/local_up_openyurt.sh
- hack/run-e2e-tests.sh
1. Integrate e2e test into github action. Then, each pr after this commit should pass e2e tests at `test/e2e` to check its correctness.
2. Also, this pr provides a local up shell located at `hack/local_up_openyurt.sh`, with which we can quickly setup an openyurt cluster at local host with `kind`.
Fixes #467
```release-note
None
```
Currently, this shell skips yurt-tunnel e2e test at `test/e2e/yurttunnel`, because it always failed at this test. We should find out the reason.
> e2e: add e2e test into github action

- pkg/yurtctl/util/kubernetes/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
When converting cluster with `yurtctl convert`, `yurtctl` will try to get the join-token for yurthub from Kubernetes secrets. 
We should ensure that the token can be used as a bootstrap token, otherwise the yurthub cannot startup.
For example, in my setup, `yurtctl` select a wrong token(the first one), so it can not get the certificate correctly.
```
[root@master-1 ~]# kubeadm token list
TOKEN                     TTL         EXPIRES                     USAGES …
```
> bugfix(yurtctl): ensure the join token of yurthub has right usages and groups

- pkg/yurtctl/cmd/revert/revert.go
- pkg/yurtctl/lock/lock.go
- pkg/yurttunnel/constants/constants.go
- pkg/yurttunnel/dns/dns.go
- pkg/yurttunnel/dns/handler.go
- pkg/yurttunnel/dns/util.go
/kind bug
Delete the yurt-tunnel-nodes configmap and yurtctl-lock when revert the whole openyurt cluster back to k8s cluster.
Fixes #531 
I'll add the test log in the following comment.
> delete yurtctl-lock and yurt-tunnel-nodes when revert the whole cluster

- pkg/yurthub/certificate/server/certmanager.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
1. To reduce the key usage scope of yurthub https server certificate
2. `any` is not standard  key usage of certificate, you can reference link here: https://help.hcltechsw.com/domino/11.0.0/conf_keyusageextensionsandextendedkeyusage_r.html, tls handshake for any key usage maybe different in different languages, for example: golang and ruby. so we need to define the key usage explicitly.
Fixes #
```release-note
```
> enhancement: revise key usage of yurthub server certificate

- pkg/yurthub/network/iptables.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Iptables rules are not requirement for clients(like kubelet, kube-proxy etc.) access yurthub, we can skip the iptables ensure error and continue to ensure remained iptables rules.
Fixes #
```release-note
```
> enhancement: skip ensure iptables rule error for yurthub

- pkg/yurtctl/cmd/join/phases/join-edge-node.go
> /kind bug
``yurtctl join  --node-type=edge-node`` doesn't work because the working_mode variable is missing.
Fixes #
/assign @huangyuqi
> inject working_mode

- pkg/yurtctl/cmd/revert/revert.go
- pkg/yurtctl/util/kubernetes/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind feature
Automatically delete the yurtappmanager function.
Fixes #392 
```release-note
```
> Yurtctl revert adds the function of deleting yurt app manager

- pkg/yurthub/proxy/util/util.go
- pkg/yurthub/proxy/util/util_test.go
> /kind bug
When using kubectl exec/attach command after access Yurthub, yurthub will return error: no accept content type for request: kubectl create pods: /api/v1/namespaces/xxxx/pods/xxxx/attach?container=xxxx&stderr=true&stdout=true
```
root@c-8cc95a:/# kubectl exec -it -n ingress-nginx       nginx-ingress-controller-p7m5t env
Error from server (BadRequest): no accept content type is set.
```
```
I1105 07:58:11.199787       1 util.go:232] start proxying: get /api/v1/namespaces/ingress-nginx/pods/nginx-ingress-controller-mlrmz, in flight requests: 26
I1105 07:58:11.199904       1 loadbalancer.go:186] picked backend https://127.0.0.1:6443 by rr algorithm for request kubectl get pods: /api/v1/namespaces/ingress-nginx/pods/nginx-ingress-controller-mlrmz
I1105 07:58:11.199923       1 …
```
> bugfix post header accept error

- pkg/yurtctl/util/kubernetes/util.go
…D resource error
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
Yurtappmanager does not use the method of deleting crd resources when crd is not deployed.
Fixes #557 
```release-note
```
> When yurtctl revert executes yurtappmanager to delete automatically, no crd resource error is reported.

- pkg/yurthub/cachemanager/cache_agent_test.go
- pkg/yurthub/cachemanager/cache_manager.go
- pkg/yurthub/cachemanager/cache_manager_test.go
- pkg/yurthub/cachemanager/storage_wrapper.go
- pkg/yurthub/cachemanager/storage_wrapper_test.go
- pkg/yurthub/certificate/certificate.go
- pkg/yurthub/certificate/hubself/cert_mgr.go
- pkg/yurthub/certificate/hubself/fake_cert_mgr.go
- pkg/yurthub/certificate/interfaces/interfaces.go
- pkg/yurthub/certificate/kubelet/cert_mgr.go
- pkg/yurthub/certificate/server/certmanager.go
- pkg/yurthub/gc/gc.go
- pkg/yurthub/metrics/metrics.go
- pkg/yurthub/transport/transport.go
…pkg/yurthub-first
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
The order of the go file import package is not standardized.
Fixes #587 
```release-note
```
> The import package sort adjustment in the go file. 

- cmd/yurt-tunnel-server/app/start.go
- pkg/yurttunnel/dns/dns.go
- pkg/yurttunnel/informers/serverinformer.go
- pkg/yurttunnel/pki/certmanager/certmanager.go
/kind design
The informers used by tunnel server is created by its component alone. This may cause the misuse of informers in the future. So i separate the creation of informers and tunnel server registers informers it need at the beginning of its start.
Fixes #
```release-note
no
```
> Refactor: separate the creation of informers from tunnel server component

- MAINTAINERS.md
@SataQiu
openyurtio
@rambohe-ch 
#518 
#507 
#482 
#471 
#468 
#452 
#451 
#429 
#406 
#378 
#294 
#290 
#287 
#283 
#282 
#270 
#202 
- Issues :
#526 
#524 
#508 
#432 
#426 
#377 
I actively use `OpenYurt` in our product, contribute `OpenYurt` to solve the problems encountered in the process of use. 
I am the main owner of the `openyurtio/yurtcluster-operator` project, and I am pushing to create the `OpenYurt` cluster in a declarative way.
> Add SataQiu as a maintainer of OpenYurt

- Makefile
- hack/lib/release-images.sh
- hack/make-rules/push-images.sh
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
after running
REPO="xxxx" make release
make push
would allow users to push the images generated to their own image ${REPO}.
Fixes #
```release-note
NONE
```
> add make push for pushing images generated during make release

- cmd/yurthub/app/config/config.go
- cmd/yurthub/app/start.go
- pkg/yurthub/cachemanager/cache_agent.go
- pkg/yurthub/cachemanager/cache_agent_test.go
- pkg/yurthub/cachemanager/cache_manager.go
- pkg/yurthub/filter/initializer/initializer.go
- pkg/yurthub/filter/interfaces.go
- pkg/yurthub/filter/masterservice/filter.go
- pkg/yurthub/filter/servicetopology/filter.go
- pkg/yurthub/filter/servicetopology/handler.go
- pkg/yurthub/proxy/proxy.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
1. service topology filter can not work when hub agent work on cloud mode
--> solution: service topology filter will list/watch node from kube-apsierver if working mode is cloud
2. optimize shared informers register. extract all of informers register and
make a common function named registerInformers
Fixes #600 
/assign @DrmagicE 
```release-note
```
> bugfix: service topology filter can not work when hub agent work on cloud mode

- pkg/yurthub/proxy/local/local.go
- pkg/yurthub/proxy/local/local_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
when user deletes pod gracefully from cloud,  kubelet need to remove pod from etcd forcefully after cleaning up pods info(like pod volume, network, containers etc.) on edge node. so yurthub need to forward `delete pod request` carefully as following:
- If cloud-edge network disconnected, yurthub should reject delete pod request, so kubelet can retry to delete pod in next interval
- when cloud-edge network recovered,  `delete pod request` will be forwarded to …
> bugfix: reject delete pod request by yurthub when cloud-edge network disconnected

- pkg/yurtctl/util/edgenode/util.go
I think const is better than a string
Fixes #
NONE
-->
```release-note
```
> use const instead the string

- pkg/yurthub/proxy/remote/remote.go
/kind bug
We should treate the log of reverseProxy.ErrorHandler as error log. It will help us to find the problem of yurthub, such as x509 error during bootstrap. 
Fixes #
```release-note
```
> print error log when remote proxy is trapped into errorHandler

- Makefile
- hack/lib/common.sh
- hack/lib/release-images.sh
- hack/lib/release-manifest.sh
- hack/make-rules/push-manifest.sh
- hack/make-rules/release-manifest.sh
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Add `make manifest` and `make push_manifest` in Makefile to support multi-arch docker manifest creation.
After the corresponding multi-arch images have been pushed to the registry, users can use `make manifest && make push_manifest` to create and push the manifest.
Fixes #
```release-note
```
> add support for docker manifest

- hack/lib/init.sh
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
So far, we need to update GIT_VERSION in the init.sh manually when updating the new version of OpenYurt. With this pr, we can do it automatically. Here's the logs of `git describe --abbrev=0`.
```bash
ys3@ys-desktop:~/Github/openyurt$ git describe --abbrev=0
v0.5.0
```
Fixes #
```release-note
```
> detect the openyurt version automatically

- test/e2e/common/ns/ns.go
- test/e2e/common/pod/pod.go
- test/e2e/e2e.go
- test/e2e/e2e_test.go
- test/e2e/util/expect.go
- test/e2e/util/ginkgowrapper/wrapper.go
- test/e2e/util/util.go
- test/e2e/yurt/yurt.go
- test/e2e/yurtconfig/yurtconfig.go
- test/e2e/yurthub/yurthub.go
- test/e2e/yurttunnel/yurttunnel.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
remove k8s.io/kubernetes dependency from e2e test.
Fixes #551 
```release-note
```
> remove k8s.io/kubernetes dependency from e2e test

- pkg/yurtctl/cmd/revert/cloudnode.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
When we use ` _output/bin/yurtctl revert cloudnode -h `,there is a bug in the information:
Fixes #
```release-note
```
> Notebug:change -e to -c

- cmd/yurthub/app/options/options.go
- cmd/yurthub/app/start.go
- pkg/yurthub/certificate/hubself/cert_mgr.go
- pkg/yurthub/certificate/pki.go
- pkg/yurthub/certificate/server/certmanager.go
- pkg/yurthub/server/server.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
Restore the original certificate mode of yurthub, which is, server and client certificates are managed separately. Avoid certificate verification errors when some components that have strict requirements on the use of certificates connect to yurthub. (for example, fluend)
Fixes #
/assign @rambohe-ch please take review
```release-note
```
> split the yurthub certificate into server and client certificates

- cmd/yurt-controller-manager/app/options/generic.go
- cmd/yurt-controller-manager/app/options/options.go
- pkg/controller/apis/config/types.go
- pkg/controller/kubernetes/controller/apis/config/types.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
- Remove "k8s.io/kubernetes/pkg/controller/apis/config" dependency for yurt-controller-manager. 
- The `k8s.io/controller-manager` only supports version 1.20.x or later. The current policy is to cache the used `k8s.io/kubernetes/pkg/controller/apis/config/types.go` file. After openYurt is upgraded to version 1.20.x, I will submit a PR to replace `k8s.io/kubernetes/pkg/controller` with `k8s.io/controller-manager`.
Fixes #
```release-note
```
> remove "k8s.io/kubernetes/pkg/controller/apis/config" dependency for yurt-controller-manager

- pkg/yurthub/filter/approver_test.go
- pkg/yurthub/filter/discardcloudservice/handler_test.go
- pkg/yurthub/filter/masterservice/handler_test.go
- pkg/yurthub/filter/servicetopology/handler_test.go
/kind good-first-issue
/kind feature
Data filtering framework is an elegant feature of yurthub, but it lacks unit tests.
Fixes #418 
> add unit tests for yurthub data filtering framework

- go.sum
- pkg/yurthub/proxy/remote/remote.go
- pkg/yurthub/proxy/util/util.go
Since APIServer can handle websocket request, yurthub which is serving as a proxy server for kubelet and other components should have the capability of proxying websocket traffic to APIServer.
Fixes #562
```release-note
```
> [enhancement] enable yurthub to handle upgrade request

- docs/tutorial/edge-pod-network.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
The RBAC requirement for patched flannel is missing, which produce "Failed to get node" error. 
```
I1214 03:35:54.782398       1 main.go:402] Found network config - Backend type: vxlan
W1214 03:35:54.782470       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
E1214 03:35:54.799285       1 main.go:673] Failed to get node for backend data: nodes "zj-cache1.js" is forbidden: User …
```
> docs: add RBAC instruction for patched flannel

- pkg/yurthub/proxy/remote/remote.go
- pkg/yurthub/util/connrotation.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
reconstruct transport setting in `RemoteProxy` of yurthub component for preventing race conditions.
1.  add `bearerUpgradeHandler` and existing `upgradeHandler` for `Connection: Upgrade` request.
2. add `RoundTrip()` func for `RemoteProxy` to group transport handler.
Fixes #674 
/assign @DrmagicE 
```release-note
```
> [bugfix] fix transport race conditions in yurthub

- docs/proposals/20210628-nodepool-ingress-support.md
Signed-off-by: zhenggu1 <zhengguang.zhang@intel.com>
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Fixes #
```release-note
```
> ingress: update nodepool ingress proposal

- cmd/yurt-tunnel-agent/app/config/config.go
- cmd/yurt-tunnel-agent/app/options/options.go
- cmd/yurt-tunnel-agent/app/start.go
- cmd/yurt-tunnel-server/app/config/config.go
- cmd/yurt-tunnel-server/app/options/options.go
- cmd/yurt-tunnel-server/app/start.go
- pkg/yurttunnel/pki/certmanager/certmanager.go
/kind good-first-issue
/kind feature
In order to make the certificates of yurt-tunnel components can be saved in any directory that user wants to save.
Fixes #409 
user can use `--cert-dir` parameter to specify the directory of certificate about both yurt tunnel server and agent.
> user can specifies the certificate directory

- .github/workflows/ci.yaml
- .golangci.yaml
- Makefile
- cmd/yurt-controller-manager/controller-manager.go
- cmd/yurt-tunnel-agent/app/config/config.go
- cmd/yurt-tunnel-server/app/config/config.go
- cmd/yurthub/app/config/config.go
- pkg/controller/certificates/csrapprover.go
- pkg/controller/kubernetes/cmd/controller-manager/app/serve.go
- pkg/yurtctl/cmd/convert/convert.go
- pkg/yurtctl/cmd/join/phases/join-edge-node.go
- pkg/yurtctl/util/kubernetes/util.go
- pkg/yurthub/network/dummyif_linux.go
- pkg/yurttunnel/handlerwrapper/localhostproxy/handler.go
- pkg/yurttunnel/server/interceptor.go
- pkg/yurttunnel/server/serveraddr/addr.go
- pkg/yurttunnel/util/util.go
After intergating gci linter into CI workflow, we can check the import package format automatically, including
1. repeated import
2. wrong 3-rd part package import order
3. no empty line before import with comment
More import format to be checked by gci linter can be seen in the [README](https://github.com/daixiang0/gci) of gci repo.
Fixes #
It's recommanded that developer should always run `make lint` at local host before submitting a pr.
Developers can run `make lint` at local host to get more info about lint error if any. There're more details than what github action outputs, including the file name and line number which cause this error.
> [CI Enhancement] Add gci linter check

- Makefile
- hack/make-rules/check_license.sh
- pkg/util/iptables/iptables_linux.go
- pkg/util/iptables/iptables_test.go
- pkg/util/iptables/iptables_unsupported.go
- pkg/util/iptables/monitor_test.go
- pkg/yurthub/network/dummyif_test.go
- pkg/yurthub/network/dummyif_unsupported.go
/kind bug
Fix some bugs when `make lint`:
1. `GOBIN` is defined nowhere, so when we `make lint` with no `golangci-lint` installed, the shell will run `/golangci-lint` and result in error.
2. `golangci-lint` install command bug
3.  gofmt some files to enable `make lint` to support go 1.17 or later version
Since go 1.17, it will transition from `// +build:` to `//go:build` to do conditional compilation. Thus, when `make lint` with go 1.17 or later version, it will end in gofmt error.
More Info: https://go.googlesource.com/proposal/+/master/design/draft-gobuild.md
Fixes #
```release-note
```
> [bug] fix make lint bug

- cmd/yurthub/app/config/config.go
- pkg/yurthub/filter/constant.go
- pkg/yurthub/filter/ingresscontroller/filter.go
- pkg/yurthub/filter/ingresscontroller/handler.go
When users access service through nodepool ingress, ingress controller
will balance the users rquests to the endpoints binding to the service,
the ingress controller in a nodepool should only balance the requests
to endpoints belonging to this nodepool, so the service endpoints need
to be filtered to exclude endpoints from other endpoints.
Note:
Currently we leverage yurthub data filtering framework to achieve the
purpose, which is actually a node level sidecar solution, if a nodepool
level data filtering sidecar is implemented in future, nodepool ingress
data filtering is suggested to switch to that solution.
Signed-off-by: zhenggu1 <zhengguang.zhang@intel.com>
> …
> ingress: add nodepool endpoints filtering for nginx ingress controller

- pkg/yurthub/certificate/hubself/cert_mgr.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
verify existed ca file if any, and do cleanup if necessary (mismatch). This will fix the openyurt convert failure due to stale contents left over in the yurthub root dir (/var/lib/yurthub).
Fixes #
```release-note
NONE
```
> yurthub verify bootstrap ca on start

- pkg/yurttunnel/server/serveraddr/addr.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
when type of service `x-tunnel-server-svc` is LoadBalancer, a panic will happen when yurt-tunnel-server component startups.
Fixes #
```release-note
```
> bugfix: panic happened when x-tunnel-server-svc service type is lb

- pkg/util/certmanager/certmanager.go
- pkg/yurttunnel/handlerwrapper/tracerequest/tracereq.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
if clients on cloud side want to access edge site through yurt-tunnel and these clients can not use dns mode or iptables mode, so yurt-tunnel need to support to proxy requests that access tunnel-server directly with specified edge node in request header.
Fixes #
```release-note
yurt-tunnel will support to proxy requests that access yurt-tunnel directly with specified header. take `curl` command as an example: 
- tunnel-server address: http://10.100.2.2:10264
- …
```
> enhancement: tunnel-server supports to proxy requests that access tunnel-server directly with specified destination

- cmd/yurt-node-servant/convert/convert.go
- cmd/yurt-node-servant/preflight-convert/preflight.go
- cmd/yurt-node-servant/revert/revert.go
- cmd/yurt-tunnel-agent/app/start.go
- cmd/yurt-tunnel-server/app/start.go
- pkg/node-servant/constant.go
- pkg/yurtctl/cmd/clusterinfo/clusterinfo.go
- pkg/yurtctl/cmd/convert/convert.go
- pkg/yurtctl/cmd/markautonomous/markautonomous.go
- pkg/yurtctl/cmd/revert/revert.go
/kind bug
Some commands don't need args. However, currently there's no check when users pass useless args. As an example:
```bash
yurtctl convert edgenode worker-node -c master-node
```
The command above will work without any error report, though we've removed the `edgenode` subcommand at #617.
Fixes #
```release-note
```
> [bug] add NoArgs check for cmds

- pkg/yurtctl/cmd/join/join.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
The`ignoreErrors` (a map) param is not initialized before using so it will cause panic when use`yurtctl join` with the flag`--ignore-preflight-errors` set.
```
panic: assignment to entry in nil map
goroutine 1 [running]:
k8s.io/apimachinery/pkg/util/sets.String.Insert(0x0, 0xc00063fba0, 0x1, 0x1, 0xc0000a5440)
/usr/local/gopath/pkg/mod/k8s.io/apimachinery@v0.20.12-rc.0/pkg/util/sets/string.go:51 +0x78
github.com/openyurtio/openyurt/pkg/yurtctl/cmd/join.newJoinData(0xc000 …
```
> fix: not initialized `sets.String` cause panic

- pkg/yurtctl/cmd/reset/phases/cleanyurtfile.go
- pkg/yurtctl/constants/constants.go
- pkg/yurtctl/util/system/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/enhancement
Use camel case instead of snake case. Keep code unification.
Fixes #
Code Style
```release-note
```
> Use camel case instead of snake case

- pkg/yurtctl/cmd/join/join.go
- pkg/yurtctl/cmd/join/joindata/data.go
- pkg/yurtctl/cmd/join/phases/prepare.go
- pkg/yurtctl/constants/constants.go
- pkg/yurtctl/kubernetes/kubeadm/app/cmd/options/constant.go
- pkg/yurtctl/util/kubernetes/util.go
> /kind bug
/kind feature
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Fixes #
```release-note
```
> support config k8s resource server

- pkg/yurttunnel/trafficforward/iptables/iptables.go
> /kind bug
/kind feature
Conntrack return error when no matching connections are found, openyurt should treat it as normal case.
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Fixes #
Same case in: [kubernetes](https://github.com/kubernetes/kubernetes/blob/d1c45c73c68b8300d3b5c813b268f3da4880e5db/pkg/util/conntrack/conntrack.go#L118:6)
```release-note
```
> Feature: Conntrack no matching connections process

- hack/lib/init.sh
/kind bug
In current master branch of openyurt, the command `git describe --abbrev=0` will initilize `GIT_VERSION` as `v0.5.0`, because it is the latest annotated tag and `v0.6.0` is not an annotated tag. Using the option of `--tags` will make `git describe` get the latest tag even it is unannotated.
The description of `--tags` option in the `git describe -h`: 
```
--tags                use any tag, even unannotated
```
We can check if a tag is an annotated tag through command `git for-each-ref refs/tags`. An unannotated tag will be marked as `commit`.
```
$ git for-each-ref refs/tags
2abb8ad93848adb2a11244373c01bd79d713eb38 commit refs/tags/v0.1.0-beta.1
9d0ae1b2aff825ff5efcde728e143e431cce8246 tag    refs/tags/v0.2.0
1ece6ab01a006b3fd6b6cd0e48dd6f33f95e4ed1 tag    refs/tags/v0.3.0 …
```
> [bugfix] detect unannotated tags when initilizing GIT_VERSION

- pkg/yurthub/cachemanager/cache_manager.go
/kind bug
SelfLink should have the format `/<apigroup>/<apiversion>/<resource>`.
By the way, selflink will be removed soon at [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1164-remove-selflink), and we may have to take it into consideration. The timeline is:
```
2019-07-23: KEP merged.
2019-07-24: KEP move to implementable.
v1.16: Released in Alpha
v1.20: Released in Beta, enabled by default
2022-01-10: KEP updated to target GA in v1.24
```
> [bugfix] fix mistaken selflink in yurthub

- .github/workflows/ci.yaml
> /kind bug
/kind feature
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Process [golint error](https://github.com/golangci/golangci-lint-action/issues/442).
Fixes #
```release-note
```
> upgrade the golint ci step 

- pkg/yurthub/filter/approver.go
> /kind bug
/kind feature
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Clean some code and add configmap delete handler.
Fixes #
```release-note
```
> add configmap delete handler for approver

- pkg/yurthub/cachemanager/cache_agent.go
> /kind bug
/kind feature
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Fixes #
```release-note
```
> support configmap delete

- pkg/node-servant/revert/revert.go
- pkg/yurtctl/cmd/convert/convert.go
- pkg/yurtctl/cmd/convert/options.go
some spelling mistakes, some little detail, it doesn't matter
Fixes #
```release-note
```
> fix spelling mistakes

- pkg/yurthub/filter/manager.go
- pkg/yurthub/proxy/remote/remote.go
- pkg/yurthub/util/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
1. From kubernetes v1.16, kube-apiserver will compress(use gzip) response body when body data size is more than 128KB, the code is here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go#L217-L224
2. filter error or cache error will happen in yurthub component because yurthub can not uncompress response body correctly.
3. so we add a feature to enable gzip read in terms of content-encoding …
> [bugfix] ungzip response by yurthub when response header contains content-encoding=gzip

- hack/lib/release-images.sh
/kind bug
Refer to actions/checkout#760, concept of safe directory was instroduced to git in https://github.blog/2022-04-12-git-security-vulnerability-announced/
Currently e2e-test in github actions fails for it:
```
+++ git rev-parse HEAD
fatal: unsafe repository ('/opt/src' is owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory /opt/src
```
As its output advise, add an exception for dir `/opt/src` before calling `git rev-parese HEAD`.
It seems that other repo under openyurtio also encountered the same problem, like openyurtio/raven-controller-manager#10
```release-note
```
> [bug] fix git safe dir error

- pkg/node-servant/components/kubelet.go
- pkg/node-servant/components/yurthub.go
- pkg/util/certmanager/pki.go
- pkg/yurtctl/cmd/join/phases/joinnode.go
- pkg/yurtctl/cmd/join/phases/postcheck.go
- pkg/yurtctl/cmd/reset/phases/unmount_linux.go
- pkg/yurtctl/cmd/yurtinit/init.go
- pkg/yurtctl/cmd/yurttest/kindinit/init.go
- pkg/yurtctl/cmd/yurttest/kindinit/init_test.go
- pkg/yurtctl/kubernetes/kubeadm/app/phases/kubelet/flags.go
- pkg/yurtctl/kubernetes/kubeadm/app/util/kubeconfig/kubeconfig.go
- pkg/yurtctl/kubernetes/kubeadm/app/util/kubeconfig/kubeconfig_test.go
- pkg/yurtctl/kubernetes/kubeadm/app/util/runtime/runtime_test.go
- pkg/yurtctl/util/edgenode/util.go
- pkg/yurtctl/util/kubernetes/util.go
- pkg/yurtctl/util/system/util.go
- pkg/yurthub/cachemanager/cache_manager_test.go
- pkg/yurthub/certificate/hubself/cert_mgr.go
- pkg/yurthub/filter/discardcloudservice/handler_test.go
- pkg/yurthub/filter/masterservice/handler_test.go
- pkg/yurthub/storage/disk/storage.go
- pkg/yurthub/transport/transport.go
- pkg/yurthub/util/util_test.go
- pkg/yurttunnel/kubernetes/kubernetes.go
- test/integration/yurttunnel_test.go
Signed-off-by: cndoit18 <cndoit18@outlook.com>
/kind good-first-issue
Please see https://golang.org/doc/go1.16#ioutil
```release-note
None
```
> cleanup: io/ioutil

- docs/proposals/20210628-nodepool-ingress-support.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Fixes #
```release-note
```
> ingress: update edge ingress proposal to add enhancements

- cmd/yurthub/app/config/config.go
- cmd/yurthub/app/options/options.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
add a `--enable-node-pool` parameter for yurthub component. by setting  up `--enable-node-pool=false` for disabling nodepools list/watch in filters so `local-up-openyurt.sh` can work when `nodepools` resource doesn't exist in cluster.
Fixes #
/assign @Congrool 
```release-note
```
> add enable-node-pool parameter for yurthub in order to disable nodepools list/watch in filters when testing.

- pkg/node-servant/components/tunnel.go
- pkg/node-servant/revert/revert.go
Sometimes the node has residual certificate files related to tunnels, if we still use this nodes to join the cluster, the invalid certificate cannot create the grpc tunnel, it can make the error for connection closed.
If we don’t open the grpc process debug parameter, it’s hard to find it. So we need to clean the tunnel directory when node-servant do the revert option.
Fixes #
```release-note
```
> 【ADD】update node servant revert step

- cmd/yurt-tunnel-agent/app/options/options.go
- cmd/yurt-tunnel-server/app/config/config.go
- cmd/yurt-tunnel-server/app/options/options.go
- cmd/yurt-tunnel-server/app/start.go
- cmd/yurthub/app/config/config.go
- cmd/yurthub/app/options/options.go
- cmd/yurthub/app/start.go
- pkg/util/certmanager/certmanager.go
- pkg/util/ip/ip.go
- pkg/util/ip/ip_test.go
- pkg/yurthub/network/iptables.go
- pkg/yurthub/server/server.go
- pkg/yurttunnel/handlerwrapper/localhostproxy/handler.go
- pkg/yurttunnel/handlerwrapper/wraphandler/wraphandler.go
- pkg/yurttunnel/server/interceptor.go
- pkg/yurttunnel/server/serveraddr/addr.go
- pkg/yurttunnel/server/serveraddr/addr_test.go
- pkg/yurttunnel/trafficforward/iptables/iptables.go
We need to run openyurt on ipv6 network.
Current works makes yurt-tunnel and yurthub work well on ipv6 network. 
- yurt-tunnel-server
- determine protocol stack according to bind ip format
- set default insecure bind address to ::1 when ipv6
- use ip6tables instead of iptables when ipv6
- yurt-tunnel-agent
- determine protocol stack according to node ip format
- set default meta host to ::1 when ipv6
- yurthub
- use `fd00::2:1` as the default dummy if ip when binding an ipv6 address(yurthub still use 127.0.0.1 as default, set --bind-address to ::1 in ipv6 )
- use ip6tables instead iptables when dummy ip is an ipv6 address
use fd00::2:1 in ipv6, as the counterpart of 169.254.2.1 in ipv4, referring to [node local dns cache ipv6 …
> support ipv6 network

- pkg/yurtctl/cmd/cmd.go
- pkg/yurtctl/cmd/yurttest/kindinit/init.go
- pkg/yurtctl/cmd/yurttest/kindinit/init_test.go
- pkg/yurtctl/cmd/yurttest/kindinit/kindoperator.go
- pkg/yurtctl/cmd/yurttest/kindinit/kindoperator_test.go
- pkg/yurtctl/cmd/yurttest/yurttest.go
Currently, when using `yurtctl test init`, the output message will block at "Start to create cluster with kind" until kind has finished its work.
```
I0602 18:00:28.034602 1088603 init.go:277] Start to install kind
I0602 18:00:28.037127 1088603 init.go:282] Start to prepare kind node image
I0602 18:00:28.039353 1088603 init.go:287] Start to prepare config file for kind
I0602 18:00:28.039530 1088603 init.go:292] Start to create cluster with kind
```
And after kind finishing its work, all processing messages will be printed at stdout at once.
```
I0602 01:56:20.455733   23683 kindoperator.go:97] Creating cluster "openyurt-e2e-test" ...
• Ensuring node image (kindest/node:v1.22.7) 🖼  ...
✓ Ensuring node image …
```
> output processing info to stdout at real time

- go.mod
- go.sum
- pkg/yurtadm/cmd/cmd.go
- pkg/yurtadm/cmd/token/token.go
> /kind bug
/kind feature
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
Fixes https://github.com/openyurtio/openyurt/issues/859
```release-note
```
> support yurtadm token subcommand

- pkg/controller/certificates/csrapprover.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage
/kind bug
only set signer name when not nil in order to prevent panic.
Fixes #
```release-note
```
> bugfix: only set signer name when not nil in order to prevent panic.

- Makefile
/kind clean
We have already had `vet` and `fmt` in [golangci-lint](https://github.com/openyurtio/openyurt/blob/master/.golangci.yaml#L42-L48). So we don't need to run them before running unit tests.
Fixes #
> clean redundant lint in makefile

- .codecov.yml
As we can see in #922 , there're some unforseen mistakes in our unit tests, which may result in coverage rate jitter and cause unexpected and unrelative codecov failure when submiting prs. Thus, we'd better tolerate small coverage rate drop to make contribution process more friendly.
Currently, we set the threshold as 2%. And when coverage rate drop exceeds 2%, this pr will received a failure notification from codecov.
Fixes #
```release-note
```
> allow codecov to tolerate coverage rate jitter

- pkg/yurtadm/cmd/join/join.go
- pkg/yurtadm/util/edgenode/util.go
- pkg/yurtadm/util/edgenode/util_test.go
/kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Currently when joining node with `yurtadm join`, it will get the nodename from `os.hostname()` directly which is problematic when hostname doesn't comply to the k8s object name specification. And this pr make this compatible with k8s.
Fixes #
```release-note
```
> fix: get proper nodename from hostname in yurtadm

- config/setup/yurt-tunnel-dns.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
add a CoreDNS pod named yurt-tunnel-dns for domain name resolution that comes from kube-apiserver, prometheus, metrics-server. so requests to edge nodes can be forwarded to yurt-tunnel-server. 
Fixes #955 
```release-note
```
> add yurt-tunnel-dns yaml

- cmd/yurthub/app/config/config.go
- cmd/yurthub/app/options/options.go
- pkg/util/ip/ip.go
- pkg/util/ip/ip_test.go
Currently, yurthub only have one configurable host `YurtHubHost`  for both yurthub server (metrics related API) & yurthub proxy server. The two servers served for different purposed  have  to share one host which is not resonable.
This PR separate these two, and make them both configurable by adding a new flag `bind-proxy-address` to `yurthub` cmd
Fixes #
This PR add a new cmd flag `bind-proxy-address` for `yurthub`.
```release-note
```
> Separate YurtHubHost  & YurtHubProxyHost

- pkg/yurtctl/cmd/yurttest/kindinit/converter.go
- pkg/yurtctl/cmd/yurttest/kindinit/converter_test.go
- pkg/yurtctl/cmd/yurttest/kindinit/init.go
- pkg/yurtctl/cmd/yurttest/kindinit/init_test.go
- pkg/yurtctl/cmd/yurttest/kindinit/kindoperator.go
- pkg/yurtctl/cmd/yurttest/kindinit/kindoperator_test.go
- pkg/yurtctl/lock/lock.go
- pkg/yurtctl/lock/lock_test.go
- pkg/yurtctl/util/kubernetes/apply_addons.go
- pkg/yurtctl/util/kubernetes/apply_addons_test.go
- pkg/yurtctl/util/kubernetes/util.go
- pkg/yurtctl/util/kubernetes/util_test.go
Fixes #
Yurttest is the main function in yurtctl, and the unit test coverage of yurttest has been  promoted to 56.1%.
```release-note
```
> Yurtctl devfor ut

- pkg/yurthub/cachemanager/cache_manager_test.go
- pkg/yurthub/util/util.go
- pkg/yurthub/util/util_test.go
> /kind bug
Fixes #957
/root/go/pkg/mod/k8s.io/apiserver@v0.22.3/pkg/endpoints/request/requestinfo.go:180
This side causes the get and list namespace to return different namespace fields in requestInfo.
But there is a problem with the resources of namespace alone. So the specific resource namespace is circumvented in the code.
> fix issue 957

- pkg/util/kubernetes/kubeadm/app/constants/constants.go
- pkg/util/kubernetes/kubeadm/app/discovery/token/token.go
- pkg/yurtadm/cmd/join/join.go
- pkg/yurtadm/cmd/join/phases/joinnode.go
- pkg/yurtadm/cmd/join/phases/preflight.go
- pkg/yurtadm/util/kubernetes/util.go
Support yurtadm join to join multiple master nodes, such as `yurtadm join 1.2.3.4:6443,1.2.3.5:6443,1.2.3.6:6443 --token=abcdef.0123456789abcdef --node-type=edge --discovery-token-unsafe-skip-ca-verification --v=5`
> support yurtadm join to join multiple master nodes

- pkg/yurthub/metrics/metrics.go
- pkg/yurthub/proxy/proxy.go
- pkg/yurthub/proxy/util/util.go
- pkg/yurthub/proxy/util/util_test.go
/kind feature
The latency collector is used to collect yurthub request latency metrics, and the latency metrics can be  divided into two categories:
- **apiserver_latency**:  requests forward by proxy server -> api server ->  received by proxy server
- **full_latency**:  requests comming to proxy server -> processing by proxy server -> api server -> received by proxy server -> proxy server handling 
The full latency start recording after [inflight requests limits has been applied](https://github.com/openyurtio/openyurt/blob/277c2ebe19763e89a637dabca49f6e482bef6cf2/pkg/yurthub/proxy/proxy.go#L112), because latency of blocked requests is of no use. 
```release-note
```
> feature: add lantency metrics for yurthub

- charts/openyurt/templates/yurt-tunnel-agent.yaml
- charts/openyurt/templates/yurt-tunnel-server.yaml
- config/setup/yurt-tunnel-agent.yaml
- config/setup/yurt-tunnel-server.yaml
- config/yaml-template/yurt-tunnel-agent.yaml
- config/yaml-template/yurt-tunnel-server.yaml
- pkg/yurtctl/constants/yurt-app-manager-tmpl.go
- pkg/yurtctl/constants/yurt-tunnel-agent-tmpl.go
- pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go
/kind bug
deprecated resource should not be used to avoid warning.
avoid the following deprecation warning.
```bash
root@tomoyafujita:~/openyurt# kubectl apply -f config/setup/yurt-tunnel-server.yaml
clusterrole.rbac.authorization.k8s.io/tunnel-proxy-client created
clusterrolebinding.rbac.authorization.k8s.io/tunnel-proxy-client created
clusterrole.rbac.authorization.k8s.io/yurt-tunnel-server created
clusterrolebinding.rbac.authorization.k8s.io/yurt-tunnel-server created
serviceaccount/yurt-tunnel-server created
service/x-tunnel-server-svc created
service/x-tunnel-server-internal-svc created
configmap/yurt-tunnel-server-cfg created
Warning: spec.template.spec.nodeSelector[beta.kubernetes.io/arch]: deprecated since v1.14; use "kubernetes.io/arch" instead
Warning: …
```
> beta.kubernetes.io is deprecated, use kubernetes.io instead

- hack/make-rules/local-up-openyurt.sh
- pkg/yurtctl/cmd/yurttest/kindinit/init.go
- pkg/yurtctl/cmd/yurttest/kindinit/init_test.go
- pkg/yurtctl/constants/openyurt-kindconfig-tmpl.go
Sometimes, we does not want the default cni kindnet to be installed in the cluster. For example, if we want to test other cni like flannel or calico to check if them can be compatible with openyurt, we need to uninstall the kindnet first and then install the cni we want. It's not such a easy job. This pr provides a way for users to install kind cluster without any pre-installed CNI.
Fixes #
```release-note
```
> [enhancement] enable `yurtctl test init` to install cluster without default kindnet

- pkg/yurtctl/cmd/yurttest/kindinit/kindoperator.go
- pkg/yurtctl/cmd/yurttest/kindinit/kindoperator_test.go
/kind bug
When `exec.Command("base", "-c", "go env GOPATH")`, the path it returns looks like `"/home/ys3/.gvm/pkgsets/system/global\n"`, while the suffix `\n` we do not need.
Fixes #
```release-note
```
> [Fix] trim suffix new line when getting gopath

- pkg/yurthub/cachemanager/cache_agent.go
- pkg/yurthub/cachemanager/cache_agent_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
> cache agent change optimize

- pkg/node-servant/components/yurthub.go
- pkg/util/ip/ip.go
- pkg/util/ip/ip_test.go
- pkg/yurtadm/cmd/join/join.go
- pkg/yurtadm/cmd/join/joindata/data.go
- pkg/yurtadm/cmd/join/phases/joinnode.go
- pkg/yurtadm/cmd/join/phases/postcheck.go
- pkg/yurtadm/constants/constants.go
- pkg/yurtadm/constants/join_options.go
- pkg/yurtadm/util/edgenode/common.go
When using `yurtadm join`, currently it's set as `127.0.0.1` as default. This PR adds an extra parameter `yurthubServerAddr` to make this configurable. 
```release-note
Add an extra parameter `yurthubServerAddr` for `yurtadm join` command
```
> feature: yurtadm join add yurthubserveraddr para

- pkg/yurthub/gc/gc.go
Signed-off-by: Tomoya Fujita <Tomoya.Fujita@sony.com>
/kind bug
Minor error check via LiseKeys of Storage Interface call.
N.A (it just fixes debug log for user experience.)
I am not sure what kind of verification process or procedure required to this PR.
Could you provide the guidance about it?
> Check if error via ListKeys of Storage Interface.

- hack/lib/common.sh
- pkg/projectinfo/projectinfo.go
- pkg/yurtctl/cmd/yurttest/kindinit/init.go
- pkg/yurtctl/cmd/yurttest/kindinit/init_test.go
As #1007 , when we release new version of openyurt, we have to manually revise versions in code, which is often forgot. This pr will automatically detect released versions of openyurt and link to projectInfo when building binaries, which can simplify what we need to do when releasing new version.
Fixes #
```release-note
```
> Add released openyurt versions to projectInfo when building binaries

- docs/proposals/202106120-edgex-integration.md
- docs/proposals/20210628-nodepool-ingress-support.md
After https://github.com/openyurtio/openyurt/issues/852, some related doc need to update.
Fixes #
```release-note
```
> revise proposal docs

- charts/openyurt/templates/yurt-controller-manager.yaml
- cmd/yurt-controller-manager/app/controllermanager.go
- cmd/yurt-controller-manager/app/core.go
- pkg/controller/servicetopology/adapter/adapter.go
- pkg/controller/servicetopology/adapter/endpoints_adapter.go
- pkg/controller/servicetopology/adapter/endpoints_adapter_test.go
- pkg/controller/servicetopology/adapter/endpointslicev1_adapter.go
- pkg/controller/servicetopology/adapter/endpointslicev1_adapter_test.go
- pkg/controller/servicetopology/adapter/endpointslicev1beta1_adapter.go
- pkg/controller/servicetopology/adapter/endpointslicev1beta1_adapter_test.go
- pkg/controller/servicetopology/servicetopology.go
- pkg/controller/servicetopology/servicetopology_test.go
- pkg/yurtctl/constants/constants.go
make servicetopology filter in yurthub work properly when service or nodepool change
Fixes #871 
/assign  @rambohe-ch 
```release-note
"NONE"
```
> make servicetopology filter in yurthub work properly when service or nodepool change

- pkg/yurtctl/cmd/yurttest/kindinit/init.go
/kind bug
When we use test cluster with more than 2 nodes, there may be no pods running on the control-plane-node, which will make the e2e tests of yurt-tunnel fail. And I think, there seems no reason to set host service topology in the test environment.
Fixes #
```release-note
```
> do not set host service topology in test cluster

- pkg/yurthub/filter/servicetopology/handler.go
- pkg/yurthub/filter/servicetopology/handler_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind bug
if no endpoints left after service topology filtering, yurthub should return a empty endpointslice to clients(like kube-proxy) instead of skipping the object. because kube-proxy need to use the empty endpointslice to update network setting on edge nodes.
Fixes #
```release-note
```
> bugfix: even no endpoints left after filter, an empty object should be returned to clients

- cmd/yurthub/app/config/config.go
- cmd/yurthub/app/options/options.go
- cmd/yurthub/app/start.go
- pkg/yurthub/healthchecker/fake_checker.go
- pkg/yurthub/healthchecker/health_checker.go
- pkg/yurthub/healthchecker/health_checker_test.go
- pkg/yurthub/healthchecker/interfaces.go
- pkg/yurthub/healthchecker/node_lease.go
- pkg/yurthub/healthchecker/prober.go
- pkg/yurthub/healthchecker/prober_test.go
- pkg/yurthub/kubernetes/rest/config.go
- pkg/yurthub/proxy/proxy.go
- pkg/yurthub/proxy/remote/loadbalancer.go
- pkg/yurthub/proxy/remote/loadbalancer_test.go
- pkg/yurthub/proxy/remote/remote.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
In order to check the healthy status of pool-coordinator component in the NodePool, the HealthChecker module is need to improved to adapt two kinds backends. so several  Interfaces have been added:
- HealthChecker: health checker for pool-coordinator component
- MultipleBackendsHealthChecker: health checker for kube-apiservers on cloud
- BackendProber: used for sending heartbeat to backend.
btw: the detail info about pool coordinator, please dive into the following proposals:
- …
> improve health checker for adapting coordinator

- README.md
- README.zh.md
Signed-off-by: Lancelot <1984737645@qq.com>
In the README.md, developer guide link can not be accessed.And current master branch does not have developer-guide.md.
Fixes #1041 
```release-note
```
> Docs: replace guide link in README.md

- pkg/yurthub/certificate/hubself/fake_cert_mgr.go
- pkg/yurthub/server/certificate_test.go
- pkg/yurthub/server/nonresource.go
- pkg/yurthub/server/nonresource_test.go
- pkg/yurthub/server/server.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind bug
Like coredns component will post non resource request to kube-apiserver through yurthub, but yurthub can not handle non resource request when cloud-edge line off, so coredns can not recover when cloud-edge disconnected.
this pull request is used for solving the above problem.
Fixes #
```release-note
```
> bugfix: non resource handle miss for coredns

- Makefile
- hack/make-rules/run-e2e-tests.sh
- pkg/yurtctl/cmd/yurttest/kindinit/init.go
- pkg/yurtctl/cmd/yurttest/kindinit/init_test.go
- test/e2e/autonomy/autonomy_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
improve e2e tests as following:
1. add a parameter `ENABLE_AUTONOMY_TESTS` for enabling or disabling autonomy e2e tests, default is: true(enable autonomy e2e tests)
2. add a parameter `TARGET_PLATFORMS` for specifying platform that run e2e tests. for example: the command for running e2e tests on mac env: make e2e-tests TARGET_PLATFORMS=linux/arm64
3. enable autonomy tests for CoreDNS component.
Fixes #
```release-note
```
> improve e2e tests for supporting mac env and coredns autonomy

- docs/proposals/20221108-yurtadm-join-refactoring.md
> /kind design
Fixes #889 
```release-note
```
> proposal of yurtadm join refactoring

- test/e2e/autonomy/autonomy_test.go
/kind test
Sometimes, we may find that the coredns autonomy e2e tests fail for timeout. It seems that in the environment of Github Action, 30s is too short for the recovery of coredns. 
Inspect serval cases, it's found that the average time of coredns autonomy test is approximately 48s. So we can extend the timeout to 60s to ensure the test can finish in most cases.
Fixes #
```release-note
```
> Extend timeout for coredns autonomy test

- cmd/yurthub/app/config/config.go
- cmd/yurthub/app/options/options.go
- cmd/yurthub/app/start.go
- pkg/yurthub/healthchecker/fake_checker.go
- pkg/yurthub/healthchecker/health_checker.go
- pkg/yurthub/healthchecker/health_checker_test.go
- pkg/yurthub/healthchecker/interfaces.go
- pkg/yurthub/healthchecker/node_lease.go
- pkg/yurthub/healthchecker/prober.go
- pkg/yurthub/healthchecker/prober_test.go
- pkg/yurthub/kubernetes/rest/config.go
- pkg/yurthub/poolcoordinator/coordinator.go
- pkg/yurthub/poolcoordinator/leader_election.go
- pkg/yurthub/proxy/proxy.go
- pkg/yurthub/proxy/remote/loadbalancer.go
- pkg/yurthub/proxy/remote/loadbalancer_test.go
- pkg/yurthub/proxy/remote/remote.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
> add yurthub leader election and coordinator framework

- test/e2e/autonomy/autonomy_test.go
- test/e2e/common/ns/ns.go
/kind bug
After execution of `docker reconnect` to reconnect the cloud node, there may have a little before the cloud node can be actually visited. So, we'd better keep retry when deleting namespace.
Fixes #1054 
```release-note
```
> retry deleting test ns after reconnecting cloud node

- test/e2e/autonomy/autonomy_test.go
/kind bug
After https://github.com/openyurtio/openyurt/pull/1060, 10s doesn't seem to be enough.
Fixes #1054 
```release-note
```
> wait for a moment before start to clean up yurt-e2e-test namespace

- test/e2e/autonomy/autonomy_test.go
It seems that 20s is not enough for reconnecting cloud node to kind network. So extend it to 120s.
Fixes #1054 
```release-note
```
> extend timeout to 2min when reconnecting cloud node after suite

- pkg/yurthub/kubernetes/meta/restmapper.go
Fix bug of RESTMapperManager.dynamicRESTMapper nil pointer.
When `_internal/restmapper/cache-crd-restmapper.conf` exist but is empty, the current implement would cause npe.
> Fix: fix dynamicRESTMapper nil pointer bug

- pkg/yurtadm/constants/constants.go
/kind bug
When the refactored `yurtadm join` running, we create the yaml file of YurtHub Static Pod to the `/etc/kubernetes/manifests` folder before calling `kubeadm join`.
In the case of `kubeadm join` before `1.23.0`, the `/etc/kubernetes/manifests` folder is checked to see if it has been created. So we need to add a preflight error ignored for this folder to adapt to the situation.
Fixes #1091 
```release-note
```
> bugfix: add ignore preflight errors to adapt kubeadm before version 1.23.0

- pkg/yurtadm/cmd/reset/reset_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
> add_reset_test.go

- go.mod
- go.sum
- pkg/yurtadm/constants/constants.go
- pkg/yurtadm/util/kubernetes/kubernetes.go
bugfix: dynamically switch apiVersion of JoinConfiguration to adapt to different versions of k8s
/kind bug
Fixes #1102 
```release-note
```
> bugfix: dynamically switch apiVersion of JoinConfiguration to adapt to different versions of k8s

- pkg/controller/poolcoordinator/cert/poolcoordinator_cert_manager.go
Fix bug of missing key "sa.key" in "pool-coordinator-static-certs" secret , which is put to "pool-coordinator-static-certs" key in "sa" secret.
> Fix: sa.key missing position bug.

- charts/openyurt/templates/yurt-tunnel-server.yaml
- charts/openyurt/values.yaml
Since users generally need to modify tunnelAgentConnectPort, it is recommended to add it to values.yaml for customization @rambohe-ch
> add tunnelAgentConnectPort to values

- cmd/yurthub/app/config/config.go
- cmd/yurthub/app/options/options.go
- cmd/yurthub/app/start.go
- pkg/node-servant/config/control-plane.go
- pkg/yurthub/healthchecker/health_checker.go
- pkg/yurthub/healthchecker/health_checker_test.go
- pkg/yurthub/poolcoordinator/certmanager/certmanager.go
- pkg/yurthub/poolcoordinator/constants/constants.go
- pkg/yurthub/poolcoordinator/coordinator.go
- pkg/yurthub/poolcoordinator/fake_coordinator.go
- pkg/yurthub/proxy/pool/pool.go
- pkg/yurthub/proxy/proxy.go
- pkg/yurthub/proxy/remote/loadbalancer.go
- pkg/yurthub/transport/transport.go
/kine bug
/kind feature
The following works has been done in this pr:
1. generate coordinator client according to ca, cert and key in the secret to communicate with coordinator
2. deliver SubjectAccessReview request to coresponding APIServer(Coordinator or Cloud APIServer) according to the Group value in it.
3. add `--enable-pool-coordinator` to enable the yurthub be aware of the pool-coordinator. If disabled, yurthub will work without pool-coordinator and no module about coordinator will start in yurthub.
4. fix bug that cannot cache response when proxying request, currently yurthub can work without `--enable-pool-coordinator`.
Fixes #778 
```release-note
```
> generate coordinator client and pass through SubjectAccessReview according to secret

- pkg/yurthub/poolcoordinator/coordinator.go
- pkg/yurthub/poolcoordinator/coordinator_test.go
/kind bug
Currently, no one will set the isPoolCacheSynced as true. We should set it as ture if detecting the lease updated.
Fixes #
```release-note
```
> bufix: set isPoolCacheSynced as true if lease updated

- pkg/yurtadm/cmd/join/join.go
- pkg/yurtadm/cmd/join/join_test.go
- pkg/yurtadm/cmd/join/joindata/data.go
- pkg/yurtadm/cmd/join/phases/prepare.go
- pkg/yurtadm/cmd/reset/phases/cleanyurtfile.go
- pkg/yurtadm/constants/constants.go
- pkg/yurtadm/util/kubernetes/kubernetes.go
/kind feature
yurtadm reset/join modification. Do not remove k8s binaries, add flag for using local cni binaries.
Fixes #1095
- Do not remove `kubeadm/kubelet/kubelet` and cni binaries on `yurtadm reset`.
- Add new flag `--reuse-cni-bin` for `yurtadm join`. It determines whether to reuse local CNI binaries or not. Default value is `false`.
> Feature: yurtadm reset/join modification. Do not remove k8s binaries, add flag for using local cni binaries.

- pkg/yurthub/storage/etcd/keycache_test.go
- pkg/yurthub/storage/etcd/mock/kv.go
/kind bug
golangci-lint reports that 
```plain-text
Error: copylocks: Put passes lock by value: github.com/openyurtio/openyurt/pkg/yurthub/storage/etcd/mock.KV contains github.com/stretchr/testify/mock.Mock contains sync.Mutex (govet)
```
This pr will solve the problem.
Fixes #
```release-note
```
> use pointer receiver in mocked clientv3.KV to avoid passing lock by value

- charts/openyurt/templates/pool-coordinator.yaml
- charts/openyurt/templates/yurt-controller-manager.yaml
- cmd/yurthub/app/options/options.go
- pkg/yurthub/storage/etcd/storage.go
- pkg/yurthub/util/util.go
1. Validate pool-coordinator chart to ensure it is installable.
2. Add default pool coordinator related service name "pool-coordinator-etcd", "pool-coordinator-apiserver", and ports to yurthub default options.
3. Add '--max-txn-ops=1000' to pool-coordinator etcd container command.
4. Add default transfer body size between yurthub and etcd to '100M'
> Fix: pool-coordinator chart format,  default service name, max body size .etc

- pkg/yurthub/poolcoordinator/coordinator.go
/kind bug
1. make updating coordinator fields as atomic operation
2. add isPoolCacheSynced as one condition of pool-coordinator ready, fix what we didn't do in #1131
As discussed in https://github.com/openyurtio/openyurt/pull/1126#discussion_r1064148395:
We should make the update of coordinator as an atomic operation to avoid undefined situation.
Fixes #
```release-note
```
> fix coordinator sync problem and update ready condition

- pkg/yurthub/server/nonresource.go
- pkg/yurthub/server/nonresource_test.go
/kind bug
If we use cordns of a high version (e.g. 1.8) but with a k8s cluster of low version (e.g. 1.20), the coredns cannot list/watch endpointslice/v1beta1, because it cannot discover the supported resource version through "GET /apis/discovery.k8s.io/v1" and "GET /apis/discovery.k8s.io/v1beta1".
The reason causing such problem is that yurthub nonresource handler will return http.StatusOK even the APIServer does not contain such resource. It will cause the coredns continuously "GET /apis/discovery.k8s.io/v1" which blocks the list/watch making it unavailable.
```go
func writeErrResponse(path string, err error, w http.ResponseWriter) {
klog.Errorf("failed to handle %s non resource request, %v", path, err)
status := …
```
> fix coredns cannot get /apis/discovery.k8s.io/v1 if cluster does not contain such resource

- cmd/yurthub/app/config/config.go
- cmd/yurthub/app/config/config_test.go
- cmd/yurthub/app/options/options.go
- cmd/yurthub/app/options/options_test.go
- cmd/yurthub/app/start.go
- pkg/yurthub/certificate/token/token.go
- pkg/yurthub/certificate/token/token_test.go
- pkg/yurthub/filter/manager/manager.go
- pkg/yurthub/filter/manager/manager_test.go
- pkg/yurthub/gc/gc.go
- pkg/yurthub/kubernetes/rest/config_test.go
- pkg/yurthub/network/iptables.go
- pkg/yurthub/network/network.go
- pkg/yurthub/proxy/util/util_test.go
- pkg/yurthub/server/certificate_test.go
- pkg/yurthub/server/server.go
- pkg/yurthub/tenant/tenant.go
- pkg/yurthub/util/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind bug
if you send SIGINT signal(kill -SIGINT pid) to yurthub component, yurthub can not exit and restart.
so i improved the yurthub http/https server by adding graceful stop feature.
Fixes #
```release-note
```
> bugfix: yurthub can not exit when SIGINT/SIGTERM happened

- pkg/yurtctl/cmd/yurttest/kindinit/init.go
- pkg/yurtctl/cmd/yurttest/kindinit/init_test.go
- pkg/yurthub/filter/constant.go
- pkg/yurthub/filter/inclusterconfig/filter.go
- pkg/yurthub/filter/inclusterconfig/handler.go
- pkg/yurthub/filter/inclusterconfig/handler_test.go
- pkg/yurthub/filter/manager/manager.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
1. add inclusterconfig filter for commenting kubeconfig setting in `kube-system/kube-proxy` configmap, in order to make kube-proxy on nodes with yurthub(like edge nodes) to use `InClusterConfig` to access kube-apiserver.  at the same time, kube-proxy on master nodes without yurthub can use kubeconfig to access kube-apiserver.
2. delete kube-proxy configure in `yurtctl init test` command.
Fixes #1127 
```release-note
```
> add inclusterconfig filter for commenting kube-proxy configmap

- cmd/yurthub/app/config/config.go
Prefix 'http://' of the param is duplicated, so I remove it.
> Fix: yurthub proxy server addr option

- pkg/webhook/poolcoordinator_webhook.go
/kind bug
When yurt-controller-manager restart, it will encounter fatal error and exit because the mutatingwebhookconfiguration and validatingwebhookconfiguration has already exists.
Fixes #
```release-note
```
> bugfix: yurt-controller-manager cannot restart

- charts/openyurt/templates/pool-coordinator.yaml
- charts/openyurt/templates/yurt-controller-manager.yaml
- charts/openyurt/templates/yurthub-cfg.yaml
/kind bug
1. `SecretProjection` does not have field `defaultMode`, move it under projected. Refer to [SecretProjection api doc](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#secretprojection-v1-core) and [ProjectedVolumeSource api doc](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#projectedvolumesource-v1-core)
2. yurthub need to be authorized to list/watch `pool-coordinator-yurthub-charts`, and get/update leases
3. yurt-controller-manager serviceaccount should be placed in the same namespace as yurt-controller-manager, otherwise the pod cannot run.
Fixes #
```release-note
```
> fix charts

- pkg/yurthub/poolcoordinator/coordinator.go
/kind bug
The isRunning field of poolCacheSyncedDetector is never updated. Thus it may exist serval instances in memory and never stop.
Fixes #
```release-note
```
> fix: isRunning state of poolCacheSyncedDetector is not updated

- charts/openyurt/templates/pool-coordinator.yaml
- cmd/yurthub/app/start.go
- pkg/controller/poolcoordinator/cert/poolcoordinator_cert_manager.go
- pkg/yurthub/poolcoordinator/certmanager/certmanager.go
- pkg/yurthub/poolcoordinator/certmanager/certmanager_test.go
- pkg/yurthub/poolcoordinator/coordinator.go
/kind bug
Yurthub cannot delegate node lease because the resourceVersion is 0. Thus, the update will always fail.
Note:
Even this pr is merged, leader yurthub may also cannot delegate heartbeat, beacuse of the noderestiction admission plugin. It only allows the node to update its own kube-node-lease with node certificate. See [noderestriction plugin](https://github.com/kubernetes/kubernetes/blob/v1.22.7/plugin/pkg/admission/noderestriction/admission.go#L542-L565)
To enable this capability, we should disable the admission plugin in APIServer command line options, like
```yaml
...
spec:
containers:
- command:
- kube-apiserver
- --advertise-address=172.19.0.3
- --allow-privileged=true
- --authorization-mode=Node,RBAC
- …
```
> fix: leader yurthub cannot proxy heartbeat

- pkg/yurthub/util/util.go
Leader Yurthub will use UesrAgent "leader-yurthub" to list/watch pool-scoped resources. To simplify user settings, we can add "leader-yurthub" into default UserAgents. Otherwise, users need to manually add "leader-yurthub" into 'yurt-hub-cfg", it's not convenient.
Fixes #
```release-note
```
> add leader-yurthub into default cache agents

- go.mod
/kind feature
Fixes #1190
@rambohe-ch 
```release-note
```
> feat: bump golang from 1.16 to 1.17

- pkg/yurthub/proxy/pool/pool.go
- pkg/yurthub/proxy/remote/loadbalancer.go
- pkg/yurthub/proxy/util/util.go
Force re-list pool-scope resource when proxy change between loadbalancer and pool-coordinator
> fix: re-list when target change

- charts/openyurt/templates/pool-coordinator.yaml
> /kind bug
when the node disconnects from all nodes except itself, pool-coordinator in this node can be rescheduled into a healthy node.
Fixes #1212
/assign @Congrool
```release-note
Since charts/openyurt/templates/pool-coordinator.yaml is changed, users should upgrade the running pool-coordinator.
```
> fix: pool-coordinator cannot be rescheduled when its node fails (#1212)

- Makefile
/kind bug
When I upgraded the golangci-lint version from 1.31.0 to 1.40.0, the problem was solved
Fixes #1223 
```release-note
```
> fix: make lint bug

- pkg/yurthub/util/fs/store.go
Now, 'Rename' function can't handler the condition that 'If file of newPath has already existed, it will be replaced.' , and error would occurs. We should delete newPath if it's existed.
> Fix: make rename replace old dir

- pkg/yurtadm/util/kubernetes/kubernetes.go
/kind bug
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #1169 
```release-note
```
> Fix: yurtadm minor version compatibility of kubelet and kubeadm

- pkg/yurthub/filter/constant.go
- pkg/yurthub/filter/initializer/initializer.go
- pkg/yurthub/filter/manager/manager.go
- pkg/yurthub/filter/nodeportisolation/filter.go
- pkg/yurthub/filter/nodeportisolation/filter_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
add a new filter named nodeportisolation in yurthub in order to make only nodes in specified nodepool can listen on nodePort of service.
Fixes #1183 
```release-note
```
> add nodeportisolation filter in yurthub

- OWNERS
@YTGhost
openyurtio
@rambohe-ch 
https://github.com/openyurtio/openyurt/pull/1013
https://github.com/openyurtio/openyurt/pull/1048
https://github.com/openyurtio/openyurt/pull/1049
https://github.com/openyurtio/openyurt/pull/1063
https://github.com/openyurtio/openyurt/pull/1075
https://github.com/openyurtio/openyurt/pull/1092
https://github.com/openyurtio/openyurt/pull/1112
https://github.com/openyurtio/openyurt/pull/1115
https://github.com/openyurtio/openyurt/pull/1192
https://github.com/openyurtio/openyurt/pull/1219
https://github.com/openyurtio/openyurt/pull/1224
https://github.com/openyurtio/openyurt/pull/1244
- Issues :
https://github.com/openyurtio/openyurt/issues/1223
https://github.com/openyurtio/openyurt/issues/1190 …
> add YTGhost as reviewer of OpenYurt

- charts/openyurt/README.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
`yurt-tunnel-agent` and `yurt-tunnel-server` will be moved in [raven](https://github.com/openyurtio/raven).
Fixes #
```release-note
```
> docs: update chart readme

- Makefile
- cmd/yurt-controller-manager/controller-manager.go
- cmd/yurt-manager/yurt-manager.go
- cmd/yurt-node-servant/node-servant.go
- cmd/yurthub/yurthub.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
that need a specific result sequence should use NewRand(NewSource(seed))
Fixes #
```release-note
```
> Fix: remove deprecated rand

- test/e2e/cmd/init/converter.go
- test/e2e/cmd/init/util/kubernetes/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
print logs of yurt-manager component in local-up-openyurt in order to help to find reasons when errors happened in e2e tests 
Fixes #
```release-note
```
> print logs of yurt-manager component in local-up-openyurt

- Makefile
Originally, `make build` does not respect env `REGION`. Thus, when user uses `REGION=cn`, the build command will still use GOPROXY as `go env GOPROXY` which may be not reachable in China. This PR can solve the problem.
Fixes #
```release-note
```
> enable to build binary with cn GOPROXY

- cmd/yurthub/app/config/config.go
- cmd/yurthub/app/options/options.go
- pkg/yurthub/certificate/token/token.go
- pkg/yurthub/server/server.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
1. support pass bootstrap file instead of join token for bootstrapping yurthub in order to improve security of yurthub. so yurtadm join will not leave `bootstrap token` on the edge node.
2. parameter `--join-token` is deprecated in yurthub, and plan to remove in OpenYurt version v1.5.
3.  add `/v1/readyz` endpoint for yurthub, add used by yurtadm command to check certificates are ready or not.
Fixes #1290 
```release-note
```
> support pass bootstrap-file to yurthub

- go.mod
- go.sum
- pkg/node-servant/components/yurthub.go
- pkg/yurtadm/cmd/cmd.go
- pkg/yurtadm/cmd/join/phases/postcheck.go
- pkg/yurtadm/cmd/join/phases/prepare.go
- pkg/yurtadm/cmd/renew/certificate/certificate.go
- pkg/yurtadm/cmd/renew/renew.go
- pkg/yurtadm/constants/constants.go
- pkg/yurtadm/util/error/error.go
- pkg/yurtadm/util/error/error_test.go
- pkg/yurtadm/util/kubernetes/kubernetes.go
- pkg/yurtadm/util/yurthub/yurthub.go
/kind feature
1. add yurtadm renew certificate command
2. gather the yurthub-related functions into `pkg/yurtadm/util/yurthub/yurthub.go`
3. gather `CheckKubeletStatus` function into `pkg/yurtadm/util/kubernetes/kubernetes.go`
4. When building a test cluster, yurthub is also started with a bootstrap file
Fixes #1290 
```release-note
```
> feat: add yurtadm renew certificate command

- pkg/controller/daemonpodupdater/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind bug
When i use helm to deploy application, the daemonset in helm charts is add annotations for daemonsetpodupdater to use, and containers are constantly being created and deleted after deploy.
I print some log for daemonsetpodupdater 
```
I0329 10:16:42.059308   55304 util.go:77] IsDaemonsetPodLatest pod.Labels: 1, fmt.Sprint(generation): 0xc0008cc768
```
and find some error
```
pod.Labels[extensions.DaemonSetTemplateGenerationKey] == fmt.Sprint(generation)
```
the code want to use pointer …
> 【FIX】fix daemonset pod updater pointer error

- charts/openyurt/templates/yurt-manager-auto-generated.yaml
- charts/openyurt/templates/yurt-manager.yaml
- charts/openyurt/values.yaml
- cmd/yurt-controller-manager/app/controllermanager.go
- cmd/yurt-controller-manager/app/core.go
- pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/apps/v1beta1/zz_generated.deepcopy.go
- pkg/apis/raven/v1alpha1/zz_generated.deepcopy.go
- pkg/controller/add_poolcoordinatorcert.go
- pkg/controller/poolcoordinator/cert/certificate.go
- pkg/controller/poolcoordinator/cert/certificate_test.go
- pkg/controller/poolcoordinator/cert/poolcoordinatorcert_controller.go
- pkg/controller/poolcoordinator/cert/poolcoordinatorcert_controller_test.go
- pkg/controller/poolcoordinator/cert/secret.go
- pkg/controller/poolcoordinator/cert/secret_test.go
- pkg/controller/poolcoordinator/cert/util.go
- pkg/controller/poolcoordinator/cert/util_test.go
1. migrate poolcoordinator-cert-manager into yurt-manager framework
2. fix syntax in helm charts 
Fixes # https://github.com/openyurtio/openyurt/issues/1067
```release-note
NONE
```
> migrate controller poolcoordinatorcert 

- charts/openyurt/templates/yurt-controller-manager.yaml
- pkg/controller/gateway/gateway/gateway_controller.go
- pkg/controller/nodepool/util.go
- pkg/controller/poolcoordinator/delegatelease/poolcoordinator_controller.go
- pkg/controller/util/node/controller_utils.go
- pkg/node-servant/preflight/checks.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind bug
When node ready condition is unknown, the native kubernetes will set node.kubernetes.io/unreachable taints in node,
and the pod will be evict after 300s, that's not what we're trying to do in delegate lease.
Up to now, it's only happen when leader in nodePool is disconnected with cloud, and this node will be not-ready,
because in an election cycle, the node lease will not delegate to cloud, after 40s, the kubernetes will set unknown.
Fixes #
@rambohe-ch 
```release-note
```
> 【FIX】fix node not-ready condition when leader disconnect with cloud

- charts/openyurt/templates/pool-coordinator.yaml
- charts/openyurt/values.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Pool-coordinator APIServer image is 
```
{{ .Values.poolCoordinator.apiserverImage.registry }}/{{ .Values.poolCoordinator.apiserverImage.repository }}:{{ .Values.poolCoordinator.apiserverImage.tag }}
```
But there's no `.Values.poolCoordinator.apiserverImage.registry`, which causes the applied image of apiserver is `/registry.k8s.io/kube-apiserver:v1.22.0` making pool-coordinator fail to run. This pr will solve this problem.
Fixes #
```release-note
```
> fix nil image registry of pool-coordinator

- hack/make-rules/add_controller.sh
- pkg/webhook/builder/defaulter_custom.go
- pkg/webhook/builder/validator_custom.go
- pkg/webhook/builder/webhook.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
At present, the webhook builder not support any other information, for example, like request info, we will use this parameter to some scenes, like use it to judge source of request, it can make our webhook more stronger and rigorous.
So we need to add other builder to create webhook.
Fixes #
```release-note
```
> add a new way to create webhook

- charts/openyurt/templates/yurt-manager.yaml
- cmd/yurt-manager/app/options/generic.go
- pkg/controller/apis/config/types.go
- pkg/controller/poolcoordinator/cert/poolcoordinatorcert_controller.go
Fixes #1342 
add a parameter for yurt-manager to specify namespace variable for PoolcoordinatorNS
modified helm: use value to specify namespace in pool-coordinator.yaml and add startup parameter in yurt-manager.yaml
> feat: support pool-coordinator component work in specified namespace

- pkg/controller/poolcoordinator/cert/certificate.go
- pkg/controller/poolcoordinator/cert/certificate_test.go
- pkg/controller/poolcoordinator/cert/poolcoordinatorcert_controller.go
- pkg/controller/poolcoordinator/cert/poolcoordinatorcert_controller_test.go
- pkg/controller/poolcoordinator/cert/secret.go
- pkg/util/kubeconfig/kubeconfig.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind bug
- background:
pool coordinator cert controller is used for preparing certificates for pool coordinator component, and it should wait for service of pool-coordinator ready before creating certificates. At present, all certificates preparation is handled in controller setup, so other controllers setup are blocked by pool coordinator cert controller.
- solution:
separate `allSelfSignedCerts` into three kinds: 
- `allIndependentCerts`: don't depend on service, and can be prepared in …
> refactor pool-coordinator-cert controller

- charts/openyurt/templates/yurt-manager.yaml
- cmd/yurt-manager/app/manager.go
- pkg/controller/gateway/gateway/gateway_controller.go
- pkg/webhook/server.go
- pkg/webhook/util/controller/webhook_controller.go
- pkg/webhook/util/util.go
/kind feature
support yurt-manager deploy in specified namespace:
support Gateway controller and Yurt-manager webhooks
Fixes parts of #1361 
```release-note
```
> feat: support yurt-manager work in specified namespace

- charts/openyurt/templates/yurt-manager.yaml
- charts/openyurt/values.yaml
- cmd/yurt-manager/app/manager.go
- cmd/yurt-manager/app/options/generic.go
- pkg/controller/add_csrapprover.go
- pkg/controller/add_daemonpodupdater.go
- pkg/controller/add_delegatelease.go
- pkg/controller/add_gateway.go
- pkg/controller/add_nodepool.go
- pkg/controller/add_podbinding.go
- pkg/controller/add_poolcoordinatorcert.go
- pkg/controller/add_servicetopology_endpoints.go
- pkg/controller/add_servicetopology_endpointslice.go
- pkg/controller/add_staticpod.go
- pkg/controller/add_yurtappset.go
- pkg/controller/apis/config/types.go
- pkg/controller/controller.go
- pkg/controller/util/controller_utils.go
- pkg/webhook/add_v1alpha1_gateway.go
- pkg/webhook/add_v1alpha1_nodepool.go
- pkg/webhook/add_v1alpha1_staticpod.go
- pkg/webhook/add_v1alpha1_yurtappset.go
- pkg/webhook/add_v1beta1_nodepool.go
- pkg/webhook/server.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #1379 
```release-note
```
> support to specify enabled controllers

- pkg/webhook/yurtappset/v1alpha1/validate.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #1390
```release-note
```
> bugfix for yurtappset

- pkg/apis/apps/v1alpha1/default.go
/kind bug
If not set default `PodSpec` for `staticpod` `PodTemplateSpec`, then when applying `staticpod`, it may be rejected due to `PodTemplateSpec` validation not passing.
Fixes #
```release-note
```
> fix: set default podspec for staticpod podtemplatespec

- charts/openyurt/crds/apps.openyurt.io_yurtappsets.yaml
- pkg/apis/apps/v1alpha1/yurtappset_types.go
- test/e2e/yurt/yurtappset.go
/kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
> fix: yurtappset patch

- pkg/controller/staticpod/config/types.go
- pkg/controller/staticpod/staticpod_controller.go
- pkg/controller/staticpod/upgradeinfo/upgrade_info.go
- pkg/controller/staticpod/upgradeinfo/upgrade_info_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
There are some double counting in the existing code on upgrde info, and the calculation part is scattered and the parameter assignment is not uniform.
So this pr is used to optimized the upgrade info, and keep the computation in one place, rather than spreading it out.
Meanwhile, peel off the relevant calculation from staticpod_controller to upgrade_info, make the responsibilities clearer.
Fixes #
```release-note
```
> optimize staticpod controller for upgrade info

- go.mod
- go.sum
> /kind bug
There is a memory leak in the yurt-tunnel-server, consuming too much memory.
The reason is that there is a goroutine memory leak in the dependency `apiserver-network-proxy`
Fixes # https://github.com/openyurtio/openyurt/issues/1440
@rambohe-ch
> fix memory leak for yur-tunnel-server

- test/e2e/yurt/daemonpodupdater.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #1476 
```release-note
```
has written e2e tests for the auto upgrade model and ota upgrade model of the daemonset pod updater respectively
> feat: add e2e test case for daemonset pod updater controller

- charts/yurthub/templates/yurthub-cloud-yurtstaticset.yaml
- charts/yurthub/templates/yurthub-yurtstaticset.yaml
- pkg/apis/apps/v1alpha1/default.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
If user defines different namespace in pod template with yurtstaticset namespace, yurtstaticset controller don't know how to handle this case.
Fixes #1473 
```release-note
```
> improve yurtstaticset template metadata

- pkg/yurtadm/constants/constants.go
- pkg/yurtadm/util/yurthub/yurthub.go
- pkg/yurtadm/util/yurthub/yurthub_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
In the scenario where the user forgets to set the yurthub server address for the master node, the yurtadm join command should replace the yurthub parameter with the address obtained from the join.
Fixes #
#1474 
```release-note
```
> feat: use real kubernetes server address to yurthub when yurtadm join

- pkg/yurthub/poolcoordinator/coordinator.go
- pkg/yurthub/storage/etcd/keycache.go
- pkg/yurthub/storage/etcd/storage.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind bug
When yurthub connect with pool-coordinator etcd failed, and keep try again, the goroutine of grpc is increase all the while, and memory of yurthub also increase, and kubelet will restart it when is happen OOM.
Fixes #
```release-note
```
> fix yurthub memory leak

- pkg/yurtadm/cmd/join/phases/prepare.go
- pkg/yurtadm/util/initsystem/initsystem.go
- pkg/yurtadm/util/initsystem/initsystem_unix.go
- pkg/yurtadm/util/initsystem/initsystem_windows.go
- pkg/yurtadm/util/kubernetes/kubernetes.go
/kind bug
Fixes #1520 
@rambohe-ch 
```release-note
```
> fix: yurtadm support enable kubelet service

- pkg/controller/daemonpodupdater/daemon_pod_updater_controller.go
- pkg/yurtadm/util/initsystem/initsystem_windows.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind bug
* Goland Code Inspection cannot recognize function type conversion after type assertion(Cannot use 'r.(*ReconcileDaemonpodupdater).deletePod' (type func(ReconcileDaemonpodupdater, event.DeleteEvent, workqueue.RateLimitingInterface)) as the type func(event.DeleteEvent, workqueue.RateLimitingInterface)). split type assertion out to fix this.
* WindowsInitSystem ServiceEnable return value is wrong
```release-note
```
> fix: ide reconciler convert error and ServiceEnable return value wrong

- pkg/controller/servicetopology/adapter/adapter.go
- pkg/controller/servicetopology/adapter/endpoints_adapter.go
- pkg/controller/servicetopology/adapter/endpoints_adapter_test.go
- pkg/controller/servicetopology/adapter/endpointslicev1_adapter.go
- pkg/controller/servicetopology/adapter/endpointslicev1_adapter_test.go
- pkg/controller/servicetopology/adapter/endpointslicev1beta1_adapter.go
- pkg/controller/servicetopology/adapter/endpointslicev1beta1_adapter_test.go
- pkg/controller/servicetopology/endpoints/endpoints_controller.go
- pkg/controller/servicetopology/endpoints/endpoints_enqueue_handlers.go
- pkg/controller/servicetopology/endpointslice/endpointslice_controller.go
- pkg/controller/servicetopology/endpointslice/endpointslice_enqueue_handlers.go
- pkg/controller/servicetopology/util/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
As discussed in #1553 , The efficiency of service topology feature can be improved if nodepool list/watch is removed.
moreover, nodepool list/watch is a dummy function for service topology controller. 
so i want to remove list/watch nodepool function in service topology controller.
Fixes #1553 
```release-note
```
> feat: remove watch nodepool in service topology controller

- cmd/yurthub/app/config/config.go
- pkg/yurthub/filter/filter.go
- pkg/yurthub/filter/initializer/initializer.go
- pkg/yurthub/filter/manager/manager.go
- pkg/yurthub/filter/manager/manager_test.go
- pkg/yurthub/filter/nodeportisolation/filter.go
- pkg/yurthub/filter/nodeportisolation/filter_test.go
- pkg/yurthub/filter/servicetopology/filter.go
- pkg/yurthub/filter/servicetopology/filter_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind bug
1. As described in pull request #1461 , filter servicetoplogy and nodeisolation have conflicts for getting node from local storage, and filter can not work well.
2. After diving into the code of these two filters, we found that node resource is used for resolving node pool, and as discussed in the issue: #1382 and pull request #1444 , node pool name for a node can not be changed after joining into the cluster.
3. at the same time, node pool name can be passed into yurthub by `yurtadm …
> fix conflicts for getting node by local storage in yurthub filters

- cmd/yurthub/app/config/config.go
- pkg/yurthub/server/server.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
User use yurtstaticset to upgrade pod, the worker pod will check the static pod status using  restful apis for yurthub like: /pods, when yurthub running in the cloud, it will not return pods because the yurthub not cache info for cloud mode.
So yurthub is cloud mode, when get pods, it can use informer cache to return pod list.
Fixes #
```release-note
```
> improve yurthub get pods for cloud node

- pkg/yurtadm/cmd/join/join.go
- pkg/yurtadm/cmd/join/joindata/data.go
- pkg/yurtadm/cmd/join/phases/joinnode.go
- pkg/yurtadm/cmd/join/phases/prepare.go
- pkg/yurtadm/constants/constants.go
- pkg/yurtadm/util/yurthub/yurthub_test.go
/kind feature
Fixes #1448 
```release-note
```
> feat: provide config option for yurtadm

- pkg/controller/servicetopology/adapter/endpoints_adapter.go
- pkg/controller/servicetopology/adapter/endpoints_adapter_test.go
- pkg/controller/servicetopology/adapter/endpointslicev1_adapter.go
- pkg/controller/servicetopology/adapter/endpointslicev1_adapter_test.go
- pkg/controller/servicetopology/adapter/endpointslicev1beta1_adapter.go
- pkg/controller/servicetopology/adapter/endpointslicev1beta1_adapter_test.go
- pkg/controller/servicetopology/endpoints/endpoints_controller.go
- pkg/controller/servicetopology/endpointslice/endpointslice_controller.go
feat: improve service topology controller by using client.Client instead of kubernetes.Interface
> /kind bug
/kind feature
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
In service topology controller, kubernetes.Interface is used for updating annotations of [endpoints](https://github.com/openyurtio/openyurt/blob/master/pkg/controller/servicetopology/adapter/endpoints_adapter.go#L49), [v1.endpointslices](https://github.com/openyurtio/openyurt/blob/master/pkg/controller/servicetopology/adapter/endpointslicev1_adapter.go#L61), …
> feat: improve service topology controller by using client.Client instead of kubernetes.Interface

- pkg/yurtadm/util/kubernetes/kubernetes.go
/kind bug
address https://github.com/openyurtio/openyurt/issues/1573
It does use the default file access permission.
- `/opt/cni/bin`
```bash
tomoyafujita@~ >ls -lt /opt/cni/
total 4.0K
drwxr-xr-x 2 root root 4.0K Jun  9 15:43 bin/
```
- `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf`
```bash
tomoyafujita@~ >ls -lt /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
-rw-r----- 1 root root 898 Sep 21  2022 /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
```
Fixes #1573 
- I believe this makes sense, and avoid unexpected problem such as https://github.com/cilium/cilium/issues/22933
> change access permission to default in general.

- .github/workflows/registry.yaml
Adds support for pushing to github container registry to avoid docker hub rate limits. 
Fixes #1575 
```release-note
OCI images can now also be found on Github
```
> build: added github registry

- .github/workflows/ci.yaml
- .github/workflows/registry.yaml
- .github/workflows/release-assets.yaml
- .goreleaser.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
backport #1577 to branch release-v1.1
Fixes #
```release-note
```
> backport: feat: add yurtadm binaries release workflow

- charts/yurt-manager/templates/yurt-manager-auto-generated.yaml
- go.mod
- pkg/webhook/node/v1/node_handler.go
- pkg/webhook/node/v1/node_validation.go
- pkg/webhook/server.go
- pkg/webhook/util/controller/webhook_controller.go
- test/e2e/yurt/nodepool.go
- test/e2e/yurt/yurtappdaemon.go
- test/e2e/yurt/yurtappset.go
/kind feature
Fixes #1382 
add a validation webhook for node:
user can not change `apps.openyurt.io/desired-nodepool` if node has been added in noodpool
user can not change `apps.openyurt.io/nodepool` directly, only yurt-manger can change this label
```release-note
```
> feat: prevent node movement by label modification

- config/setup/yurthub.yaml
> /kind bug
there is not cpu limit for yurthub, it will cause the yurthub cost too much CPU, causing high node load and affecting other services.
Fixes #https://github.com/openyurtio/openyurt/issues/1605
> add cpu limit for yurthub

- pkg/webhook/yurtstaticset/v1alpha1/yurtstaticset_validation.go
> str replaced by const

- pkg/controller/platformadmin/config/EdgeXConfig/config-nosecty.json
- pkg/controller/platformadmin/config/EdgeXConfig/config.json
- pkg/controller/platformadmin/platformadmin_controller.go
/kind feature
/sig iot
This pr will give users the ability to customize the edgex framework. We write the standard configuration collected by the auto-collector into a configmap called "platformadmin-framework". Users can customize their edgex by editing this configmap.
Fixes #1595
```release-note
kubectl edit cm platformadmin-framework
```
> feat: provide users with the ability to customize the edgex framework

- test/e2e/cmd/init/converter.go
- test/e2e/cmd/init/init.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Add check about the yurt manager container's readiness in e2e, otherwise the deployment webhook won't be ready at update of coredns. 
Fixes #
```release-note
NONE
```
> check whether yurt manager's container is ready in e2e

- pkg/controller/yurtstaticset/yurtstaticset_controller.go
- pkg/controller/yurtstaticset/yurtstaticset_controller_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
When yurtStaticSet is delete, the configmap which is created by it is still exist, and it will always be there.
Fixes #
```release-note
```
> delete configmap when yurtstaticset is deleting

- cmd/yurt-iot-dock/app/core.go
- pkg/yurtiotdock/controllers/device_controller.go
- pkg/yurtiotdock/controllers/deviceprofile_controller.go
- pkg/yurtiotdock/controllers/deviceservice_controller.go
/kind feature
/sig iot
When YurtIoTDock receives the exit signal, it needs to reclaim device, deviceprofile, and deviceservice.
Clean up unwanted cr for users.
Fixes #1626 
```release-note
NONE
```
> feat: reclaim device, deviceprofile and deviceservice before exiting YurtIoTDock 

- cmd/yurthub/app/config/config.go
- cmd/yurthub/app/start.go
- go.mod
- go.sum
- pkg/apis/apps/well_known_labels_annotations.go
- pkg/util/kubeconfig/kubeconfig.go
- pkg/util/kubeconfig/kubeconfig_test.go
- pkg/util/kubernetes/kubeadm/app/util/apiclient/idempotency.go
- pkg/yurtadm/cmd/join/join.go
- pkg/yurthub/filter/initializer/initializer.go
- pkg/yurthub/filter/initializer/initializer_test.go
- pkg/yurthub/filter/manager/manager.go
- pkg/yurthub/filter/manager/manager_test.go
- pkg/yurthub/filter/nodeportisolation/filter.go
- pkg/yurthub/filter/servicetopology/filter.go
- pkg/yurthub/filter/servicetopology/filter_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
1. remove dependencies on yurt-app-manager-api repo and yurt client repo
2. use dynamic client and dynamicinformer to get NodePool resource
3. update imports of v1alpha1.NodePool to v1beta1.NodePool
Fixes #1010
```release-note
```
> use dynamicinformerfactory to get nodepool instead of yurt-app-manager-api repo

- cmd/yurt-manager/app/options/options.go
- pkg/apis/raven/well_known_labels_annotations.go
- pkg/yurtmanager/controller/controller.go
- pkg/yurtmanager/controller/raven/common.go
- pkg/yurtmanager/controller/raven/dns/dns_controller.go
- pkg/yurtmanager/controller/raven/dns/dns_controller_test.go
- pkg/yurtmanager/controller/raven/dns/dns_enqueue_handlers.go
- pkg/yurtmanager/controller/raven/dns/dns_enqueue_handlers_test.go
- pkg/yurtmanager/controller/raven/utils/utils.go
> /sig network
This controller maintains a configmap record that requests across network domains are forwarded to the Gateway node by the Raven Agent
Fixes #
```release-note
A configmap named edge-tunnel-nodes is mounted to CoreDNS using the hosts plugin, the DNS controller is responsible for maintaining this configmap and maps requests of acrossing pools to the x-raven-proxy-internal-svc address
```
> add raven l7 dns controller

- charts/yurt-manager/crds/iot.openyurt.io_platformadmins.yaml
- pkg/apis/iot/v1alpha1/platformadmin_types.go
/sig iot
Let users use the more complete version of v1alpha2.
Fixes #1656
```release-note
Please use the v1alpha2 version of platformadmin, which is much more complete than v1alpha1.
```
> feat: unserve v1alpha1 version of platformadmin crd

- pkg/yurtmanager/controller/platformadmin/platformadmin_controller.go
/kind bug
/sig iot
Because the `yurt-iot-dock` is an internal component of `openyurt` and is not in the standard configuration collected by the `auto-collector`, a separate decision for the `yurt-iot-dock` is added when calculating the required components.
```release-note
```
> fix: yurt-iot-dock cannot be dynamically deployed in platformadmin

- pkg/yurtmanager/controller/controller.go
- pkg/yurtmanager/controller/raven/common.go
- pkg/yurtmanager/controller/raven/gatewayinternalservice/gateway_internal_service_controller.go
- pkg/yurtmanager/controller/raven/gatewayinternalservice/gateway_internal_service_controller_test.go
- pkg/yurtmanager/controller/raven/gatewayinternalservice/gateway_internal_service_enqueue_handlers.go
- pkg/yurtmanager/controller/raven/utils/options.go
- pkg/yurtmanager/controller/raven/utils/utils.go
> /sig network
Fixes #
```release-note
```
> add gateway internal service controller

- pkg/yurtadm/cmd/join/join.go
- pkg/yurtadm/constants/constants.go
- pkg/yurtadm/util/kubernetes/kubernetes.go
/kind feature
Fixes #1672 
```release-note
```
> feat: add token format checking to yurtadm join process

- pkg/yurtmanager/controller/controller.go
- pkg/yurtmanager/controller/raven/common.go
- pkg/yurtmanager/controller/raven/gatewayinternalservice/gateway_internal_service_enqueue_handlers.go
- pkg/yurtmanager/controller/raven/gatewaypickup/gateway_pickup_controller.go
- pkg/yurtmanager/controller/raven/gatewaypublicservice/gateway_public_service_controller.go
- pkg/yurtmanager/controller/raven/gatewaypublicservice/gateway_public_service_controller_test.go
- pkg/yurtmanager/controller/raven/gatewaypublicservice/gateway_public_service_enqueue_handlers.go
- pkg/yurtmanager/controller/raven/utils/utils.go
- pkg/yurtmanager/webhook/server.go
> /sig network
This controller focuses on automating the management of LoadBalancer services
Fixes #
```release-note
```
> add public service controller for manage loadbalancer service

- cmd/yurt-tunnel-server/app/options/options.go
- pkg/yurtmanager/controller/yurtappset/adapter/adapter_util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
NONE
```
> chore: slice loop replace

- pkg/yurthub/certificate/manager/manager.go
- pkg/yurthub/certificate/manager/manager_test.go
/kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
We expect Yurthub's workdir to be `/var/lib/yurthub`. Currently, it is set to `/var/lib/yurthub/yurthub` because `options.RootDir=/var/lib/yurthub` by default, which is misleading for end users.
Fixes #
```release-note
```
> Fix work dir nested `yurthub/yurthub`

- pkg/yurtiotdock/controllers/device_syncer.go
- pkg/yurtiotdock/controllers/deviceprofile_syncer.go
- pkg/yurtiotdock/controllers/deviceservice_syncer.go
/kind bug
/sig iot
add the logic of removing the finalizer
Fixes #1694 
/assgin @LavenderQAQ @wangxye
> fix: add the logic of removing the finalizer in yurt-iot-dock

- charts/yurt-manager/crds/raven.openyurt.io_gateways.yaml
- hack/make-rules/kustomize_to_chart.sh
> /sig network
add convert webhook for gateway 
Fixes #
```release-note
```
> add convert webhook for gateway

- go.mod
- go.sum
- pkg/yurtadm/cmd/cmd.go
- pkg/yurtadm/cmd/config/config.go
- pkg/yurtadm/constants/constants.go
- pkg/yurtadm/util/cmdutil.go
/kind feature
Fixes #1536 
```release-note
```
> feat: support yurtadm config command

- pkg/node-servant/convert/convert.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
> fix: fix some typo

- hack/make-rules/add_controller.sh
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
We update the yurt-manager controller and webhook dirctory, and the Makefile command: make newcontroller, auto-generated the code logic, not correct yet. so we need to update it.
Fixes #
```release-note
```
> update make newcontroller logic

- pkg/apis/calico/v3/doc.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
CRD blockaffinity does not need to be generated. So skip it.
Fixes #1716
```release-note
```
> fix: kustomize build yaml skipping blockaffinity

- pkg/yurtmanager/controller/yurtappoverrider/yurtappoverrider_controller.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind bug
panic will happen in yurtappoverrider when ordinary deployments without ownerreferences are handled.
so ownerreferences should be checked before yurtapporverrider deals with it.
Fixes #
```release-note
```
> fix yurtappoverrider panic for handling normal deployments that has no ownerreferences

- pkg/yurthub/storage/etcd/key.go
/kind bug
when pool scope resources set to some crd resources by editing yurt-hub-cfg configmap,  the default etcd storage key is wrong, where resource group is not set in the key path
Fixes #1728
```release-note
```
> fix  pool scope crd resource etcd key path

- pkg/yurthub/util/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
make yurthub can cache metadata for raven agent
Fixes #
```release-note
```
> make yurthub can cache metadata for raven agent

- pkg/yurthub/certificate/kubeletcertificate/kubelet_certificate.go
- pkg/yurthub/certificate/manager/manager.go
- pkg/yurtmanager/webhook/node/v1/node_default.go
> /kind bug
/kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
1. modify kubelet component certificate name
2. improve empty nodepool check
Fixes #
```release-note
```
> [yurthub component]: fix kubeletcertificate file name error and empty nodepool

- charts/yurt-manager/templates/yurt-manager.yaml
- charts/yurt-manager/values.yaml
- cmd/yurt-manager/app/manager.go
- cmd/yurt-manager/app/options/generic.go
- pkg/yurtmanager/controller/apis/config/types.go
- test/e2e/cmd/init/constants/constants.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Improve lease configuration for yurt-manager component. use `componentbaseconfig.LeaderElectionConfiguration` instead of defining parameters.
Fixes #
```release-note
```
> improve lease lock for yurt-manager component

- charts/yurt-manager/templates/yurt-manager-auto-generated.yaml
- charts/yurt-manager/templates/yurt-manager.yaml
- pkg/yurtmanager/controller/yurtappdaemon/yurtappdaemon_controller.go
- pkg/yurtmanager/controller/yurtappset/yurtappset_controller.go
- pkg/yurtmanager/controller/yurtcoordinator/cert/yurtcoordinatorcert_controller.go
- pkg/yurtmanager/webhook/server.go
- pkg/yurtmanager/webhook/util/controller/webhook_controller.go
- pkg/yurtmanager/webhook/util/writer/certwriter.go
- pkg/yurtmanager/webhook/util/writer/error.go
- pkg/yurtmanager/webhook/util/writer/secret.go
- test/e2e/cmd/init/constants/constants.go
- test/e2e/cmd/init/util/kubernetes/apply_addons.go
- test/e2e/cmd/init/util/kubernetes/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
In order to improve the security setting for yurt-manager component, improve secret resource rbac settings for yurt-manager as following:
1. move secret rbac settings from clusterrole to role
2. secret rbac verbs only left `update` and `get`. remove other verbs like create and delete.
Fixes #
```release-note
```
> improve rabc settings of secrets for yurt-manager component

- cmd/yurthub/app/options/options.go
- cmd/yurthub/app/options/options_test.go
- pkg/yurthub/certificate/manager/manager.go
- pkg/yurthub/certificate/manager/manager_test.go
- pkg/yurthub/network/dummyif_linux.go
- pkg/yurthub/network/network.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
disable iptables setting of Yurthub component by default, and we will remove iptables setting in the future. this means we will remove parameter `--enable-iptables` of yurthub.
the reason as following:
> We originally expected that these iptables configurations would help clients in the container network to have access to yurthub's dummy interface, but in fact many situations prevented yurthub from running and caused confusion for users. At the same time, we found that without …
> disable the iptables setting of yurthub component by default

- CHANGELOG.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
update changelog file for release v1.4
@LavenderQAQ please add changelog info for SIG IoT in **yurt-iot-dock** chapter.
Fixes #
```release-note
```
> update changelog for release-v1.4

- CHANGELOG.md
/sig iot
Add iot section in changelog for release-v1.4.
> docs: add iot section in changelog for release-v1.4

- .github/workflows/rerun-failed-workflows.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
reviewers or higher member can comment `/rerun` to trigger github actions that will rerun all failed workflows of the pull request.
Fixes #
```release-note
```
> add rerun failed workflows script

- .github/workflows/rerun-failed-workflows.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
fix /rerun command error
Fixes #
```release-note
```
> fix rereun failed jobs in workflow of github actions

- pkg/yurthub/cachemanager/cache_manager.go
What type of PR is this?
/kind good-first-issue
/kind feature
What this PR does / why we need it:
fix error log format in cache manager.
Which issue(s) this PR fixes:
Fixes #1776
> feat:fix error log format in cache manager

- pkg/yurthub/proxy/util/util.go
/kind feature
Improve request proxy log in yurthub component.
Fixes #1772
> feat: improve request proxy log in yurthub component (#1772)

- pkg/yurtmanager/controller/yurtappoverrider/yurtappoverrider_controller.go
Add Cache Cleanup and Update on Deletion and Changes
When a `YurtAppOverrider` instance is deleted, the cache data in `CacheOverriderMap` should also be removed. This ensures that the cache stays synchronized with the actual instances.
Additionally, when entries of `YurtAppOverrider` are changed, the controller now updates the new instance into `CacheOverriderMap`. This guarantees that the cache reflects the latest changes in the `YurtAppOverrider` instances.
#1793
> fix the cache leak in yurtappoverrider controller

- pkg/yurtmanager/webhook/util/configuration/configuration.go
if a ValidatingWebhook is disabled, the following logs will always be output continuously. and this affects the user's ability to parse yurt-manager's logs.
so modify the log level from warning to info5
#1820
> Added logs of yurt-manager component

- pkg/yurtmanager/controller/raven/dns/dns_controller.go
- pkg/yurtmanager/controller/raven/dns/dns_enqueue_handlers.go
- pkg/yurtmanager/controller/raven/gatewayinternalservice/gateway_internal_service_controller.go
- pkg/yurtmanager/controller/raven/gatewayinternalservice/gateway_internal_service_enqueue_handlers.go
- pkg/yurtmanager/controller/raven/gatewaypickup/gateway_pickup_controller.go
- pkg/yurtmanager/controller/raven/gatewaypickup/gateway_pickup_enqueue_handlers.go
- pkg/yurtmanager/controller/raven/gatewaypublicservice/gateway_public_service_controller.go
- pkg/yurtmanager/controller/raven/gatewaypublicservice/gateway_public_service_enqueue_handlers.go
> Reduce redundant logs

- pkg/yurtmanager/controller/controller.go
it is easy to verify which controllers are registered if register log is printed out, so  improve the log print of controller register in the entry point instead of in each controller register function.
#1813
> print out all registered controllers

- pkg/yurtmanager/controller/controller.go
- pkg/yurtmanager/controller/nodelifecycle/node_lifecycle_controller.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
improve FieldIndexer setting in yurt-manager
Fixes #1794
```release-note
```
> improve FieldIndexer setting in yurt-manager

- pkg/yurtadm/cmd/config/config.go
- pkg/yurtadm/cmd/join/join.go
- pkg/yurtadm/constants/constants.go
/kind bug
Fixes #1836 
```release-note
```
> fix: yurtadm join ignorePreflightErrors could not set all

- pkg/yurtmanager/controller/yurtappdaemon/workloadcontroller/deployment_controller.go
- pkg/yurtmanager/controller/yurtappdaemon/workloadcontroller/deployment_controller_test.go
- pkg/yurtmanager/webhook/deploymentrender/v1alpha1/deploymentrender_default.go
- pkg/yurtmanager/webhook/deploymentrender/v1alpha1/deploymentrender_webhook_test.go
/kind bug
Currently,  deployment overrider webhook will override the deployment spec owned by a yad(yurtappdaemon) with the yad template. However, the `nodeselector` field in the deployment spec will be set to null because it's not set in the yad template but set by the yad controller. This leads to [issue](https://github.com/openyurtio/openyurt/issues/1841).
We need to use the `applyTemplate` in the yad controller to get the complete deployment spec.
Fixes # https://github.com/openyurtio/openyurt/issues/1841
@rambohe-ch  @vie-serendipity 
```release-note
```
> Fix: webhook overwrite deployment owned by yad/yas

- docs/proposals/20231219-reduce-traffic-spike-during-rapid-node-additions.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Add a proposal to reduce cloud-edge traffic spike during rapid node additions.
Fixes #
```release-note
```
> proposal: add NodeBucket to reduce cloud-edge traffic spike during rapid node additions.

- cmd/yurthub/app/options/options.go
Adds a new validation for dummy interface length not to exceed 15 chars. 
Fixes #1867 
/@rambohe-ch
```release-note
NONE
```
> Feature: add name-length of dummy interface too long error

- charts/yurt-manager/templates/yurt-manager-auto-generated.yaml
- pkg/yurtmanager/controller/nodelifecycle/node_lifecycle_controller.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
If role of nodes/status resource is missing, the operation of yurt-manager(nodelifecycle-controllerr) to update the node status is prohibited.
Fixes #1882 
```release-note
```
> fix(yurt-manager): add clusterrole for nodes/status subresources

- cmd/yurt-iot-dock/app/core.go
/sig iot 
/kind bug
Remove exit reclaim logic to avoid iot-dock actively delete resources on edgex due to extreme concurrency.
Fixes #1887
/assign @LavenderQAQ @Rui-Gan
Users need to take the initiative to remove cr resources: device/deviceprofile/deviceservice.
```release-note
kubectl patch device hangzhou-random-boolean-device -p '{"metadata":{"finalizers":[]}}' --type=merge && kubectl delete device hangzhou-random-boolean-device
```
> fix: remove custom signal handler for concurrent reclaims

- pkg/yurtadm/util/kubernetes/kubernetes.go
/kind bug
fix: yurtadm join can't work when kubernetes version is large than v1.27.0
Fixes #1675
```release-note
```
> fix: yurtadm join can't work when kubernetes version large than v1.27.0

- test/fuzz/yurtappdaemon_fuzzer.go
/kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
> fix fuzz controller spell

- pkg/yurtmanager/controller/yurtappdaemon/yurtappdaemon_controller.go
- pkg/yurtmanager/controller/yurtappset/yurtappset_controller.go
> /kind bug
After editing yad's spec, there is a new created ControllerRevision. 
However, yad's status isn't updated because the function updateStatus use param `currentRevision`, instead of the updated value. We can see that in https://github.com/openyurtio/openyurt/blob/master/pkg/yurtmanager/controller/yurtappdaemon/yurtappdaemon_controller.go#L203
So, when invoking function updateStatus, we just need to replace `currentRevision` to `expectedRevision` to solve this problem.
Fixes #1879
> fix: yad status should be updated according to the new created ControllerRevision (#1879)

- docs/proposals/20240102-upgrade-yurtappset-to-v1beta1.md
> /kind bug
/kind question
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
```
> add yurtappset v1beta1 proposal

- pkg/yurtmanager/controller/platformadmin/config/EdgeXConfig/config-nosecty.json
- pkg/yurtmanager/controller/platformadmin/config/EdgeXConfig/config.json
- pkg/yurtmanager/controller/platformadmin/config/EdgeXConfig/manifest.yaml
- test/e2e/yurt/iot.go
/kind feature
/sig iot
The latest edgex version is adapted through the auto-collector.
The configuration is generated automatically, so be sure to test it once in the openyurt environment to ensure the availability of the new version.
> feat: support edgex napa version by auto-collector

- cmd/yurt-manager/app/options/daemonpodupdatercontroller.go
- cmd/yurt-manager/app/options/options.go
- pkg/yurtmanager/controller/apis/config/types.go
- pkg/yurtmanager/controller/daemonpodupdater/config/types.go
- pkg/yurtmanager/controller/daemonpodupdater/daemon_pod_updater_controller.go
improve the configuration of concurrent daemonpodupdater worker in yurt-manager component
Fixes #1907
> feat: improve configuration of concurrent daemon pod updater workers (#1907)

- cmd/yurt-manager/app/options/options.go
- cmd/yurt-manager/app/options/podbindingcontroller.go
- pkg/yurtmanager/controller/apis/config/types.go
- pkg/yurtmanager/controller/yurtcoordinator/podbinding/config/types.go
- pkg/yurtmanager/controller/yurtcoordinator/podbinding/podbinding_controller.go
improve the configuration of concurrent pod-binding worker in yurt-manager component
Fixes #1917
> feat: improve configuration of concurrent pod-binding workers (#1917)

- cmd/yurt-manager/app/options/delegateleasecontroller.go
- cmd/yurt-manager/app/options/options.go
- pkg/yurtmanager/controller/apis/config/types.go
- pkg/yurtmanager/controller/yurtcoordinator/delegatelease/config/types.go
- pkg/yurtmanager/controller/yurtcoordinator/delegatelease/delegatelease_controller.go
improve the configuration of concurrent delegate-lease worker in yurt-manager component
Fixes #1918
> feat: improve configuration of concurrent delegate-lease workers (#1918)

- cmd/yurt-manager/app/options/podbindingcontroller.go
> /kind bug
modify mismatched code comments in podbindingcontroller
> fix: modify mismatched code comments in podbindingcontroller

- pkg/yurthub/filter/constant.go
- pkg/yurthub/filter/discardcloudservice/filter.go
- pkg/yurthub/filter/discardcloudservice/filter_test.go
have improved discardcloudservice filter in yurthub component
only discarding LoadBalancer service which has annotation `svc.openyurt.io/discard=true`, instead of which doesn't have `openyurt.io/skip-discard=true`.
Fixes #1924
> feat: improve discardcloudservice filter in yurthub component (#1924)

- charts/yurt-manager/templates/yurt-manager-auto-generated.yaml
- pkg/yurtmanager/controller/yurtstaticset/yurtstaticset_controller.go
/kind bug
Node lifecycle controller in yurt-manager maybe miss rbac settings.
Fixes #1934
```release-note
NONE
```
> Add missing verb to the role of node lifecycle controller

- pkg/yurthub/cachemanager/cache_manager.go
- pkg/yurthub/cachemanager/cache_manager_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
don't cache csr and sar resource on edge nodes
Fixes #1880
```release-note
```
> don't cache csr and sar resource in yurthub

- pkg/yurthub/filter/approver.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind bug
yurt-hub-cfg configmap is used in multiple places, like:
- https://github.com/openyurtio/openyurt/blob/master/pkg/yurthub/cachemanager/cache_agent.go#L72
- https://github.com/openyurtio/openyurt/blob/master/pkg/yurthub/filter/approver.go#L126
In the [cache manager](https://github.com/openyurtio/openyurt/blob/master/pkg/yurthub/cachemanager/cache_agent.go#L72), configmap is read, but in the [approver](https://github.com/openyurtio/openyurt/blob/master/pkg/yurthub/filter/approver.go#L126) …
> fix cache manager panic in yurthub

- pkg/util/kubernetes/controller/hash/hash.go
- pkg/util/kubernetes/controller/history/controller_history.go
- pkg/yurtmanager/controller/yurtappset/revision.go
such as https://github.com/openyurtio/openyurt/blob/34b14ccadfe26b8956144d21ec62a79a3aef1760/pkg/yurtmanager/controller/yurtappset/revision.go#L96
https://github.com/openyurtio/openyurt/blob/34b14ccadfe26b8956144d21ec62a79a3aef1760/pkg/yurtmanager/controller/yurtappset/revision.go#L103
https://github.com/openyurtio/openyurt/blob/34b14ccadfe26b8956144d21ec62a79a3aef1760/pkg/yurtmanager/controller/yurtappset/revision.go#L193
they all call functions in `k8s.io/kubernetes/pkg/controller/history`, for avoiding this, just simply copy related functions codes into `pkg/util/kebernetes`, then we can call these functions in our directory.
Fixes #1967
> feat: Avoid calling functions under package k8s.io/kubernetes, move it to util (#1967)

- pkg/yurthub/filter/base/base_test.go
- pkg/yurthub/filter/discardcloudservice/filter.go
- pkg/yurthub/filter/discardcloudservice/filter_test.go
- pkg/yurthub/filter/inclusterconfig/filter.go
- pkg/yurthub/filter/inclusterconfig/filter_test.go
- pkg/yurthub/filter/initializer/initializer_test.go
- pkg/yurthub/filter/interfaces.go
- pkg/yurthub/filter/masterservice/filter.go
- pkg/yurthub/filter/masterservice/filter_test.go
- pkg/yurthub/filter/nodeportisolation/filter.go
- pkg/yurthub/filter/nodeportisolation/filter_test.go
- pkg/yurthub/filter/responsefilter/filter.go
- pkg/yurthub/filter/responsefilter/filter_test.go
- pkg/yurthub/filter/servicetopology/filter.go
- pkg/yurthub/filter/servicetopology/filter_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
Move list object handling in every ObjectFilter(like masterservice, servicetopology, etc.) into `ResponseFilter`, so each ObjectFilter only need to handle single object.
Fixes #1990 
```release-note
```
> move list object handling from ObjectFilter into ResponseFilter

- pkg/yurthub/filter/inclusterconfig/filter.go
- pkg/yurthub/filter/masterservice/filter.go
- pkg/yurthub/filter/nodeportisolation/filter.go
- pkg/yurthub/filter/responsefilter/filter.go
- pkg/yurthub/filter/responsefilter/filter_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
ResponseFilter return `watch.Deleted` event back to clients when Standalone object is filtered to nil in ObjectFilters.
by the way, this feature will be helpful for all ObjectFilters, not only for `nodeportisolation` filter.
Fixes #1994 
```release-note
```
> return back watch.Deleted event to clients when watch object is removed in OjbectFilters

- go.mod
- go.sum
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
The runc(1.1.5) package indirectly imported by openyurt has some security risks before version 1.1.11, so the minor version number of the runc package is upgraded to version 1.1.12.
For specific details of security risks, please refer to: [summary](https://devhub.checkmarx.com/cve-details/CVE-2024-21626/)
Fixes #
```release-note
```
> fix: upgrade the version of runc to avoid security risk

- cmd/yurthub/app/options/filters.go
- pkg/yurthub/certificate/server/server.go
- pkg/yurthub/filter/forwardkubesvctraffic/filter.go
- pkg/yurthub/filter/forwardkubesvctraffic/filter_test.go
- pkg/yurthub/filter/responsefilter/filter_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
add a new ObjectFilter named `forwardkubesvctraffic` in order to improve transparent management mechanism for control traffic from edge to cloud.
the detail design of this filter, the proposal link is here: https://github.com/openyurtio/openyurt/pull/1975
Fixes #
```release-note
```
> add forwardkubesvctraffic filter and adapt server certificate

- charts/yurt-manager/crds/network.openyurt.io_poolservices.yaml
- hack/make-rules/kustomize_to_chart.sh
- pkg/apis/network/v1alpha1/poolservice_types.go
- pkg/apis/network/v1alpha1/zz_generated.deepcopy.go
> /kind design
> /sig network
Add two fields AggregateToAnnotations and AggregateToLabels to status
-  AggregateToAnnotations means that this information is aggregated into the annotations of the service
-  AggregateToLabels means that this information is aggregated into the labels of the service
```release-note
YES
```
> modify status of poolservice

- SECURITY.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
mail: security@mail.openyurt.io seems that there are some problems, so change the mail address for security disclosure.
Fixes #
```release-note
```
> change mail address for security disclosure

- pkg/yurtmanager/controller/loadbalancerset/loadbalancerset/loadbalancerset_controller.go
- pkg/yurtmanager/controller/loadbalancerset/loadbalancerset/predicate.go
- pkg/yurtmanager/controller/loadbalancerset/loadbalancerset/predicate_test.go
> /kind bug
> /sig network
Fix the problem of failure to update service status
```release-note
YES
```
> fix service status update.

- pkg/yurtmanager/controller/platformadmin/config/EdgeXConfig/config-nosecty.json
- pkg/yurtmanager/controller/platformadmin/config/EdgeXConfig/config.json
/kind bug
/sig iot
The default maxSurge value for k8s deployment is 25%, and when replicas is 1, maxSurge is 1 after rounding up. This results in the existence of 2 identical edgex components at the same time after a quick create + update operation, and edgex components use a registration mechanism. If a component preregisters and is terminated by workload, this causes the metadata component to scramble. This chaos manifests itself in the form of other components crashing all the time.
I updated `auto-collector` to directly inject the default maxSurge value of 0 into the config file and the issue was resolved.
Fixes #2028
> fix: edgex component creation cause registration errors and core-command crash

- pkg/util/file/file.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Fixes #
```release-note
NONE
```
> fix: close dst file

- pkg/yurtmanager/webhook/pod/v1alpha1/pod_default.go
- pkg/yurtmanager/webhook/pod/v1alpha1/pod_default_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Because of terms in pod.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution.NodeSelectorTerms are ORed, not ANDed, so we need to add excludeHostNetworkRequirement for each NodeSelectorTerms.
Fixes #
```release-note
```
> improve pod webhook for adapting hostnetwork mode nodepool

- pkg/yurthub/cachemanager/cache_manager.go
- pkg/yurthub/proxy/proxy.go
- pkg/yurthub/proxy/util/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
Fixes #
```release-note
NONE
```
> intercept kubelet get node request in order to reduce the traffic

- docs/proposals/20240517-separate-yurtmanager-clients.md
Propose a plan for separating yurt-manager clients.
Fixes #
```release-note
```
> Proposal: separate yurt-manager clients

- pkg/yurthub/kubernetes/meta/restmapper.go
- pkg/yurthub/kubernetes/meta/restmapper_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
because plural of gateway is gateways instead of gatewaies in raven, so we need to deal with gateway resource specially in restmapper of yurthub component.
Fixes #
```release-note
```
> improve restmapper for gateway resource

- pkg/yurtmanager/controller/csrapprover/csrapprover_controller.go
- pkg/yurtmanager/controller/csrapprover/csrapprover_controller_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
in controller-runtime v0.16, client.Client is supported to update csr approval. so remove original kubernetes client in csr approver controller and use the client.Client to replace it.
Fixes #
```release-note
```
> improve csr approver controller by replacing kubernetes client with client.Client

- cmd/yurt-manager/app/options/nodepoolcontroller.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind bug
revert pull request #2007 
Fixes #
```release-note
```
> revert nodepool controller parameter that has been removed in #2007

- cmd/yurt-manager/app/options/nodepoolcontroller.go
- pkg/yurtmanager/controller/nodepool/config/types.go
- pkg/yurtmanager/controller/nodepool/nodepool_controller.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
The parameter `ConcurrentNodepools ` is not match with NodePool controller, so rename it to `ConcurrentNodePoolWorkers`.
Fixes #
```release-note
```
> rename ConcurrentNodepools to ConcurrentNodePoolWorkers

- pkg/yurtmanager/webhook/node/v1/node_handler.go
- pkg/yurtmanager/webhook/pod/v1alpha1/pod_handler.go
- pkg/yurtmanager/webhook/util/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Because of Group is empty for `node` and `pod` resource, so webhook paths are not registered correctly.
The detail logs are as following:
```
I0618 03:23:08.492989       1 webhook.go:158] controller-runtime/builder "msg"="Registering a mutating webhook" "GVK"={"Group":"","Version":"v1","Kind":"Node"} "path"="/mutate--v1-node"
I0618 03:23:08.493039       1 server.go:183] controller-runtime/webhook "msg"="Registering webhook" "path"="/mutate--v1-node"
I0618 03:23:08.493061 …
```
> improve independent webhook

- pkg/yurthub/cachemanager/cache_manager.go
- pkg/yurthub/cachemanager/storage_wrapper.go
- pkg/yurthub/proxy/autonomy/autonomy.go
- pkg/yurthub/server/nonresource.go
- pkg/yurthub/server/nonresource_test.go
- pkg/yurthub/storage/disk/storage.go
- pkg/yurthub/storage/disk/storage_test.go
- pkg/yurthub/storage/etcd/storage.go
- pkg/yurthub/storage/key.go
- pkg/yurthub/storage/store.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
Fixes #
```release-note
```
> fix: upload autonomy status correctly

- .github/workflows/sync-charts.yaml
- hack/lib/sync-charts.sh
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
because `secrets.SYNC_CHARTS_SECRET` is used for syncing charts to `openyurtio/openyurt-helm` repo. so we create a new key named `SYNC_OPENYURTIO_CHARTS_KEY` for syncing charts to `openyurtio/charts` repo.
moreover, charts releaser only rely on the version filed in the Chart.yaml of helm chart, so we remove the `$VERSION` info in the `sync-charts.sh`
Fixes #
```release-note
```
> feat: use secrets.SYNC_OPENYURTIO_CHARTS_KEY to sync charts to openyurtio/charts repo.

- pkg/yurtmanager/controller/platformadmin/config/EdgeXConfig/config-nosecty.json
- pkg/yurtmanager/controller/platformadmin/config/EdgeXConfig/config.json
/kind bug
/sig iot
In the napa version, the host's `/etc/localtime` file is mounted as a file, whereas previously the default bind type for `openyurt/auto-collector` was a folder. This pr is fixed to file.
This may have caused pr #2103 to fail iot e2e.
> fix(iot): the mount type of hostpath for localtime in napa

- .github/workflows/ci.yaml
/kind bug
fix codecov not valid tokenless upload error like this: https://github.com/openyurtio/openyurt/actions/runs/10227408471/job/28298818547
The fixes are suggested from https://github.com/codecov/codecov-action/issues/1487#issuecomment-2225600449
@rambohe-ch 
```release-note
```
> fix: codecov not valid tokenless upload

- pkg/yurtmanager/controller/platformadmin/platform_admin_controller.go
- pkg/yurtmanager/webhook/platformadmin/v1alpha1/platformadmin_validation.go
- pkg/yurtmanager/webhook/platformadmin/v1alpha2/platformadmin_validation.go
/kind feature
Upgrade IoT component platformadmin's yurtappset dependencies to v1beta1
Fixes #1941
@luc99hen @LavenderQAQ
> feat: Upgrade platformadmin's yurtappset dependencies to v1beta1

- pkg/yurtmanager/controller/raven/dns/gateway_dns_controller_test.go
- pkg/yurtmanager/controller/raven/dns/gateway_dns_enqueue_handlers_test.go
- pkg/yurtmanager/controller/raven/gatewayinternalservice/gateway_internal_service_controller_test.go
- pkg/yurtmanager/webhook/gateway/v1alpha1/gateway_default_test.go
- pkg/yurtmanager/webhook/gateway/v1alpha1/gateway_validation.go
- pkg/yurtmanager/webhook/gateway/v1alpha1/gateway_validation_test.go
- pkg/yurtmanager/webhook/gateway/v1beta1/gateway_default_test.go
- pkg/yurtmanager/webhook/gateway/v1beta1/gateway_validation.go
- pkg/yurtmanager/webhook/gateway/v1beta1/gateway_validation_test.go
- pkg/yurtmanager/webhook/yurtappdaemon/v1alpha1/yurtappdaemon_default_test.go
- pkg/yurtmanager/webhook/yurtappdaemon/v1alpha1/yurtappdaemon_validation_test.go
- pkg/yurtmanager/webhook/yurtappoverrider/v1alpha1/yurtappoverrider_default_test.go
- pkg/yurtmanager/webhook/yurtappoverrider/v1alpha1/yurtappoverrider_validation.go
- pkg/yurtmanager/webhook/yurtappoverrider/v1alpha1/yurtappoverrider_validation_test.go
- pkg/yurtmanager/webhook/yurtappset/v1beta1/yurtappset_default_test.go
- pkg/yurtmanager/webhook/yurtstaticset/v1alpha1/yurtstaticset_default_test.go
- pkg/yurtmanager/webhook/yurtstaticset/v1alpha1/yurtstaticset_validation_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
feat: add ut by tongyilingma and fix some error message
Fixes #
@rambohe-ch
> feat: add ut by tongyilingma and fix some error message

- cmd/yurthub/app/options/filters.go
- pkg/yurthub/filter/masterservice/filter.go
- pkg/yurthub/filter/responsefilter/filter_test.go
- pkg/yurthub/filter/serviceenvupdater/filter.go
- pkg/yurthub/filter/serviceenvupdater/filter_test.go
- pkg/yurtiotdock/clients/edgex-foundry/v3/deviceservice_client_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
Adds a filter in Yurthub that sets `KUBERNETES_SERVICE_HOST` and  `KUBERNETES_SERVICE_PORT` environment variable to the Yurthub proxy host and port. This enhancement aims to ensure node autonomy for edge nodes when they are operating offline.
Incluster client testing using image built from this PR:
We can see that both  `KUBERNETES_SERVICE_HOST` and  `KUBERNETES_SERVICE_PORT` are updated with the correct values
Fixes https://github.com/openyurtio/openyurt/issues/2158
/assign …
> Add yurthub service env updater filter

- pkg/yurthub/storage/disk/storage.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind bug
fix bug of issue 2133
Fixes #2133
```release-note
NONE
```
> fix: create abspath dir in case that contents is empty

- go.mod
- pkg/yurthub/cachemanager/cache_agent.go
- pkg/yurthub/cachemanager/cache_manager.go
- pkg/yurthub/cachemanager/cache_manager_test.go
- pkg/yurthub/proxy/autonomy/autonomy.go
- pkg/yurthub/proxy/local/local.go
- pkg/yurthub/proxy/pool/pool.go
- pkg/yurthub/proxy/proxy.go
- pkg/yurthub/proxy/util/util.go
- pkg/yurthub/proxy/util/util_test.go
- pkg/yurthub/storage/disk/key_test.go
- pkg/yurthub/util/util.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind bug
support cache response for partial object metadata requests, like the following request:
```
curl -H "Accept: application/json;as=PartialObjectMetadataList;g=meta.k8s.io;v=v1" "$API_SERVER/apis/apiextensions.k8s.io/v1/customresourcedefinitions"
```
Fixes #2121 
```release-note
```
> [yurthub] support cache response for partial object metadata requests。

- pkg/yurthub/filter/masterservice/filter.go
- pkg/yurthub/filter/masterservice/filter_test.go
- pkg/yurthub/filter/responsefilter/filter_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Set `clusterIPs` field for masterservice filter.
CoreDNS will read it: https://github.com/coredns/coredns/blob/v1.11.3/plugin/kubernetes/kubernetes.go#L507
About [`ClusterIPs`](https://kubernetes.io/zh-cn/docs/reference/kubernetes-api/service-resources/service-v1/#ServiceSpec)
Fixes #
```release-note
```
> fix: masterservice missing clusterIPs field.

- cmd/yurthub/app/config/config.go
- cmd/yurthub/app/options/options.go
- cmd/yurthub/app/start.go
- go.mod
- go.sum
- pkg/yurthub/locallb/iptables.go
- pkg/yurthub/locallb/locallb.go
- pkg/yurthub/util/util.go
- pkg/yurthub/util/util_test.go
> /kind design
#2124
Fixes #2156
> Enhance operational efficiency of K8s cluster in user's IDC

- pkg/projectinfo/projectinfo.go
- pkg/yurtmanager/controller/util/node/controller_utils.go
- pkg/yurtmanager/controller/yurtcoordinator/podbinding/pod_binding_controller.go
- pkg/yurtmanager/controller/yurtcoordinator/podbinding/pod_binding_controller_test.go
/kind feature
Resolves https://github.com/openyurtio/openyurt/issues/2196
Fixes https://github.com/openyurtio/openyurt/issues/2196
```release-note
Adds a new node annotation node.openyurt.io/autonomy-duration which maps to pod tolerationSeconds to ensure pods are evicted during node failures.
```
```bash
k get nodes vagrant -o yaml
apiVersion: v1
kind: Node
metadata:
annotations:
node.openyurt.io/autonomy-duration: 30s
k get pods -o wide
NAME                               READY   STATUS    RESTARTS   AGE     IP               NODE                                NOMINATED NODE   READINESS GATES
netutils-6f94558c58-kvcwq          1/1     Running   0          3m50s   10.244.1.41      vagrant                             <none>           <none>
netutils-6f94558c58-pz9cp …
```
> feat: add node autonomy duration to lifecycle controller

- pkg/yurtmanager/webhook/util/writer/certwriter.go
- pkg/yurtmanager/webhook/util/writer/error.go
- pkg/yurtmanager/webhook/util/writer/fs.go
/kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
If the user set `WEBHOOK_HOST` environment variable, the webhook certs will be written to filesystem (`/tmp/yurt-manager-webhook-certs` by default), and the code has a type confusion of `notExistError` and `notFoundError`.
This PR also fix a null pointer dereference in `updateIfNotExists`.
Fixes #
```release-note
```
> fix: move notFoundError to notExistError

- charts/yurt-manager/templates/yurt-manager-auto-generated.yaml
- pkg/yurtmanager/controller/util/pod/pod_util.go
- pkg/yurtmanager/controller/util/pod/pod_util_test.go
- pkg/yurtmanager/webhook/endpoints/v1/endpoints_default.go
- pkg/yurtmanager/webhook/endpoints/v1/endpoints_default_test.go
- pkg/yurtmanager/webhook/endpoints/v1/endpoints_handler.go
- pkg/yurtmanager/webhook/server.go
Adds endpoint webhook for node autonomy feature. When the node lifecycle controller marks a pod not ready; the endpoints are removed. This webhook ensures those endpoints are still in the ready state when node autonomy feature is in use. 
Fixes https://github.com/openyurtio/openyurt/issues/2197
No
```bash
apiVersion: apps/v1
kind: Deployment
metadata:
annotations:
deployment.kubernetes.io/revision: "1"
meta.helm.sh/release-name: yurt-manager
meta.helm.sh/release-namespace: kube-system
creationTimestamp: "2024-12-01T22:26:12Z"
generation: 1
labels:
app.kubernetes.io/instance: yurt-manager
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: yurt-manager
app.kubernetes.io/version: v1.5.0
helm.sh/chart: yurt-manager-1.5.0
name: yurt-manager
namespace: kube-system …
```
> feat: add endpoints webhook for node autonomy

- charts/yurt-manager/templates/yurt-manager-auto-generated.yaml
- pkg/yurtmanager/webhook/endpointslice/v1/endpointslice_default.go
- pkg/yurtmanager/webhook/endpointslice/v1/endpointslice_default_test.go
- pkg/yurtmanager/webhook/endpointslice/v1/endpointslice_handler.go
- pkg/yurtmanager/webhook/server.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
This change adds a webhook in yurt-manager that updates endpoints within endpointslice resource from "not ready" to "ready" when the node has node autonomy configuration(node.openyurt.io/autonomy-duration). We don't want endpoints to be removed from endpointslice if node autonomy duration is configured.
Fixes https://github.com/openyurtio/openyurt/issues/2198
assign @rambohe-ch 
```release-note
NONE
```
Testing results:
```
// deployed yurt-manager with PR change
$ k get pod …
```
> Add endpointslice webhook for node autonomy

- SECURITY.md
> Modify safety reporting Email

- pkg/yurthub/cachemanager/cache_manager.go
- pkg/yurthub/cachemanager/cache_manager_test.go
- pkg/yurthub/cachemanager/storage_wrapper.go
- pkg/yurthub/proxy/util/util.go
- pkg/yurthub/proxy/util/util_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
improve saveWatchObject function in cache manager for supporting paritialobjectmetadata watch requests.
Fixes #2199 
```release-note
```
> fix: support cache response for partial object metedata watch request

- CODEOWNERS
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
add codeowners file for enforcing Access Control Rules to secure the code base against attacks.
In the first step, I add Openyurt-Maintainers team as CODEOWNER for the whole repository.
and we will keep improve the CODEOWNER assignment during incubation.
Fixes #
```release-note
```
> fix: add codeowners file for openyurt

- ROADMAP.md
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
Add OpenYurt Project 2024 Roadmap
Fixes #
```release-note
```
> add roadmap of 2024 for openyurt

- .golangci.yaml
- hack/make-rules/add_controller.sh
- pkg/yurtmanager/controller/daemonpodupdater/daemon_pod_updater_controller.go
- pkg/yurtmanager/controller/loadbalancerset/loadbalancerset/load_balancer_set_controller.go
- pkg/yurtmanager/controller/nodebucket/node_bucket_controller.go
- pkg/yurtmanager/controller/nodelifecycle/node_life_cycle_controller_test.go
- pkg/yurtmanager/controller/nodepool/nodepool_controller.go
- pkg/yurtmanager/controller/nodepool/nodepool_enqueue_handlers.go
- pkg/yurtmanager/controller/platformadmin/platform_admin_controller.go
- pkg/yurtmanager/controller/raven/dns/gateway_dns_controller.go
- pkg/yurtmanager/controller/raven/dns/gateway_dns_enqueue_handlers.go
- pkg/yurtmanager/controller/raven/gatewayinternalservice/gateway_internal_service_controller.go
- pkg/yurtmanager/controller/raven/gatewayinternalservice/gateway_internal_service_enqueue_handlers.go
- pkg/yurtmanager/controller/raven/gatewaypickup/gateway_pickup_controller.go
- pkg/yurtmanager/controller/raven/gatewaypickup/gateway_pickup_enqueue_handlers.go
- pkg/yurtmanager/controller/raven/gatewaypublicservice/gateway_public_service_controller.go
- pkg/yurtmanager/controller/raven/gatewaypublicservice/gateway_public_service_enqueue_handlers.go
- pkg/yurtmanager/controller/servicetopology/endpoints/endpoints_enqueue_handlers.go
- pkg/yurtmanager/controller/servicetopology/endpoints/service_topology_endpoints_controller.go
- pkg/yurtmanager/controller/servicetopology/endpointslice/endpointslice_enqueue_handlers.go
- pkg/yurtmanager/controller/servicetopology/endpointslice/service_topology_endpointslice_controller.go
- pkg/yurtmanager/controller/yurtappdaemon/yurt_app_daemon_controller.go
- pkg/yurtmanager/controller/yurtappoverrider/yurt_app_overrider_controller.go
- pkg/yurtmanager/controller/yurtcoordinator/cert/certificate.go
- pkg/yurtmanager/controller/yurtcoordinator/cert/secret.go
- pkg/yurtmanager/controller/yurtcoordinator/cert/util.go
- pkg/yurtmanager/controller/yurtcoordinator/cert/yurt_coordinator_cert_controller.go
- pkg/yurtmanager/controller/yurtcoordinator/podbinding/pod_binding_controller.go
- pkg/yurtmanager/controller/yurtstaticset/yurt_static_set_controller.go
- test/e2e/e2e_test.go
fix issue https://github.com/openyurtio/openyurt/issues/2234
Fixes #
```release-note
```
> fix: go lint errors

- pkg/yurtmanager/controller/util/node/controller_utils.go
- pkg/yurtmanager/controller/yurtcoordinator/podbinding/pod_binding_controller.go
- pkg/yurtmanager/controller/yurtcoordinator/podbinding/pod_binding_controller_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
1. configure toleration seconds of new pods after node autonomy is enabled.
2. restore toleration seconds of pods if node autonomy is disabled.
Fixes #2240 
```release-note
```
> feat: improve pod binding controller

- charts/yurt-manager/templates/yurt-manager-auto-generated.yaml
- pkg/yurtmanager/webhook/endpointslice/v1/endpointslice_default.go
- pkg/yurtmanager/webhook/endpointslice/v1/endpointslice_handler.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind bug
1. Endpointslices resource belongs to `discovery.k8s.io` group instead of core group. so we need to adapt webhook settings according to group `discovery.k8s.io`.
2. fix some miss of mutating endpointslices
Fixes #
```release-note
```
> fix: endpointslices belongs to discovery.k8s.io group

- pkg/yurtmanager/controller/yurtcoordinator/podbinding/pod_binding_controller.go
- pkg/yurtmanager/controller/yurtcoordinator/podbinding/pod_binding_controller_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind bug
improve pod binding controller as following:
1. only process edge nodes and pods which run on edge nodes.
2. add pod request into reconcile queue instead of adding node request.
Fixes #
```release-note
```
> fix add pod request into reconcile queue instead of node

- .github/workflows/ci.yaml
- Makefile
- hack/make-rules/local-up-openyurt.sh
- test/e2e/cmd/init/init.go
OpenYurt supports Kubernetes clusters version 1.30, and the e2e test kind cluster needs to be upgraded to 1.30.
-->
```release-note
none
```
> upgrade kind cluster to 1.30 for e2e.

- charts/yurt-manager/values.yaml
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
According to the proposal #2155 , we use endpoints/endpointslices webhook to replace the current design: improve nodelifecyle controller to manage pod ready status according to node autonomy settings.
so we plan to disable nodelifecycle controller by default in yurt-manager component, and we will remove this controller in the future version.
by the way, we also don't disable nodelifecycle controller in kube-controller-manager component anymore.
Fixes #
```release-note
We don't need …
```
> feat: disable nodelifecycle controller by default

- CHANGELOG.md
- README.md
- README.zh.md
- charts/yurt-coordinator/Chart.yaml
- charts/yurt-iot-dock/Chart.yaml
- charts/yurt-manager/Chart.yaml
- charts/yurthub/Chart.yaml
release openyurt v1.6.0
-->
```release-note
release openyurt v1.6.0
```
> release openyurt v1.6.0

- .github/workflows/release-assets.yaml
update go version to 1.22.3 for setup-go action.
```release-note
NONE
```
> update go version to 1.22.3 for setup-go action.

- cmd/yurthub/app/options/options.go
- pkg/yurthub/cachemanager/cache_manager.go
- pkg/yurthub/cachemanager/cache_manager_test.go
- pkg/yurthub/configuration/manager.go
- pkg/yurthub/filter/approver/approver.go
- pkg/yurthub/filter/approver/approver_test.go
- pkg/yurthub/filter/manager/manager_test.go
- pkg/yurthub/filter/responsefilter/filter_test.go
- pkg/yurthub/metrics/metrics.go
- pkg/yurthub/proxy/autonomy/autonomy_test.go
- pkg/yurthub/proxy/local/local_test.go
- pkg/yurthub/proxy/proxy.go
- pkg/yurthub/proxy/remote/loadbalancer.go
- pkg/yurthub/proxy/util/util.go
- pkg/yurthub/proxy/util/util_test.go
- pkg/yurthub/util/util.go
- pkg/yurthub/util/util_test.go
> /kind bug
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
/kind feature
1. remove latency metrics(proxyLatencyCollector) of yurthub, because this metric is not useful for end users.
2. remove WithMaxInFlightLimit handler, because requests are aggregated by multiplexer in yurthub, so requests limit is not needed for controlling requests volume.
3.  remove WithCacheHeaderCheck handler, because Edge-Cache header is rarely used.
4. improve WithRequestClientComponent handler, add whole user agent into request context, and truncate user agent by callers.
5. …
> feat: improve proxy handler of yurthub

- charts/yurt-manager/templates/yurt-manager-auto-generated.yaml
- cmd/yurt-manager/app/options/hubleaderconfigcontroller.go
- cmd/yurt-manager/app/options/options.go
- cmd/yurt-manager/names/controller_names.go
- pkg/projectinfo/projectinfo.go
- pkg/yurtmanager/controller/apis/config/types.go
- pkg/yurtmanager/controller/base/controller.go
- pkg/yurtmanager/controller/hubleader/hubleader_controller.go
- pkg/yurtmanager/controller/hubleaderconfig/config/types.go
- pkg/yurtmanager/controller/hubleaderconfig/hubleaderconfig_controller.go
- pkg/yurtmanager/controller/hubleaderconfig/hubleaderconfig_controller_test.go
- pkg/yurtmanager/controller/util/nodepool/nodepool.go
- pkg/yurtmanager/controller/util/nodepool/nodepool_test.go
/kind feature
Adds hubleader config controller to create configmap for the nodepool leader and pool scoped metadata
Fixes https://github.com/openyurtio/openyurt/issues/2260
```release-note
NONE
```
An internal CRD would be an improvement than a configmap to have a structured schema. Endpoints resource was not used due to character limitations using annotations to store poolscoped metadata. It was decided to use a config map instead.
> feat: add hub leader config controller

- charts/yurt-manager/crds/apps.openyurt.io_nodepools.yaml
- pkg/apis/apps/v1beta2/nodepool_types.go
- pkg/apis/apps/v1beta2/zz_generated.deepcopy.go
- pkg/yurtmanager/controller/hubleader/hubleader_controller.go
- pkg/yurtmanager/controller/hubleader/hubleader_controller_test.go
- pkg/yurtmanager/controller/hubleaderconfig/hubleaderconfig_controller.go
- pkg/yurtmanager/controller/hubleaderconfig/hubleaderconfig_controller_test.go
- pkg/yurtmanager/webhook/nodepool/v1beta2/nodepool_default.go
- pkg/yurtmanager/webhook/nodepool/v1beta2/nodepool_default_test.go
Adds enablePoolScopeMetadata and moves pool scope metadata to GroupVersionResource rather than GVK. enablePoolScopMetadata will be used to control whether reuse of list/watch events within the nodepool will occur. This differs from using interConnectivity field in NodePool spec. 
Fixes https://github.com/openyurtio/openyurt/issues/2306
```release-note
NONE
```
> feat: update nodepool spec

- pkg/yurtmanager/controller/hubleaderconfig/hubleaderconfig_controller_test.go
- pkg/yurtmanager/webhook/nodepool/v1beta2/nodepool_default.go
- pkg/yurtmanager/webhook/nodepool/v1beta2/nodepool_default_test.go
- test/e2e/yurt/hubleader.go
/kind bug
When moving from GVK to GVR in poolscoped metadata, the core.v1.services was left with group. We need to remove group from GVR for v1.services.
Fixes https://github.com/openyurtio/openyurt/issues/2317
```release-note
NONE
```
> fix: update gvr for core.v1.services

- pkg/yurtmanager/controller/hubleaderconfig/hubleaderconfig_controller.go
- pkg/yurtmanager/controller/hubleaderconfig/hubleaderconfig_controller_test.go
- pkg/yurtmanager/webhook/nodepool/v1beta2/nodepool_default.go
- pkg/yurtmanager/webhook/nodepool/v1beta2/nodepool_default_test.go
- test/e2e/yurt/hubleader.go
/kind bug
Hub leader config should be deleted when nodepool is deleted
Fixes https://github.com/openyurtio/openyurt/issues/2323
```release-note
None
```
* Removed set enableLeaderElection = false from defaulting webhook. Should not set this default. 
* Created e2e scenario for hub leader config clean up
> fix: ensure hub leader configmap is deleted with nodepool

- charts/yurt-manager/crds/apps.openyurt.io_nodepools.yaml
- pkg/apis/apps/v1beta2/nodepool_types.go
- pkg/apis/apps/v1beta2/zz_generated.deepcopy.go
- pkg/yurtmanager/controller/hubleader/hubleader_controller.go
- pkg/yurtmanager/controller/hubleader/hubleader_controller_test.go
- test/e2e/yurt/hubleader.go
- test/e2e/yurt/nodepool.go
/kind feature
Adds status information to the nodepool when using `k get nodepools`
Fixes https://github.com/openyurtio/openyurt/issues/2331
```release-note
NONE
```
> feat: add printer columns for leaders
